/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:1" *)
module demux_8_32_sintetizado(clk_4f, data_in, valid, reset, data_out, valid_out);
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  wire [31:0] _000_;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  wire [1:0] _001_;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:1" *)
  input clk_4f;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:2" *)
  input [7:0] data_in;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:5" *)
  output [31:0] data_out;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:4" *)
  input reset;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:8" *)
  wire [1:0] selector;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:3" *)
  input valid;
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:6" *)
  output valid_out;
  NOT _123_ (
    .A(selector[0]),
    .Y(_105_)
  );
  NOT _124_ (
    .A(selector[1]),
    .Y(_106_)
  );
  NOT _125_ (
    .A(data_in[0]),
    .Y(_107_)
  );
  NOT _126_ (
    .A(data_in[1]),
    .Y(_108_)
  );
  NOT _127_ (
    .A(data_in[2]),
    .Y(_109_)
  );
  NOT _128_ (
    .A(data_in[3]),
    .Y(_110_)
  );
  NOT _129_ (
    .A(data_in[4]),
    .Y(_111_)
  );
  NOT _130_ (
    .A(data_in[5]),
    .Y(_112_)
  );
  NOT _131_ (
    .A(data_in[6]),
    .Y(_113_)
  );
  NOT _132_ (
    .A(data_in[7]),
    .Y(_114_)
  );
  NOT _133_ (
    .A(valid),
    .Y(_115_)
  );
  NAND _134_ (
    .A(_105_),
    .B(valid),
    .Y(_116_)
  );
  NOR _135_ (
    .A(_106_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _136_ (
    .A(data_out[8]),
    .B(_117_),
    .Y(_118_)
  );
  NAND _137_ (
    .A(_107_),
    .B(_117_),
    .Y(_119_)
  );
  NAND _138_ (
    .A(reset),
    .B(_119_),
    .Y(_120_)
  );
  NOR _139_ (
    .A(_118_),
    .B(_120_),
    .Y(_000_[8])
  );
  NOR _140_ (
    .A(data_out[9]),
    .B(_117_),
    .Y(_121_)
  );
  NAND _141_ (
    .A(_108_),
    .B(_117_),
    .Y(_122_)
  );
  NAND _142_ (
    .A(reset),
    .B(_122_),
    .Y(_003_)
  );
  NOR _143_ (
    .A(_121_),
    .B(_003_),
    .Y(_000_[9])
  );
  NOR _144_ (
    .A(data_out[10]),
    .B(_117_),
    .Y(_004_)
  );
  NAND _145_ (
    .A(_109_),
    .B(_117_),
    .Y(_005_)
  );
  NAND _146_ (
    .A(reset),
    .B(_005_),
    .Y(_006_)
  );
  NOR _147_ (
    .A(_004_),
    .B(_006_),
    .Y(_000_[10])
  );
  NOR _148_ (
    .A(data_out[11]),
    .B(_117_),
    .Y(_007_)
  );
  NAND _149_ (
    .A(_110_),
    .B(_117_),
    .Y(_008_)
  );
  NAND _150_ (
    .A(reset),
    .B(_008_),
    .Y(_009_)
  );
  NOR _151_ (
    .A(_007_),
    .B(_009_),
    .Y(_000_[11])
  );
  NOR _152_ (
    .A(data_out[12]),
    .B(_117_),
    .Y(_010_)
  );
  NAND _153_ (
    .A(_111_),
    .B(_117_),
    .Y(_011_)
  );
  NAND _154_ (
    .A(reset),
    .B(_011_),
    .Y(_012_)
  );
  NOR _155_ (
    .A(_010_),
    .B(_012_),
    .Y(_000_[12])
  );
  NOR _156_ (
    .A(data_out[13]),
    .B(_117_),
    .Y(_013_)
  );
  NAND _157_ (
    .A(_112_),
    .B(_117_),
    .Y(_014_)
  );
  NAND _158_ (
    .A(reset),
    .B(_014_),
    .Y(_015_)
  );
  NOR _159_ (
    .A(_013_),
    .B(_015_),
    .Y(_000_[13])
  );
  NOR _160_ (
    .A(data_out[14]),
    .B(_117_),
    .Y(_016_)
  );
  NAND _161_ (
    .A(_113_),
    .B(_117_),
    .Y(_017_)
  );
  NAND _162_ (
    .A(reset),
    .B(_017_),
    .Y(_018_)
  );
  NOR _163_ (
    .A(_016_),
    .B(_018_),
    .Y(_000_[14])
  );
  NOR _164_ (
    .A(data_out[15]),
    .B(_117_),
    .Y(_019_)
  );
  NAND _165_ (
    .A(_114_),
    .B(_117_),
    .Y(_020_)
  );
  NAND _166_ (
    .A(reset),
    .B(_020_),
    .Y(_021_)
  );
  NOR _167_ (
    .A(_019_),
    .B(_021_),
    .Y(_000_[15])
  );
  NAND _168_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_022_)
  );
  NOT _169_ (
    .A(_022_),
    .Y(_023_)
  );
  NOR _170_ (
    .A(_115_),
    .B(_022_),
    .Y(_024_)
  );
  NOR _171_ (
    .A(data_out[0]),
    .B(_024_),
    .Y(_025_)
  );
  NAND _172_ (
    .A(_107_),
    .B(_024_),
    .Y(_026_)
  );
  NAND _173_ (
    .A(reset),
    .B(_026_),
    .Y(_027_)
  );
  NOR _174_ (
    .A(_025_),
    .B(_027_),
    .Y(_000_[0])
  );
  NOR _175_ (
    .A(data_out[1]),
    .B(_024_),
    .Y(_028_)
  );
  NAND _176_ (
    .A(_108_),
    .B(_024_),
    .Y(_029_)
  );
  NAND _177_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NOR _178_ (
    .A(_028_),
    .B(_030_),
    .Y(_000_[1])
  );
  NOR _179_ (
    .A(data_out[2]),
    .B(_024_),
    .Y(_031_)
  );
  NAND _180_ (
    .A(_109_),
    .B(_024_),
    .Y(_032_)
  );
  NAND _181_ (
    .A(reset),
    .B(_032_),
    .Y(_033_)
  );
  NOR _182_ (
    .A(_031_),
    .B(_033_),
    .Y(_000_[2])
  );
  NOR _183_ (
    .A(data_out[3]),
    .B(_024_),
    .Y(_034_)
  );
  NAND _184_ (
    .A(_110_),
    .B(_024_),
    .Y(_035_)
  );
  NAND _185_ (
    .A(reset),
    .B(_035_),
    .Y(_036_)
  );
  NOR _186_ (
    .A(_034_),
    .B(_036_),
    .Y(_000_[3])
  );
  NOR _187_ (
    .A(data_out[4]),
    .B(_024_),
    .Y(_037_)
  );
  NAND _188_ (
    .A(_111_),
    .B(_024_),
    .Y(_038_)
  );
  NAND _189_ (
    .A(reset),
    .B(_038_),
    .Y(_039_)
  );
  NOR _190_ (
    .A(_037_),
    .B(_039_),
    .Y(_000_[4])
  );
  NOR _191_ (
    .A(data_out[5]),
    .B(_024_),
    .Y(_040_)
  );
  NAND _192_ (
    .A(_112_),
    .B(_024_),
    .Y(_041_)
  );
  NAND _193_ (
    .A(reset),
    .B(_041_),
    .Y(_042_)
  );
  NOR _194_ (
    .A(_040_),
    .B(_042_),
    .Y(_000_[5])
  );
  NOR _195_ (
    .A(data_out[6]),
    .B(_024_),
    .Y(_043_)
  );
  NAND _196_ (
    .A(_113_),
    .B(_024_),
    .Y(_044_)
  );
  NAND _197_ (
    .A(reset),
    .B(_044_),
    .Y(_045_)
  );
  NOR _198_ (
    .A(_043_),
    .B(_045_),
    .Y(_000_[6])
  );
  NOR _199_ (
    .A(data_out[7]),
    .B(_024_),
    .Y(_046_)
  );
  NAND _200_ (
    .A(_114_),
    .B(_024_),
    .Y(_047_)
  );
  NAND _201_ (
    .A(reset),
    .B(_047_),
    .Y(_048_)
  );
  NOR _202_ (
    .A(_046_),
    .B(_048_),
    .Y(_000_[7])
  );
  NAND _203_ (
    .A(selector[0]),
    .B(valid),
    .Y(_049_)
  );
  NOR _204_ (
    .A(selector[1]),
    .B(_049_),
    .Y(_050_)
  );
  NOR _205_ (
    .A(data_out[16]),
    .B(_050_),
    .Y(_051_)
  );
  NAND _206_ (
    .A(_107_),
    .B(_050_),
    .Y(_052_)
  );
  NAND _207_ (
    .A(reset),
    .B(_052_),
    .Y(_053_)
  );
  NOR _208_ (
    .A(_051_),
    .B(_053_),
    .Y(_000_[16])
  );
  NOR _209_ (
    .A(data_out[17]),
    .B(_050_),
    .Y(_054_)
  );
  NAND _210_ (
    .A(_108_),
    .B(_050_),
    .Y(_055_)
  );
  NAND _211_ (
    .A(reset),
    .B(_055_),
    .Y(_056_)
  );
  NOR _212_ (
    .A(_054_),
    .B(_056_),
    .Y(_000_[17])
  );
  NOR _213_ (
    .A(data_out[18]),
    .B(_050_),
    .Y(_057_)
  );
  NAND _214_ (
    .A(_109_),
    .B(_050_),
    .Y(_058_)
  );
  NAND _215_ (
    .A(reset),
    .B(_058_),
    .Y(_059_)
  );
  NOR _216_ (
    .A(_057_),
    .B(_059_),
    .Y(_000_[18])
  );
  NOR _217_ (
    .A(data_out[19]),
    .B(_050_),
    .Y(_060_)
  );
  NAND _218_ (
    .A(_110_),
    .B(_050_),
    .Y(_061_)
  );
  NAND _219_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NOR _220_ (
    .A(_060_),
    .B(_062_),
    .Y(_000_[19])
  );
  NOR _221_ (
    .A(data_out[20]),
    .B(_050_),
    .Y(_063_)
  );
  NAND _222_ (
    .A(_111_),
    .B(_050_),
    .Y(_064_)
  );
  NAND _223_ (
    .A(reset),
    .B(_064_),
    .Y(_065_)
  );
  NOR _224_ (
    .A(_063_),
    .B(_065_),
    .Y(_000_[20])
  );
  NOR _225_ (
    .A(data_out[21]),
    .B(_050_),
    .Y(_066_)
  );
  NAND _226_ (
    .A(_112_),
    .B(_050_),
    .Y(_067_)
  );
  NAND _227_ (
    .A(reset),
    .B(_067_),
    .Y(_068_)
  );
  NOR _228_ (
    .A(_066_),
    .B(_068_),
    .Y(_000_[21])
  );
  NOR _229_ (
    .A(data_out[22]),
    .B(_050_),
    .Y(_069_)
  );
  NAND _230_ (
    .A(_113_),
    .B(_050_),
    .Y(_070_)
  );
  NAND _231_ (
    .A(reset),
    .B(_070_),
    .Y(_071_)
  );
  NOR _232_ (
    .A(_069_),
    .B(_071_),
    .Y(_000_[22])
  );
  NOR _233_ (
    .A(data_out[23]),
    .B(_050_),
    .Y(_072_)
  );
  NAND _234_ (
    .A(_114_),
    .B(_050_),
    .Y(_073_)
  );
  NAND _235_ (
    .A(reset),
    .B(_073_),
    .Y(_074_)
  );
  NOR _236_ (
    .A(_072_),
    .B(_074_),
    .Y(_000_[23])
  );
  NOR _237_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_075_)
  );
  NOT _238_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _239_ (
    .A(selector[1]),
    .B(_116_),
    .Y(_077_)
  );
  NOR _240_ (
    .A(data_out[24]),
    .B(_077_),
    .Y(_078_)
  );
  NAND _241_ (
    .A(_107_),
    .B(_077_),
    .Y(_079_)
  );
  NAND _242_ (
    .A(reset),
    .B(_079_),
    .Y(_080_)
  );
  NOR _243_ (
    .A(_078_),
    .B(_080_),
    .Y(_000_[24])
  );
  NOR _244_ (
    .A(data_out[25]),
    .B(_077_),
    .Y(_081_)
  );
  NAND _245_ (
    .A(_108_),
    .B(_077_),
    .Y(_082_)
  );
  NAND _246_ (
    .A(reset),
    .B(_082_),
    .Y(_083_)
  );
  NOR _247_ (
    .A(_081_),
    .B(_083_),
    .Y(_000_[25])
  );
  NOR _248_ (
    .A(data_out[26]),
    .B(_077_),
    .Y(_084_)
  );
  NAND _249_ (
    .A(_109_),
    .B(_077_),
    .Y(_085_)
  );
  NAND _250_ (
    .A(reset),
    .B(_085_),
    .Y(_086_)
  );
  NOR _251_ (
    .A(_084_),
    .B(_086_),
    .Y(_000_[26])
  );
  NOR _252_ (
    .A(data_out[27]),
    .B(_077_),
    .Y(_087_)
  );
  NAND _253_ (
    .A(_110_),
    .B(_077_),
    .Y(_088_)
  );
  NAND _254_ (
    .A(reset),
    .B(_088_),
    .Y(_089_)
  );
  NOR _255_ (
    .A(_087_),
    .B(_089_),
    .Y(_000_[27])
  );
  NOR _256_ (
    .A(data_out[28]),
    .B(_077_),
    .Y(_090_)
  );
  NAND _257_ (
    .A(_111_),
    .B(_077_),
    .Y(_091_)
  );
  NAND _258_ (
    .A(reset),
    .B(_091_),
    .Y(_092_)
  );
  NOR _259_ (
    .A(_090_),
    .B(_092_),
    .Y(_000_[28])
  );
  NOR _260_ (
    .A(data_out[29]),
    .B(_077_),
    .Y(_093_)
  );
  NAND _261_ (
    .A(_112_),
    .B(_077_),
    .Y(_094_)
  );
  NAND _262_ (
    .A(reset),
    .B(_094_),
    .Y(_095_)
  );
  NOR _263_ (
    .A(_093_),
    .B(_095_),
    .Y(_000_[29])
  );
  NOR _264_ (
    .A(data_out[30]),
    .B(_077_),
    .Y(_096_)
  );
  NAND _265_ (
    .A(_113_),
    .B(_077_),
    .Y(_097_)
  );
  NAND _266_ (
    .A(reset),
    .B(_097_),
    .Y(_098_)
  );
  NOR _267_ (
    .A(_096_),
    .B(_098_),
    .Y(_000_[30])
  );
  NOR _268_ (
    .A(data_out[31]),
    .B(_077_),
    .Y(_099_)
  );
  NAND _269_ (
    .A(_114_),
    .B(_077_),
    .Y(_100_)
  );
  NAND _270_ (
    .A(reset),
    .B(_100_),
    .Y(_101_)
  );
  NOR _271_ (
    .A(_099_),
    .B(_101_),
    .Y(_000_[31])
  );
  NOR _272_ (
    .A(_023_),
    .B(_075_),
    .Y(_102_)
  );
  NAND _273_ (
    .A(_022_),
    .B(_076_),
    .Y(_103_)
  );
  NAND _274_ (
    .A(valid),
    .B(reset),
    .Y(_104_)
  );
  NOR _275_ (
    .A(_102_),
    .B(_104_),
    .Y(_002_)
  );
  NOR _276_ (
    .A(selector[0]),
    .B(_104_),
    .Y(_001_[0])
  );
  NOR _277_ (
    .A(_103_),
    .B(_104_),
    .Y(_001_[1])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _278_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _279_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _280_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _281_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _282_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _283_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _284_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _285_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _286_ (
    .C(clk_4f),
    .D(_000_[8]),
    .Q(data_out[8])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _287_ (
    .C(clk_4f),
    .D(_000_[9]),
    .Q(data_out[9])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _288_ (
    .C(clk_4f),
    .D(_000_[10]),
    .Q(data_out[10])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _289_ (
    .C(clk_4f),
    .D(_000_[11]),
    .Q(data_out[11])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _290_ (
    .C(clk_4f),
    .D(_000_[12]),
    .Q(data_out[12])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _291_ (
    .C(clk_4f),
    .D(_000_[13]),
    .Q(data_out[13])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _292_ (
    .C(clk_4f),
    .D(_000_[14]),
    .Q(data_out[14])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _293_ (
    .C(clk_4f),
    .D(_000_[15]),
    .Q(data_out[15])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _294_ (
    .C(clk_4f),
    .D(_000_[16]),
    .Q(data_out[16])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _295_ (
    .C(clk_4f),
    .D(_000_[17]),
    .Q(data_out[17])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _296_ (
    .C(clk_4f),
    .D(_000_[18]),
    .Q(data_out[18])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _297_ (
    .C(clk_4f),
    .D(_000_[19]),
    .Q(data_out[19])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _298_ (
    .C(clk_4f),
    .D(_000_[20]),
    .Q(data_out[20])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _299_ (
    .C(clk_4f),
    .D(_000_[21]),
    .Q(data_out[21])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _300_ (
    .C(clk_4f),
    .D(_000_[22]),
    .Q(data_out[22])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _301_ (
    .C(clk_4f),
    .D(_000_[23]),
    .Q(data_out[23])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _302_ (
    .C(clk_4f),
    .D(_000_[24]),
    .Q(data_out[24])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _303_ (
    .C(clk_4f),
    .D(_000_[25]),
    .Q(data_out[25])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _304_ (
    .C(clk_4f),
    .D(_000_[26]),
    .Q(data_out[26])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _305_ (
    .C(clk_4f),
    .D(_000_[27]),
    .Q(data_out[27])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _306_ (
    .C(clk_4f),
    .D(_000_[28]),
    .Q(data_out[28])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _307_ (
    .C(clk_4f),
    .D(_000_[29]),
    .Q(data_out[29])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _308_ (
    .C(clk_4f),
    .D(_000_[30]),
    .Q(data_out[30])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _309_ (
    .C(clk_4f),
    .D(_000_[31]),
    .Q(data_out[31])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _310_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_out)
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _311_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(selector[0])
  );
  (* src = "../demux_8_32_sintetizado/demux_8_32_sintetizado.v:10" *)
  DFF _312_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(selector[1])
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:1" *)
module mux_striping_sintetizado(clk_2f, lane_0, lane_1, valid_0, valid_1, reset, data_output, valid_out);
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  wire [31:0] _000_;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  wire _001_;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:2" *)
  input clk_2f;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:8" *)
  output [31:0] data_output;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:3" *)
  input [31:0] lane_0;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:4" *)
  input [31:0] lane_1;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:7" *)
  input reset;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:11" *)
  wire sel;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:5" *)
  input valid_0;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:6" *)
  input valid_1;
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:9" *)
  output valid_out;
  NOT _207_ (
    .A(sel),
    .Y(_003_)
  );
  NOT _208_ (
    .A(data_output[0]),
    .Y(_004_)
  );
  NOT _209_ (
    .A(valid_1),
    .Y(_005_)
  );
  NOT _210_ (
    .A(data_output[1]),
    .Y(_006_)
  );
  NOT _211_ (
    .A(data_output[2]),
    .Y(_007_)
  );
  NOT _212_ (
    .A(data_output[3]),
    .Y(_008_)
  );
  NOT _213_ (
    .A(data_output[4]),
    .Y(_009_)
  );
  NOT _214_ (
    .A(data_output[5]),
    .Y(_010_)
  );
  NOT _215_ (
    .A(data_output[6]),
    .Y(_011_)
  );
  NOT _216_ (
    .A(data_output[7]),
    .Y(_012_)
  );
  NOT _217_ (
    .A(data_output[8]),
    .Y(_013_)
  );
  NOT _218_ (
    .A(data_output[9]),
    .Y(_014_)
  );
  NOT _219_ (
    .A(data_output[10]),
    .Y(_015_)
  );
  NOT _220_ (
    .A(data_output[11]),
    .Y(_016_)
  );
  NOT _221_ (
    .A(data_output[12]),
    .Y(_017_)
  );
  NOT _222_ (
    .A(data_output[13]),
    .Y(_018_)
  );
  NOT _223_ (
    .A(data_output[14]),
    .Y(_019_)
  );
  NOT _224_ (
    .A(data_output[15]),
    .Y(_020_)
  );
  NOT _225_ (
    .A(data_output[16]),
    .Y(_021_)
  );
  NOT _226_ (
    .A(data_output[17]),
    .Y(_022_)
  );
  NOT _227_ (
    .A(data_output[18]),
    .Y(_023_)
  );
  NOT _228_ (
    .A(data_output[19]),
    .Y(_024_)
  );
  NOT _229_ (
    .A(data_output[20]),
    .Y(_025_)
  );
  NOT _230_ (
    .A(data_output[21]),
    .Y(_026_)
  );
  NOT _231_ (
    .A(data_output[22]),
    .Y(_027_)
  );
  NOT _232_ (
    .A(data_output[23]),
    .Y(_028_)
  );
  NOT _233_ (
    .A(data_output[24]),
    .Y(_029_)
  );
  NOT _234_ (
    .A(data_output[25]),
    .Y(_030_)
  );
  NOT _235_ (
    .A(data_output[26]),
    .Y(_031_)
  );
  NOT _236_ (
    .A(data_output[27]),
    .Y(_032_)
  );
  NOT _237_ (
    .A(data_output[28]),
    .Y(_033_)
  );
  NOT _238_ (
    .A(data_output[29]),
    .Y(_034_)
  );
  NOT _239_ (
    .A(data_output[30]),
    .Y(_035_)
  );
  NOT _240_ (
    .A(data_output[31]),
    .Y(_036_)
  );
  NOT _241_ (
    .A(valid_0),
    .Y(_037_)
  );
  NOT _242_ (
    .A(reset),
    .Y(_038_)
  );
  NOR _243_ (
    .A(_003_),
    .B(_005_),
    .Y(_039_)
  );
  NAND _244_ (
    .A(sel),
    .B(valid_1),
    .Y(_040_)
  );
  NOR _245_ (
    .A(sel),
    .B(_037_),
    .Y(_041_)
  );
  NAND _246_ (
    .A(_003_),
    .B(valid_0),
    .Y(_042_)
  );
  NAND _247_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _248_ (
    .A(_004_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _249_ (
    .A(lane_1[0]),
    .B(_039_),
    .Y(_045_)
  );
  NAND _250_ (
    .A(lane_0[0]),
    .B(_041_),
    .Y(_046_)
  );
  NAND _251_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _252_ (
    .A(_044_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _253_ (
    .A(_038_),
    .B(_048_),
    .Y(_000_[0])
  );
  NOR _254_ (
    .A(_006_),
    .B(_043_),
    .Y(_049_)
  );
  NAND _255_ (
    .A(lane_1[1]),
    .B(_039_),
    .Y(_050_)
  );
  NAND _256_ (
    .A(lane_0[1]),
    .B(_041_),
    .Y(_051_)
  );
  NAND _257_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _258_ (
    .A(_049_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _259_ (
    .A(_038_),
    .B(_053_),
    .Y(_000_[1])
  );
  NOR _260_ (
    .A(_007_),
    .B(_043_),
    .Y(_054_)
  );
  NAND _261_ (
    .A(lane_1[2]),
    .B(_039_),
    .Y(_055_)
  );
  NAND _262_ (
    .A(lane_0[2]),
    .B(_041_),
    .Y(_056_)
  );
  NAND _263_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _264_ (
    .A(_054_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _265_ (
    .A(_038_),
    .B(_058_),
    .Y(_000_[2])
  );
  NOR _266_ (
    .A(_008_),
    .B(_043_),
    .Y(_059_)
  );
  NAND _267_ (
    .A(lane_1[3]),
    .B(_039_),
    .Y(_060_)
  );
  NAND _268_ (
    .A(lane_0[3]),
    .B(_041_),
    .Y(_061_)
  );
  NAND _269_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _270_ (
    .A(_059_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _271_ (
    .A(_038_),
    .B(_063_),
    .Y(_000_[3])
  );
  NOR _272_ (
    .A(_009_),
    .B(_043_),
    .Y(_064_)
  );
  NAND _273_ (
    .A(lane_1[4]),
    .B(_039_),
    .Y(_065_)
  );
  NAND _274_ (
    .A(lane_0[4]),
    .B(_041_),
    .Y(_066_)
  );
  NAND _275_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _276_ (
    .A(_064_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _277_ (
    .A(_038_),
    .B(_068_),
    .Y(_000_[4])
  );
  NOR _278_ (
    .A(_010_),
    .B(_043_),
    .Y(_069_)
  );
  NAND _279_ (
    .A(lane_1[5]),
    .B(_039_),
    .Y(_070_)
  );
  NAND _280_ (
    .A(lane_0[5]),
    .B(_041_),
    .Y(_071_)
  );
  NAND _281_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _282_ (
    .A(_069_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _283_ (
    .A(_038_),
    .B(_073_),
    .Y(_000_[5])
  );
  NOR _284_ (
    .A(_011_),
    .B(_043_),
    .Y(_074_)
  );
  NAND _285_ (
    .A(lane_1[6]),
    .B(_039_),
    .Y(_075_)
  );
  NAND _286_ (
    .A(lane_0[6]),
    .B(_041_),
    .Y(_076_)
  );
  NAND _287_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _288_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _289_ (
    .A(_038_),
    .B(_078_),
    .Y(_000_[6])
  );
  NOR _290_ (
    .A(_012_),
    .B(_043_),
    .Y(_079_)
  );
  NAND _291_ (
    .A(lane_1[7]),
    .B(_039_),
    .Y(_080_)
  );
  NAND _292_ (
    .A(lane_0[7]),
    .B(_041_),
    .Y(_081_)
  );
  NAND _293_ (
    .A(_080_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _294_ (
    .A(_079_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _295_ (
    .A(_038_),
    .B(_083_),
    .Y(_000_[7])
  );
  NOR _296_ (
    .A(_013_),
    .B(_043_),
    .Y(_084_)
  );
  NAND _297_ (
    .A(lane_1[8]),
    .B(_039_),
    .Y(_085_)
  );
  NAND _298_ (
    .A(lane_0[8]),
    .B(_041_),
    .Y(_086_)
  );
  NAND _299_ (
    .A(_085_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _300_ (
    .A(_084_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _301_ (
    .A(_038_),
    .B(_088_),
    .Y(_000_[8])
  );
  NOR _302_ (
    .A(_014_),
    .B(_043_),
    .Y(_089_)
  );
  NAND _303_ (
    .A(lane_1[9]),
    .B(_039_),
    .Y(_090_)
  );
  NAND _304_ (
    .A(lane_0[9]),
    .B(_041_),
    .Y(_091_)
  );
  NAND _305_ (
    .A(_090_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _306_ (
    .A(_089_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _307_ (
    .A(_038_),
    .B(_093_),
    .Y(_000_[9])
  );
  NOR _308_ (
    .A(_015_),
    .B(_043_),
    .Y(_094_)
  );
  NAND _309_ (
    .A(lane_1[10]),
    .B(_039_),
    .Y(_095_)
  );
  NAND _310_ (
    .A(lane_0[10]),
    .B(_041_),
    .Y(_096_)
  );
  NAND _311_ (
    .A(_095_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _312_ (
    .A(_094_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _313_ (
    .A(_038_),
    .B(_098_),
    .Y(_000_[10])
  );
  NOR _314_ (
    .A(_016_),
    .B(_043_),
    .Y(_099_)
  );
  NAND _315_ (
    .A(lane_1[11]),
    .B(_039_),
    .Y(_100_)
  );
  NAND _316_ (
    .A(lane_0[11]),
    .B(_041_),
    .Y(_101_)
  );
  NAND _317_ (
    .A(_100_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _318_ (
    .A(_099_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _319_ (
    .A(_038_),
    .B(_103_),
    .Y(_000_[11])
  );
  NOR _320_ (
    .A(_017_),
    .B(_043_),
    .Y(_104_)
  );
  NAND _321_ (
    .A(lane_1[12]),
    .B(_039_),
    .Y(_105_)
  );
  NAND _322_ (
    .A(lane_0[12]),
    .B(_041_),
    .Y(_106_)
  );
  NAND _323_ (
    .A(_105_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _324_ (
    .A(_104_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _325_ (
    .A(_038_),
    .B(_108_),
    .Y(_000_[12])
  );
  NOR _326_ (
    .A(_018_),
    .B(_043_),
    .Y(_109_)
  );
  NAND _327_ (
    .A(lane_1[13]),
    .B(_039_),
    .Y(_110_)
  );
  NAND _328_ (
    .A(lane_0[13]),
    .B(_041_),
    .Y(_111_)
  );
  NAND _329_ (
    .A(_110_),
    .B(_111_),
    .Y(_112_)
  );
  NOR _330_ (
    .A(_109_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _331_ (
    .A(_038_),
    .B(_113_),
    .Y(_000_[13])
  );
  NOR _332_ (
    .A(_019_),
    .B(_043_),
    .Y(_114_)
  );
  NAND _333_ (
    .A(lane_1[14]),
    .B(_039_),
    .Y(_115_)
  );
  NAND _334_ (
    .A(lane_0[14]),
    .B(_041_),
    .Y(_116_)
  );
  NAND _335_ (
    .A(_115_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _336_ (
    .A(_114_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _337_ (
    .A(_038_),
    .B(_118_),
    .Y(_000_[14])
  );
  NOR _338_ (
    .A(_020_),
    .B(_043_),
    .Y(_119_)
  );
  NAND _339_ (
    .A(lane_1[15]),
    .B(_039_),
    .Y(_120_)
  );
  NAND _340_ (
    .A(lane_0[15]),
    .B(_041_),
    .Y(_121_)
  );
  NAND _341_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  NOR _342_ (
    .A(_119_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _343_ (
    .A(_038_),
    .B(_123_),
    .Y(_000_[15])
  );
  NOR _344_ (
    .A(_021_),
    .B(_043_),
    .Y(_124_)
  );
  NAND _345_ (
    .A(lane_1[16]),
    .B(_039_),
    .Y(_125_)
  );
  NAND _346_ (
    .A(lane_0[16]),
    .B(_041_),
    .Y(_126_)
  );
  NAND _347_ (
    .A(_125_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _348_ (
    .A(_124_),
    .B(_127_),
    .Y(_128_)
  );
  NOR _349_ (
    .A(_038_),
    .B(_128_),
    .Y(_000_[16])
  );
  NOR _350_ (
    .A(_022_),
    .B(_043_),
    .Y(_129_)
  );
  NAND _351_ (
    .A(lane_1[17]),
    .B(_039_),
    .Y(_130_)
  );
  NAND _352_ (
    .A(lane_0[17]),
    .B(_041_),
    .Y(_131_)
  );
  NAND _353_ (
    .A(_130_),
    .B(_131_),
    .Y(_132_)
  );
  NOR _354_ (
    .A(_129_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _355_ (
    .A(_038_),
    .B(_133_),
    .Y(_000_[17])
  );
  NOR _356_ (
    .A(_023_),
    .B(_043_),
    .Y(_134_)
  );
  NAND _357_ (
    .A(lane_1[18]),
    .B(_039_),
    .Y(_135_)
  );
  NAND _358_ (
    .A(lane_0[18]),
    .B(_041_),
    .Y(_136_)
  );
  NAND _359_ (
    .A(_135_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _360_ (
    .A(_134_),
    .B(_137_),
    .Y(_138_)
  );
  NOR _361_ (
    .A(_038_),
    .B(_138_),
    .Y(_000_[18])
  );
  NOR _362_ (
    .A(_024_),
    .B(_043_),
    .Y(_139_)
  );
  NAND _363_ (
    .A(lane_1[19]),
    .B(_039_),
    .Y(_140_)
  );
  NAND _364_ (
    .A(lane_0[19]),
    .B(_041_),
    .Y(_141_)
  );
  NAND _365_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _366_ (
    .A(_139_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _367_ (
    .A(_038_),
    .B(_143_),
    .Y(_000_[19])
  );
  NOR _368_ (
    .A(_025_),
    .B(_043_),
    .Y(_144_)
  );
  NAND _369_ (
    .A(lane_1[20]),
    .B(_039_),
    .Y(_145_)
  );
  NAND _370_ (
    .A(lane_0[20]),
    .B(_041_),
    .Y(_146_)
  );
  NAND _371_ (
    .A(_145_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _372_ (
    .A(_144_),
    .B(_147_),
    .Y(_148_)
  );
  NOR _373_ (
    .A(_038_),
    .B(_148_),
    .Y(_000_[20])
  );
  NOR _374_ (
    .A(_026_),
    .B(_043_),
    .Y(_149_)
  );
  NAND _375_ (
    .A(lane_1[21]),
    .B(_039_),
    .Y(_150_)
  );
  NAND _376_ (
    .A(lane_0[21]),
    .B(_041_),
    .Y(_151_)
  );
  NAND _377_ (
    .A(_150_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _378_ (
    .A(_149_),
    .B(_152_),
    .Y(_153_)
  );
  NOR _379_ (
    .A(_038_),
    .B(_153_),
    .Y(_000_[21])
  );
  NOR _380_ (
    .A(_027_),
    .B(_043_),
    .Y(_154_)
  );
  NAND _381_ (
    .A(lane_1[22]),
    .B(_039_),
    .Y(_155_)
  );
  NAND _382_ (
    .A(lane_0[22]),
    .B(_041_),
    .Y(_156_)
  );
  NAND _383_ (
    .A(_155_),
    .B(_156_),
    .Y(_157_)
  );
  NOR _384_ (
    .A(_154_),
    .B(_157_),
    .Y(_158_)
  );
  NOR _385_ (
    .A(_038_),
    .B(_158_),
    .Y(_000_[22])
  );
  NOR _386_ (
    .A(_028_),
    .B(_043_),
    .Y(_159_)
  );
  NAND _387_ (
    .A(lane_1[23]),
    .B(_039_),
    .Y(_160_)
  );
  NAND _388_ (
    .A(lane_0[23]),
    .B(_041_),
    .Y(_161_)
  );
  NAND _389_ (
    .A(_160_),
    .B(_161_),
    .Y(_162_)
  );
  NOR _390_ (
    .A(_159_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _391_ (
    .A(_038_),
    .B(_163_),
    .Y(_000_[23])
  );
  NOR _392_ (
    .A(_029_),
    .B(_043_),
    .Y(_164_)
  );
  NAND _393_ (
    .A(lane_1[24]),
    .B(_039_),
    .Y(_165_)
  );
  NAND _394_ (
    .A(lane_0[24]),
    .B(_041_),
    .Y(_166_)
  );
  NAND _395_ (
    .A(_165_),
    .B(_166_),
    .Y(_167_)
  );
  NOR _396_ (
    .A(_164_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _397_ (
    .A(_038_),
    .B(_168_),
    .Y(_000_[24])
  );
  NOR _398_ (
    .A(_030_),
    .B(_043_),
    .Y(_169_)
  );
  NAND _399_ (
    .A(lane_1[25]),
    .B(_039_),
    .Y(_170_)
  );
  NAND _400_ (
    .A(lane_0[25]),
    .B(_041_),
    .Y(_171_)
  );
  NAND _401_ (
    .A(_170_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _402_ (
    .A(_169_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _403_ (
    .A(_038_),
    .B(_173_),
    .Y(_000_[25])
  );
  NOR _404_ (
    .A(_031_),
    .B(_043_),
    .Y(_174_)
  );
  NAND _405_ (
    .A(lane_1[26]),
    .B(_039_),
    .Y(_175_)
  );
  NAND _406_ (
    .A(lane_0[26]),
    .B(_041_),
    .Y(_176_)
  );
  NAND _407_ (
    .A(_175_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _408_ (
    .A(_174_),
    .B(_177_),
    .Y(_178_)
  );
  NOR _409_ (
    .A(_038_),
    .B(_178_),
    .Y(_000_[26])
  );
  NOR _410_ (
    .A(_032_),
    .B(_043_),
    .Y(_179_)
  );
  NAND _411_ (
    .A(lane_1[27]),
    .B(_039_),
    .Y(_180_)
  );
  NAND _412_ (
    .A(lane_0[27]),
    .B(_041_),
    .Y(_181_)
  );
  NAND _413_ (
    .A(_180_),
    .B(_181_),
    .Y(_182_)
  );
  NOR _414_ (
    .A(_179_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _415_ (
    .A(_038_),
    .B(_183_),
    .Y(_000_[27])
  );
  NOR _416_ (
    .A(_033_),
    .B(_043_),
    .Y(_184_)
  );
  NAND _417_ (
    .A(lane_1[28]),
    .B(_039_),
    .Y(_185_)
  );
  NAND _418_ (
    .A(lane_0[28]),
    .B(_041_),
    .Y(_186_)
  );
  NAND _419_ (
    .A(_185_),
    .B(_186_),
    .Y(_187_)
  );
  NOR _420_ (
    .A(_184_),
    .B(_187_),
    .Y(_188_)
  );
  NOR _421_ (
    .A(_038_),
    .B(_188_),
    .Y(_000_[28])
  );
  NOR _422_ (
    .A(_034_),
    .B(_043_),
    .Y(_189_)
  );
  NAND _423_ (
    .A(lane_1[29]),
    .B(_039_),
    .Y(_190_)
  );
  NAND _424_ (
    .A(lane_0[29]),
    .B(_041_),
    .Y(_191_)
  );
  NAND _425_ (
    .A(_190_),
    .B(_191_),
    .Y(_192_)
  );
  NOR _426_ (
    .A(_189_),
    .B(_192_),
    .Y(_193_)
  );
  NOR _427_ (
    .A(_038_),
    .B(_193_),
    .Y(_000_[29])
  );
  NOR _428_ (
    .A(_035_),
    .B(_043_),
    .Y(_194_)
  );
  NAND _429_ (
    .A(lane_1[30]),
    .B(_039_),
    .Y(_195_)
  );
  NAND _430_ (
    .A(lane_0[30]),
    .B(_041_),
    .Y(_196_)
  );
  NAND _431_ (
    .A(_195_),
    .B(_196_),
    .Y(_197_)
  );
  NOR _432_ (
    .A(_194_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _433_ (
    .A(_038_),
    .B(_198_),
    .Y(_000_[30])
  );
  NOR _434_ (
    .A(_036_),
    .B(_043_),
    .Y(_199_)
  );
  NAND _435_ (
    .A(lane_1[31]),
    .B(_039_),
    .Y(_200_)
  );
  NAND _436_ (
    .A(lane_0[31]),
    .B(_041_),
    .Y(_201_)
  );
  NAND _437_ (
    .A(_200_),
    .B(_201_),
    .Y(_202_)
  );
  NOR _438_ (
    .A(_199_),
    .B(_202_),
    .Y(_203_)
  );
  NOR _439_ (
    .A(_038_),
    .B(_203_),
    .Y(_000_[31])
  );
  NOR _440_ (
    .A(sel),
    .B(valid_0),
    .Y(_204_)
  );
  NAND _441_ (
    .A(reset),
    .B(_040_),
    .Y(_205_)
  );
  NOR _442_ (
    .A(_204_),
    .B(_205_),
    .Y(_001_)
  );
  NAND _443_ (
    .A(reset),
    .B(_043_),
    .Y(_206_)
  );
  NOT _444_ (
    .A(_206_),
    .Y(_002_)
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _445_ (
    .C(clk_2f),
    .D(_002_),
    .Q(valid_out)
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _446_ (
    .C(clk_2f),
    .D(_001_),
    .Q(sel)
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _447_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_output[0])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _448_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_output[1])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _449_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_output[2])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _450_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_output[3])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _451_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_output[4])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _452_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_output[5])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _453_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_output[6])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _454_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_output[7])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _455_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(data_output[8])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _456_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(data_output[9])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _457_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(data_output[10])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _458_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(data_output[11])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _459_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(data_output[12])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _460_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(data_output[13])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _461_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(data_output[14])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _462_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(data_output[15])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _463_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(data_output[16])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _464_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(data_output[17])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _465_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(data_output[18])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _466_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(data_output[19])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _467_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(data_output[20])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _468_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(data_output[21])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _469_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(data_output[22])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _470_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(data_output[23])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _471_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(data_output[24])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _472_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(data_output[25])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _473_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(data_output[26])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _474_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(data_output[27])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _475_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(data_output[28])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _476_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(data_output[29])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _477_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(data_output[30])
  );
  (* src = "../mux_striping_sintetizado/mux_striping_sintetizado.v:13" *)
  DFF _478_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(data_output[31])
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "phy_RX_sintetizado.v:6" *)
module phy_RX_sintetizado(serial_data_0, serial_data_1, reset, clk_2f, clk_4f, clk_32f, data_final_sintetizado, valid_final_sintetizado);
  (* src = "phy_RX_sintetizado.v:15" *)
  (* unused_bits = "0" *)
  wire active_0;
  (* src = "phy_RX_sintetizado.v:15" *)
  (* unused_bits = "0" *)
  wire active_1;
  (* src = "phy_RX_sintetizado.v:9" *)
  input clk_2f;
  (* src = "phy_RX_sintetizado.v:11" *)
  input clk_32f;
  (* src = "phy_RX_sintetizado.v:10" *)
  input clk_4f;
  (* src = "phy_RX_sintetizado.v:12" *)
  output [31:0] data_final_sintetizado;
  (* src = "phy_RX_sintetizado.v:21" *)
  wire [7:0] data_out_sp_0;
  (* src = "phy_RX_sintetizado.v:21" *)
  wire [7:0] data_out_sp_1;
  (* src = "phy_RX_sintetizado.v:25" *)
  wire [31:0] demux_out_0;
  (* src = "phy_RX_sintetizado.v:25" *)
  wire [31:0] demux_out_1;
  (* src = "phy_RX_sintetizado.v:8" *)
  input reset;
  (* src = "phy_RX_sintetizado.v:6" *)
  input serial_data_0;
  (* src = "phy_RX_sintetizado.v:7" *)
  input serial_data_1;
  (* src = "phy_RX_sintetizado.v:23" *)
  wire valid_demux_0;
  (* src = "phy_RX_sintetizado.v:23" *)
  wire valid_demux_1;
  (* src = "phy_RX_sintetizado.v:13" *)
  output valid_final_sintetizado;
  (* src = "phy_RX_sintetizado.v:23" *)
  wire valid_sp_0;
  (* src = "phy_RX_sintetizado.v:23" *)
  wire valid_sp_1;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_RX_sintetizado.v:49" *)
  demux_8_32_sintetizado demux_final_0 (
    .clk_4f(clk_4f),
    .data_in(data_out_sp_0),
    .data_out(demux_out_0),
    .reset(reset),
    .valid(valid_sp_0),
    .valid_out(valid_demux_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_RX_sintetizado.v:59" *)
  demux_8_32_sintetizado demux_final_1 (
    .clk_4f(clk_4f),
    .data_in(data_out_sp_1),
    .data_out(demux_out_1),
    .reset(reset),
    .valid(valid_sp_1),
    .valid_out(valid_demux_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_RX_sintetizado.v:69" *)
  mux_striping_sintetizado mux_stp (
    .clk_2f(clk_2f),
    .data_output(data_final_sintetizado),
    .lane_0(demux_out_0),
    .lane_1(demux_out_1),
    .reset(reset),
    .valid_0(valid_demux_0),
    .valid_1(valid_demux_1),
    .valid_out(valid_final_sintetizado)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_RX_sintetizado.v:27" *)
  serial_paralelo_sintetizado sp0 (
    .active(active_0),
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(serial_data_0),
    .data_out(data_out_sp_0),
    .reset(reset),
    .valid_out(valid_sp_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_RX_sintetizado.v:38" *)
  serial_paralelo_sintetizado sp1 (
    .active(active_1),
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(serial_data_1),
    .data_out(data_out_sp_1),
    .reset(reset),
    .valid_out(valid_sp_1)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "prueba.v:1" *)
module serial_paralelo_sintetizado(reset, clk_4f, clk_32f, data_in, active, valid_out, data_out);
  (* src = "prueba.v:15" *)
  wire [31:0] _0000_;
  (* src = "prueba.v:15" *)
  wire _0001_;
  (* src = "prueba.v:15" *)
  wire [7:0] _0002_;
  (* src = "prueba.v:15" *)
  wire [31:0] _0003_;
  (* src = "prueba.v:15" *)
  wire [7:0] _0004_;
  (* src = "prueba.v:15" *)
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  (* src = "prueba.v:11" *)
  wire [31:0] BC_counter;
  (* src = "prueba.v:6" *)
  output active;
  (* src = "prueba.v:12" *)
  wire [7:0] buffer;
  (* src = "prueba.v:4" *)
  input clk_32f;
  (* src = "prueba.v:3" *)
  input clk_4f;
  (* src = "prueba.v:13" *)
  wire [31:0] counter;
  (* src = "prueba.v:5" *)
  input data_in;
  (* src = "prueba.v:8" *)
  output [7:0] data_out;
  (* src = "prueba.v:2" *)
  input reset;
  (* src = "prueba.v:7" *)
  output valid_out;
  NOT _0483_ (
    .A(BC_counter[3]),
    .Y(_0006_)
  );
  NOT _0484_ (
    .A(BC_counter[4]),
    .Y(_0007_)
  );
  NOT _0485_ (
    .A(BC_counter[6]),
    .Y(_0008_)
  );
  NOT _0486_ (
    .A(BC_counter[7]),
    .Y(_0009_)
  );
  NOT _0487_ (
    .A(BC_counter[9]),
    .Y(_0010_)
  );
  NOT _0488_ (
    .A(BC_counter[10]),
    .Y(_0011_)
  );
  NOT _0489_ (
    .A(BC_counter[11]),
    .Y(_0012_)
  );
  NOT _0490_ (
    .A(BC_counter[13]),
    .Y(_0013_)
  );
  NOT _0491_ (
    .A(BC_counter[15]),
    .Y(_0014_)
  );
  NOT _0492_ (
    .A(BC_counter[16]),
    .Y(_0015_)
  );
  NOT _0493_ (
    .A(BC_counter[18]),
    .Y(_0016_)
  );
  NOT _0494_ (
    .A(BC_counter[20]),
    .Y(_0017_)
  );
  NOT _0495_ (
    .A(BC_counter[21]),
    .Y(_0018_)
  );
  NOT _0496_ (
    .A(BC_counter[22]),
    .Y(_0019_)
  );
  NOT _0497_ (
    .A(BC_counter[23]),
    .Y(_0020_)
  );
  NOT _0498_ (
    .A(BC_counter[24]),
    .Y(_0021_)
  );
  NOT _0499_ (
    .A(BC_counter[26]),
    .Y(_0022_)
  );
  NOT _0500_ (
    .A(BC_counter[27]),
    .Y(_0023_)
  );
  NOT _0501_ (
    .A(BC_counter[28]),
    .Y(_0024_)
  );
  NOT _0502_ (
    .A(BC_counter[30]),
    .Y(_0025_)
  );
  NOT _0503_ (
    .A(buffer[0]),
    .Y(_0026_)
  );
  NOT _0504_ (
    .A(buffer[1]),
    .Y(_0027_)
  );
  NOT _0505_ (
    .A(buffer[6]),
    .Y(_0028_)
  );
  NOT _0506_ (
    .A(counter[4]),
    .Y(_0029_)
  );
  NOT _0507_ (
    .A(counter[5]),
    .Y(_0030_)
  );
  NOT _0508_ (
    .A(counter[6]),
    .Y(_0031_)
  );
  NOT _0509_ (
    .A(counter[7]),
    .Y(_0032_)
  );
  NOT _0510_ (
    .A(counter[8]),
    .Y(_0033_)
  );
  NOT _0511_ (
    .A(counter[9]),
    .Y(_0034_)
  );
  NOT _0512_ (
    .A(counter[10]),
    .Y(_0035_)
  );
  NOT _0513_ (
    .A(counter[11]),
    .Y(_0036_)
  );
  NOT _0514_ (
    .A(counter[12]),
    .Y(_0037_)
  );
  NOT _0515_ (
    .A(counter[13]),
    .Y(_0038_)
  );
  NOT _0516_ (
    .A(counter[14]),
    .Y(_0039_)
  );
  NOT _0517_ (
    .A(counter[15]),
    .Y(_0040_)
  );
  NOT _0518_ (
    .A(counter[16]),
    .Y(_0041_)
  );
  NOT _0519_ (
    .A(counter[17]),
    .Y(_0042_)
  );
  NOT _0520_ (
    .A(counter[18]),
    .Y(_0043_)
  );
  NOT _0521_ (
    .A(counter[19]),
    .Y(_0044_)
  );
  NOT _0522_ (
    .A(counter[20]),
    .Y(_0045_)
  );
  NOT _0523_ (
    .A(counter[21]),
    .Y(_0046_)
  );
  NOT _0524_ (
    .A(counter[22]),
    .Y(_0047_)
  );
  NOT _0525_ (
    .A(counter[23]),
    .Y(_0048_)
  );
  NOT _0526_ (
    .A(counter[24]),
    .Y(_0049_)
  );
  NOT _0527_ (
    .A(counter[25]),
    .Y(_0050_)
  );
  NOT _0528_ (
    .A(counter[26]),
    .Y(_0051_)
  );
  NOT _0529_ (
    .A(counter[27]),
    .Y(_0052_)
  );
  NOT _0530_ (
    .A(counter[28]),
    .Y(_0053_)
  );
  NOT _0531_ (
    .A(counter[29]),
    .Y(_0054_)
  );
  NOT _0532_ (
    .A(counter[31]),
    .Y(_0055_)
  );
  NOT _0533_ (
    .A(counter[0]),
    .Y(_0056_)
  );
  NOT _0534_ (
    .A(counter[1]),
    .Y(_0057_)
  );
  NOT _0535_ (
    .A(counter[2]),
    .Y(_0058_)
  );
  NOT _0536_ (
    .A(reset),
    .Y(_0059_)
  );
  NOT _0537_ (
    .A(BC_counter[1]),
    .Y(_0060_)
  );
  NOT _0538_ (
    .A(BC_counter[2]),
    .Y(_0061_)
  );
  NOT _0539_ (
    .A(buffer[2]),
    .Y(_0062_)
  );
  NOT _0540_ (
    .A(buffer[3]),
    .Y(_0063_)
  );
  NOT _0541_ (
    .A(buffer[4]),
    .Y(_0064_)
  );
  NOT _0542_ (
    .A(buffer[5]),
    .Y(_0065_)
  );
  NOT _0543_ (
    .A(data_out[0]),
    .Y(_0066_)
  );
  NOT _0544_ (
    .A(data_out[1]),
    .Y(_0067_)
  );
  NOT _0545_ (
    .A(data_out[6]),
    .Y(_0068_)
  );
  NOT _0546_ (
    .A(buffer[7]),
    .Y(_0069_)
  );
  NOR _0547_ (
    .A(counter[0]),
    .B(_0059_),
    .Y(_0003_[0])
  );
  NOR _0548_ (
    .A(_0056_),
    .B(_0057_),
    .Y(_0070_)
  );
  NAND _0549_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_0071_)
  );
  NOR _0550_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_0072_)
  );
  NAND _0551_ (
    .A(_0056_),
    .B(_0057_),
    .Y(_0073_)
  );
  NAND _0552_ (
    .A(reset),
    .B(_0073_),
    .Y(_0074_)
  );
  NOR _0553_ (
    .A(_0070_),
    .B(_0074_),
    .Y(_0003_[1])
  );
  NOR _0554_ (
    .A(_0058_),
    .B(_0071_),
    .Y(_0075_)
  );
  NOT _0555_ (
    .A(_0075_),
    .Y(_0076_)
  );
  NAND _0556_ (
    .A(_0058_),
    .B(_0071_),
    .Y(_0077_)
  );
  NAND _0557_ (
    .A(reset),
    .B(_0077_),
    .Y(_0078_)
  );
  NOR _0558_ (
    .A(_0075_),
    .B(_0078_),
    .Y(_0003_[2])
  );
  NOR _0559_ (
    .A(counter[28]),
    .B(counter[29]),
    .Y(_0079_)
  );
  NOR _0560_ (
    .A(counter[30]),
    .B(counter[31]),
    .Y(_0080_)
  );
  NAND _0561_ (
    .A(_0079_),
    .B(_0080_),
    .Y(_0081_)
  );
  NAND _0562_ (
    .A(_0049_),
    .B(_0050_),
    .Y(_0082_)
  );
  NAND _0563_ (
    .A(_0051_),
    .B(_0052_),
    .Y(_0083_)
  );
  NOR _0564_ (
    .A(_0082_),
    .B(_0083_),
    .Y(_0084_)
  );
  NAND _0565_ (
    .A(_0045_),
    .B(_0046_),
    .Y(_0085_)
  );
  NAND _0566_ (
    .A(_0047_),
    .B(_0048_),
    .Y(_0086_)
  );
  NOR _0567_ (
    .A(_0085_),
    .B(_0086_),
    .Y(_0087_)
  );
  NAND _0568_ (
    .A(_0084_),
    .B(_0087_),
    .Y(_0088_)
  );
  NOR _0569_ (
    .A(_0081_),
    .B(_0088_),
    .Y(_0089_)
  );
  NAND _0570_ (
    .A(_0033_),
    .B(_0034_),
    .Y(_0090_)
  );
  NAND _0571_ (
    .A(_0035_),
    .B(_0036_),
    .Y(_0091_)
  );
  NOR _0572_ (
    .A(_0090_),
    .B(_0091_),
    .Y(_0092_)
  );
  NAND _0573_ (
    .A(_0030_),
    .B(_0031_),
    .Y(_0093_)
  );
  NAND _0574_ (
    .A(_0029_),
    .B(_0032_),
    .Y(_0094_)
  );
  NOR _0575_ (
    .A(_0093_),
    .B(_0094_),
    .Y(_0095_)
  );
  NAND _0576_ (
    .A(_0092_),
    .B(_0095_),
    .Y(_0096_)
  );
  NOR _0577_ (
    .A(counter[18]),
    .B(counter[19]),
    .Y(_0097_)
  );
  NOR _0578_ (
    .A(counter[16]),
    .B(counter[17]),
    .Y(_0098_)
  );
  NAND _0579_ (
    .A(_0097_),
    .B(_0098_),
    .Y(_0099_)
  );
  NOR _0580_ (
    .A(counter[12]),
    .B(counter[13]),
    .Y(_0100_)
  );
  NOR _0581_ (
    .A(counter[14]),
    .B(counter[15]),
    .Y(_0101_)
  );
  NAND _0582_ (
    .A(_0100_),
    .B(_0101_),
    .Y(_0102_)
  );
  NOR _0583_ (
    .A(_0099_),
    .B(_0102_),
    .Y(_0103_)
  );
  NAND _0584_ (
    .A(_0089_),
    .B(_0103_),
    .Y(_0104_)
  );
  NOR _0585_ (
    .A(_0096_),
    .B(_0104_),
    .Y(_0105_)
  );
  NOR _0586_ (
    .A(_0076_),
    .B(_0105_),
    .Y(_0106_)
  );
  NOR _0587_ (
    .A(counter[3]),
    .B(_0106_),
    .Y(_0107_)
  );
  NAND _0588_ (
    .A(counter[3]),
    .B(_0075_),
    .Y(_0108_)
  );
  NOT _0589_ (
    .A(_0108_),
    .Y(_0109_)
  );
  NAND _0590_ (
    .A(reset),
    .B(_0108_),
    .Y(_0110_)
  );
  NOR _0591_ (
    .A(_0107_),
    .B(_0110_),
    .Y(_0003_[3])
  );
  NOR _0592_ (
    .A(_0029_),
    .B(_0108_),
    .Y(_0111_)
  );
  NAND _0593_ (
    .A(counter[4]),
    .B(_0109_),
    .Y(_0112_)
  );
  NAND _0594_ (
    .A(_0029_),
    .B(_0108_),
    .Y(_0113_)
  );
  NAND _0595_ (
    .A(reset),
    .B(_0113_),
    .Y(_0114_)
  );
  NOR _0596_ (
    .A(_0111_),
    .B(_0114_),
    .Y(_0003_[4])
  );
  NOR _0597_ (
    .A(_0030_),
    .B(_0112_),
    .Y(_0115_)
  );
  NAND _0598_ (
    .A(counter[5]),
    .B(_0111_),
    .Y(_0116_)
  );
  NAND _0599_ (
    .A(_0030_),
    .B(_0112_),
    .Y(_0117_)
  );
  NAND _0600_ (
    .A(reset),
    .B(_0117_),
    .Y(_0118_)
  );
  NOR _0601_ (
    .A(_0115_),
    .B(_0118_),
    .Y(_0003_[5])
  );
  NOR _0602_ (
    .A(_0031_),
    .B(_0116_),
    .Y(_0119_)
  );
  NAND _0603_ (
    .A(counter[6]),
    .B(_0115_),
    .Y(_0120_)
  );
  NAND _0604_ (
    .A(_0031_),
    .B(_0116_),
    .Y(_0121_)
  );
  NAND _0605_ (
    .A(reset),
    .B(_0121_),
    .Y(_0122_)
  );
  NOR _0606_ (
    .A(_0119_),
    .B(_0122_),
    .Y(_0003_[6])
  );
  NOR _0607_ (
    .A(_0032_),
    .B(_0120_),
    .Y(_0123_)
  );
  NAND _0608_ (
    .A(counter[7]),
    .B(_0119_),
    .Y(_0124_)
  );
  NAND _0609_ (
    .A(_0032_),
    .B(_0120_),
    .Y(_0125_)
  );
  NAND _0610_ (
    .A(reset),
    .B(_0125_),
    .Y(_0126_)
  );
  NOR _0611_ (
    .A(_0123_),
    .B(_0126_),
    .Y(_0003_[7])
  );
  NOR _0612_ (
    .A(_0033_),
    .B(_0124_),
    .Y(_0127_)
  );
  NAND _0613_ (
    .A(counter[8]),
    .B(_0123_),
    .Y(_0128_)
  );
  NAND _0614_ (
    .A(_0033_),
    .B(_0124_),
    .Y(_0129_)
  );
  NAND _0615_ (
    .A(reset),
    .B(_0129_),
    .Y(_0130_)
  );
  NOR _0616_ (
    .A(_0127_),
    .B(_0130_),
    .Y(_0003_[8])
  );
  NOR _0617_ (
    .A(_0034_),
    .B(_0128_),
    .Y(_0131_)
  );
  NAND _0618_ (
    .A(counter[9]),
    .B(_0127_),
    .Y(_0132_)
  );
  NAND _0619_ (
    .A(_0034_),
    .B(_0128_),
    .Y(_0133_)
  );
  NAND _0620_ (
    .A(reset),
    .B(_0133_),
    .Y(_0134_)
  );
  NOR _0621_ (
    .A(_0131_),
    .B(_0134_),
    .Y(_0003_[9])
  );
  NOR _0622_ (
    .A(_0035_),
    .B(_0132_),
    .Y(_0135_)
  );
  NAND _0623_ (
    .A(counter[10]),
    .B(_0131_),
    .Y(_0136_)
  );
  NAND _0624_ (
    .A(_0035_),
    .B(_0132_),
    .Y(_0137_)
  );
  NAND _0625_ (
    .A(reset),
    .B(_0137_),
    .Y(_0138_)
  );
  NOR _0626_ (
    .A(_0135_),
    .B(_0138_),
    .Y(_0003_[10])
  );
  NOR _0627_ (
    .A(_0036_),
    .B(_0136_),
    .Y(_0139_)
  );
  NAND _0628_ (
    .A(counter[11]),
    .B(_0135_),
    .Y(_0140_)
  );
  NAND _0629_ (
    .A(_0036_),
    .B(_0136_),
    .Y(_0141_)
  );
  NAND _0630_ (
    .A(reset),
    .B(_0141_),
    .Y(_0142_)
  );
  NOR _0631_ (
    .A(_0139_),
    .B(_0142_),
    .Y(_0003_[11])
  );
  NOR _0632_ (
    .A(_0037_),
    .B(_0140_),
    .Y(_0143_)
  );
  NAND _0633_ (
    .A(counter[12]),
    .B(_0139_),
    .Y(_0144_)
  );
  NAND _0634_ (
    .A(_0037_),
    .B(_0140_),
    .Y(_0145_)
  );
  NAND _0635_ (
    .A(reset),
    .B(_0145_),
    .Y(_0146_)
  );
  NOR _0636_ (
    .A(_0143_),
    .B(_0146_),
    .Y(_0003_[12])
  );
  NOR _0637_ (
    .A(_0038_),
    .B(_0144_),
    .Y(_0147_)
  );
  NAND _0638_ (
    .A(counter[13]),
    .B(_0143_),
    .Y(_0148_)
  );
  NAND _0639_ (
    .A(_0038_),
    .B(_0144_),
    .Y(_0149_)
  );
  NAND _0640_ (
    .A(reset),
    .B(_0149_),
    .Y(_0150_)
  );
  NOR _0641_ (
    .A(_0147_),
    .B(_0150_),
    .Y(_0003_[13])
  );
  NOR _0642_ (
    .A(_0039_),
    .B(_0148_),
    .Y(_0151_)
  );
  NAND _0643_ (
    .A(counter[14]),
    .B(_0147_),
    .Y(_0152_)
  );
  NAND _0644_ (
    .A(_0039_),
    .B(_0148_),
    .Y(_0153_)
  );
  NAND _0645_ (
    .A(reset),
    .B(_0153_),
    .Y(_0154_)
  );
  NOR _0646_ (
    .A(_0151_),
    .B(_0154_),
    .Y(_0003_[14])
  );
  NOR _0647_ (
    .A(_0040_),
    .B(_0152_),
    .Y(_0155_)
  );
  NAND _0648_ (
    .A(counter[15]),
    .B(_0151_),
    .Y(_0156_)
  );
  NAND _0649_ (
    .A(_0040_),
    .B(_0152_),
    .Y(_0157_)
  );
  NAND _0650_ (
    .A(reset),
    .B(_0157_),
    .Y(_0158_)
  );
  NOR _0651_ (
    .A(_0155_),
    .B(_0158_),
    .Y(_0003_[15])
  );
  NOR _0652_ (
    .A(_0041_),
    .B(_0156_),
    .Y(_0159_)
  );
  NAND _0653_ (
    .A(counter[16]),
    .B(_0155_),
    .Y(_0160_)
  );
  NAND _0654_ (
    .A(_0041_),
    .B(_0156_),
    .Y(_0161_)
  );
  NAND _0655_ (
    .A(reset),
    .B(_0161_),
    .Y(_0162_)
  );
  NOR _0656_ (
    .A(_0159_),
    .B(_0162_),
    .Y(_0003_[16])
  );
  NOR _0657_ (
    .A(_0042_),
    .B(_0160_),
    .Y(_0163_)
  );
  NAND _0658_ (
    .A(counter[17]),
    .B(_0159_),
    .Y(_0164_)
  );
  NAND _0659_ (
    .A(_0042_),
    .B(_0160_),
    .Y(_0165_)
  );
  NAND _0660_ (
    .A(reset),
    .B(_0165_),
    .Y(_0166_)
  );
  NOR _0661_ (
    .A(_0163_),
    .B(_0166_),
    .Y(_0003_[17])
  );
  NOR _0662_ (
    .A(_0043_),
    .B(_0164_),
    .Y(_0167_)
  );
  NAND _0663_ (
    .A(counter[18]),
    .B(_0163_),
    .Y(_0168_)
  );
  NAND _0664_ (
    .A(_0043_),
    .B(_0164_),
    .Y(_0169_)
  );
  NAND _0665_ (
    .A(reset),
    .B(_0169_),
    .Y(_0170_)
  );
  NOR _0666_ (
    .A(_0167_),
    .B(_0170_),
    .Y(_0003_[18])
  );
  NOR _0667_ (
    .A(_0044_),
    .B(_0168_),
    .Y(_0171_)
  );
  NAND _0668_ (
    .A(counter[19]),
    .B(_0167_),
    .Y(_0172_)
  );
  NAND _0669_ (
    .A(_0044_),
    .B(_0168_),
    .Y(_0173_)
  );
  NAND _0670_ (
    .A(reset),
    .B(_0173_),
    .Y(_0174_)
  );
  NOR _0671_ (
    .A(_0171_),
    .B(_0174_),
    .Y(_0003_[19])
  );
  NOR _0672_ (
    .A(_0045_),
    .B(_0172_),
    .Y(_0175_)
  );
  NAND _0673_ (
    .A(counter[20]),
    .B(_0171_),
    .Y(_0176_)
  );
  NAND _0674_ (
    .A(_0045_),
    .B(_0172_),
    .Y(_0177_)
  );
  NAND _0675_ (
    .A(reset),
    .B(_0177_),
    .Y(_0178_)
  );
  NOR _0676_ (
    .A(_0175_),
    .B(_0178_),
    .Y(_0003_[20])
  );
  NOR _0677_ (
    .A(_0046_),
    .B(_0176_),
    .Y(_0179_)
  );
  NAND _0678_ (
    .A(counter[21]),
    .B(_0175_),
    .Y(_0180_)
  );
  NAND _0679_ (
    .A(_0046_),
    .B(_0176_),
    .Y(_0181_)
  );
  NAND _0680_ (
    .A(reset),
    .B(_0181_),
    .Y(_0182_)
  );
  NOR _0681_ (
    .A(_0179_),
    .B(_0182_),
    .Y(_0003_[21])
  );
  NOR _0682_ (
    .A(_0047_),
    .B(_0180_),
    .Y(_0183_)
  );
  NAND _0683_ (
    .A(counter[22]),
    .B(_0179_),
    .Y(_0184_)
  );
  NAND _0684_ (
    .A(_0047_),
    .B(_0180_),
    .Y(_0185_)
  );
  NAND _0685_ (
    .A(reset),
    .B(_0185_),
    .Y(_0186_)
  );
  NOR _0686_ (
    .A(_0183_),
    .B(_0186_),
    .Y(_0003_[22])
  );
  NOR _0687_ (
    .A(_0048_),
    .B(_0184_),
    .Y(_0187_)
  );
  NAND _0688_ (
    .A(counter[23]),
    .B(_0183_),
    .Y(_0188_)
  );
  NAND _0689_ (
    .A(_0048_),
    .B(_0184_),
    .Y(_0189_)
  );
  NAND _0690_ (
    .A(reset),
    .B(_0189_),
    .Y(_0190_)
  );
  NOR _0691_ (
    .A(_0187_),
    .B(_0190_),
    .Y(_0003_[23])
  );
  NOR _0692_ (
    .A(_0049_),
    .B(_0188_),
    .Y(_0191_)
  );
  NAND _0693_ (
    .A(counter[24]),
    .B(_0187_),
    .Y(_0192_)
  );
  NAND _0694_ (
    .A(_0049_),
    .B(_0188_),
    .Y(_0193_)
  );
  NAND _0695_ (
    .A(reset),
    .B(_0193_),
    .Y(_0194_)
  );
  NOR _0696_ (
    .A(_0191_),
    .B(_0194_),
    .Y(_0003_[24])
  );
  NOR _0697_ (
    .A(_0050_),
    .B(_0192_),
    .Y(_0195_)
  );
  NAND _0698_ (
    .A(counter[25]),
    .B(_0191_),
    .Y(_0196_)
  );
  NAND _0699_ (
    .A(_0050_),
    .B(_0192_),
    .Y(_0197_)
  );
  NAND _0700_ (
    .A(reset),
    .B(_0197_),
    .Y(_0198_)
  );
  NOR _0701_ (
    .A(_0195_),
    .B(_0198_),
    .Y(_0003_[25])
  );
  NOR _0702_ (
    .A(_0051_),
    .B(_0196_),
    .Y(_0199_)
  );
  NAND _0703_ (
    .A(counter[26]),
    .B(_0195_),
    .Y(_0200_)
  );
  NAND _0704_ (
    .A(_0051_),
    .B(_0196_),
    .Y(_0201_)
  );
  NAND _0705_ (
    .A(reset),
    .B(_0201_),
    .Y(_0202_)
  );
  NOR _0706_ (
    .A(_0199_),
    .B(_0202_),
    .Y(_0003_[26])
  );
  NOR _0707_ (
    .A(_0052_),
    .B(_0200_),
    .Y(_0203_)
  );
  NAND _0708_ (
    .A(counter[27]),
    .B(_0199_),
    .Y(_0204_)
  );
  NAND _0709_ (
    .A(_0052_),
    .B(_0200_),
    .Y(_0205_)
  );
  NAND _0710_ (
    .A(reset),
    .B(_0205_),
    .Y(_0206_)
  );
  NOR _0711_ (
    .A(_0203_),
    .B(_0206_),
    .Y(_0003_[27])
  );
  NOR _0712_ (
    .A(_0053_),
    .B(_0204_),
    .Y(_0207_)
  );
  NAND _0713_ (
    .A(counter[28]),
    .B(_0203_),
    .Y(_0208_)
  );
  NAND _0714_ (
    .A(_0053_),
    .B(_0204_),
    .Y(_0209_)
  );
  NAND _0715_ (
    .A(reset),
    .B(_0209_),
    .Y(_0210_)
  );
  NOR _0716_ (
    .A(_0207_),
    .B(_0210_),
    .Y(_0003_[28])
  );
  NOR _0717_ (
    .A(_0054_),
    .B(_0208_),
    .Y(_0211_)
  );
  NAND _0718_ (
    .A(_0054_),
    .B(_0208_),
    .Y(_0212_)
  );
  NAND _0719_ (
    .A(reset),
    .B(_0212_),
    .Y(_0213_)
  );
  NOR _0720_ (
    .A(_0211_),
    .B(_0213_),
    .Y(_0003_[29])
  );
  NAND _0721_ (
    .A(counter[30]),
    .B(_0211_),
    .Y(_0214_)
  );
  NOT _0722_ (
    .A(_0214_),
    .Y(_0215_)
  );
  NOR _0723_ (
    .A(counter[30]),
    .B(_0211_),
    .Y(_0216_)
  );
  NOT _0724_ (
    .A(_0216_),
    .Y(_0217_)
  );
  NAND _0725_ (
    .A(reset),
    .B(_0217_),
    .Y(_0218_)
  );
  NOR _0726_ (
    .A(_0215_),
    .B(_0218_),
    .Y(_0003_[30])
  );
  NOR _0727_ (
    .A(_0055_),
    .B(_0214_),
    .Y(_0219_)
  );
  NAND _0728_ (
    .A(_0055_),
    .B(_0214_),
    .Y(_0220_)
  );
  NAND _0729_ (
    .A(reset),
    .B(_0220_),
    .Y(_0221_)
  );
  NOR _0730_ (
    .A(_0219_),
    .B(_0221_),
    .Y(_0003_[31])
  );
  NOR _0731_ (
    .A(buffer[1]),
    .B(buffer[6]),
    .Y(_0222_)
  );
  NOR _0732_ (
    .A(buffer[0]),
    .B(_0064_),
    .Y(_0223_)
  );
  NAND _0733_ (
    .A(buffer[7]),
    .B(_0223_),
    .Y(_0224_)
  );
  NOR _0734_ (
    .A(_0063_),
    .B(_0065_),
    .Y(_0225_)
  );
  NAND _0735_ (
    .A(_0222_),
    .B(_0225_),
    .Y(_0226_)
  );
  NOR _0736_ (
    .A(_0224_),
    .B(_0226_),
    .Y(_0227_)
  );
  NOT _0737_ (
    .A(_0227_),
    .Y(_0228_)
  );
  NOR _0738_ (
    .A(_0062_),
    .B(_0228_),
    .Y(_0229_)
  );
  NAND _0739_ (
    .A(buffer[2]),
    .B(_0227_),
    .Y(_0230_)
  );
  NOR _0740_ (
    .A(BC_counter[28]),
    .B(BC_counter[29]),
    .Y(_0231_)
  );
  NAND _0741_ (
    .A(_0025_),
    .B(_0231_),
    .Y(_0232_)
  );
  NAND _0742_ (
    .A(_0017_),
    .B(_0020_),
    .Y(_0233_)
  );
  NAND _0743_ (
    .A(_0018_),
    .B(_0019_),
    .Y(_0234_)
  );
  NOR _0744_ (
    .A(BC_counter[24]),
    .B(BC_counter[25]),
    .Y(_0235_)
  );
  NOR _0745_ (
    .A(BC_counter[26]),
    .B(BC_counter[27]),
    .Y(_0236_)
  );
  NAND _0746_ (
    .A(_0235_),
    .B(_0236_),
    .Y(_0237_)
  );
  NOR _0747_ (
    .A(_0233_),
    .B(_0237_),
    .Y(_0238_)
  );
  NOR _0748_ (
    .A(_0232_),
    .B(_0234_),
    .Y(_0239_)
  );
  NAND _0749_ (
    .A(_0238_),
    .B(_0239_),
    .Y(_0240_)
  );
  NOR _0750_ (
    .A(BC_counter[8]),
    .B(BC_counter[9]),
    .Y(_0241_)
  );
  NOR _0751_ (
    .A(BC_counter[10]),
    .B(BC_counter[11]),
    .Y(_0242_)
  );
  NAND _0752_ (
    .A(_0241_),
    .B(_0242_),
    .Y(_0243_)
  );
  NOR _0753_ (
    .A(BC_counter[5]),
    .B(BC_counter[6]),
    .Y(_0244_)
  );
  NOR _0754_ (
    .A(BC_counter[4]),
    .B(BC_counter[7]),
    .Y(_0245_)
  );
  NAND _0755_ (
    .A(_0244_),
    .B(_0245_),
    .Y(_0246_)
  );
  NOR _0756_ (
    .A(_0243_),
    .B(_0246_),
    .Y(_0247_)
  );
  NOR _0757_ (
    .A(BC_counter[17]),
    .B(BC_counter[18]),
    .Y(_0248_)
  );
  NOR _0758_ (
    .A(BC_counter[16]),
    .B(BC_counter[19]),
    .Y(_0249_)
  );
  NAND _0759_ (
    .A(_0248_),
    .B(_0249_),
    .Y(_0250_)
  );
  NOR _0760_ (
    .A(BC_counter[12]),
    .B(BC_counter[13]),
    .Y(_0251_)
  );
  NOR _0761_ (
    .A(BC_counter[14]),
    .B(BC_counter[15]),
    .Y(_0252_)
  );
  NAND _0762_ (
    .A(_0251_),
    .B(_0252_),
    .Y(_0253_)
  );
  NOR _0763_ (
    .A(_0250_),
    .B(_0253_),
    .Y(_0254_)
  );
  NAND _0764_ (
    .A(_0247_),
    .B(_0254_),
    .Y(_0255_)
  );
  NOR _0765_ (
    .A(_0240_),
    .B(_0255_),
    .Y(_0256_)
  );
  NAND _0766_ (
    .A(_0061_),
    .B(_0256_),
    .Y(_0257_)
  );
  NOR _0767_ (
    .A(BC_counter[3]),
    .B(_0257_),
    .Y(_0258_)
  );
  NOR _0768_ (
    .A(BC_counter[31]),
    .B(_0258_),
    .Y(_0259_)
  );
  NOR _0769_ (
    .A(_0230_),
    .B(_0259_),
    .Y(_0260_)
  );
  NOT _0770_ (
    .A(_0260_),
    .Y(_0261_)
  );
  NOR _0771_ (
    .A(BC_counter[0]),
    .B(BC_counter[1]),
    .Y(_0262_)
  );
  NAND _0772_ (
    .A(BC_counter[2]),
    .B(_0262_),
    .Y(_0263_)
  );
  NOT _0773_ (
    .A(_0263_),
    .Y(_0264_)
  );
  NOR _0774_ (
    .A(counter[3]),
    .B(counter[2]),
    .Y(_0265_)
  );
  NOT _0775_ (
    .A(_0265_),
    .Y(_0266_)
  );
  NOR _0776_ (
    .A(BC_counter[3]),
    .B(BC_counter[31]),
    .Y(_0267_)
  );
  NAND _0777_ (
    .A(_0265_),
    .B(_0267_),
    .Y(_0268_)
  );
  NOR _0778_ (
    .A(_0073_),
    .B(_0268_),
    .Y(_0269_)
  );
  NAND _0779_ (
    .A(_0264_),
    .B(_0269_),
    .Y(_0270_)
  );
  NAND _0780_ (
    .A(_0105_),
    .B(_0256_),
    .Y(_0271_)
  );
  NOR _0781_ (
    .A(_0270_),
    .B(_0271_),
    .Y(_0272_)
  );
  NOT _0782_ (
    .A(_0272_),
    .Y(_0273_)
  );
  NAND _0783_ (
    .A(valid_out),
    .B(_0273_),
    .Y(_0274_)
  );
  NAND _0784_ (
    .A(BC_counter[2]),
    .B(_0256_),
    .Y(_0275_)
  );
  NAND _0785_ (
    .A(_0072_),
    .B(_0262_),
    .Y(_0276_)
  );
  NOT _0786_ (
    .A(_0276_),
    .Y(_0277_)
  );
  NOR _0787_ (
    .A(BC_counter[3]),
    .B(_0266_),
    .Y(_0278_)
  );
  NAND _0788_ (
    .A(_0277_),
    .B(_0278_),
    .Y(_0279_)
  );
  NOR _0789_ (
    .A(BC_counter[31]),
    .B(_0279_),
    .Y(_0280_)
  );
  NAND _0790_ (
    .A(_0105_),
    .B(_0280_),
    .Y(_0281_)
  );
  NOR _0791_ (
    .A(_0275_),
    .B(_0281_),
    .Y(_0282_)
  );
  NOT _0792_ (
    .A(_0282_),
    .Y(_0283_)
  );
  NOR _0793_ (
    .A(_0260_),
    .B(_0274_),
    .Y(_0284_)
  );
  NOR _0794_ (
    .A(_0229_),
    .B(_0273_),
    .Y(_0285_)
  );
  NOR _0795_ (
    .A(_0227_),
    .B(_0283_),
    .Y(_0286_)
  );
  NOR _0796_ (
    .A(buffer[2]),
    .B(_0283_),
    .Y(_0287_)
  );
  NOR _0797_ (
    .A(_0284_),
    .B(_0285_),
    .Y(_0288_)
  );
  NOR _0798_ (
    .A(_0059_),
    .B(_0288_),
    .Y(_0005_)
  );
  NOR _0799_ (
    .A(active),
    .B(_0282_),
    .Y(_0289_)
  );
  NOR _0800_ (
    .A(_0059_),
    .B(_0289_),
    .Y(_0001_)
  );
  NAND _0801_ (
    .A(reset),
    .B(data_in),
    .Y(_0290_)
  );
  NOT _0802_ (
    .A(_0290_),
    .Y(_0002_[0])
  );
  NOR _0803_ (
    .A(_0026_),
    .B(_0059_),
    .Y(_0002_[1])
  );
  NOR _0804_ (
    .A(_0027_),
    .B(_0059_),
    .Y(_0002_[2])
  );
  NAND _0805_ (
    .A(reset),
    .B(buffer[2]),
    .Y(_0291_)
  );
  NOT _0806_ (
    .A(_0291_),
    .Y(_0002_[3])
  );
  NAND _0807_ (
    .A(reset),
    .B(buffer[3]),
    .Y(_0292_)
  );
  NOT _0808_ (
    .A(_0292_),
    .Y(_0002_[4])
  );
  NAND _0809_ (
    .A(reset),
    .B(buffer[4]),
    .Y(_0293_)
  );
  NOT _0810_ (
    .A(_0293_),
    .Y(_0002_[5])
  );
  NAND _0811_ (
    .A(reset),
    .B(buffer[5]),
    .Y(_0294_)
  );
  NOT _0812_ (
    .A(_0294_),
    .Y(_0002_[6])
  );
  NOR _0813_ (
    .A(_0028_),
    .B(_0059_),
    .Y(_0002_[7])
  );
  NAND _0814_ (
    .A(BC_counter[0]),
    .B(_0260_),
    .Y(_0295_)
  );
  NOT _0815_ (
    .A(_0295_),
    .Y(_0296_)
  );
  NOR _0816_ (
    .A(BC_counter[0]),
    .B(_0260_),
    .Y(_0297_)
  );
  NOT _0817_ (
    .A(_0297_),
    .Y(_0298_)
  );
  NAND _0818_ (
    .A(reset),
    .B(_0298_),
    .Y(_0299_)
  );
  NOR _0819_ (
    .A(_0296_),
    .B(_0299_),
    .Y(_0000_[0])
  );
  NAND _0820_ (
    .A(_0060_),
    .B(_0295_),
    .Y(_0300_)
  );
  NOR _0821_ (
    .A(_0060_),
    .B(_0295_),
    .Y(_0301_)
  );
  NAND _0822_ (
    .A(reset),
    .B(_0300_),
    .Y(_0302_)
  );
  NOR _0823_ (
    .A(_0301_),
    .B(_0302_),
    .Y(_0000_[1])
  );
  NOR _0824_ (
    .A(BC_counter[2]),
    .B(_0301_),
    .Y(_0303_)
  );
  NOT _0825_ (
    .A(_0303_),
    .Y(_0304_)
  );
  NAND _0826_ (
    .A(BC_counter[2]),
    .B(_0301_),
    .Y(_0305_)
  );
  NOT _0827_ (
    .A(_0305_),
    .Y(_0306_)
  );
  NAND _0828_ (
    .A(_0304_),
    .B(_0305_),
    .Y(_0307_)
  );
  NOR _0829_ (
    .A(_0282_),
    .B(_0307_),
    .Y(_0308_)
  );
  NOR _0830_ (
    .A(_0285_),
    .B(_0308_),
    .Y(_0309_)
  );
  NOR _0831_ (
    .A(_0059_),
    .B(_0309_),
    .Y(_0000_[2])
  );
  NAND _0832_ (
    .A(_0006_),
    .B(_0305_),
    .Y(_0310_)
  );
  NAND _0833_ (
    .A(reset),
    .B(_0310_),
    .Y(_0311_)
  );
  NOR _0834_ (
    .A(_0006_),
    .B(_0305_),
    .Y(_0312_)
  );
  NAND _0835_ (
    .A(BC_counter[3]),
    .B(_0306_),
    .Y(_0313_)
  );
  NOR _0836_ (
    .A(_0311_),
    .B(_0312_),
    .Y(_0000_[3])
  );
  NAND _0837_ (
    .A(_0007_),
    .B(_0313_),
    .Y(_0314_)
  );
  NAND _0838_ (
    .A(reset),
    .B(_0314_),
    .Y(_0315_)
  );
  NAND _0839_ (
    .A(BC_counter[3]),
    .B(BC_counter[4]),
    .Y(_0316_)
  );
  NOR _0840_ (
    .A(_0305_),
    .B(_0316_),
    .Y(_0317_)
  );
  NOR _0841_ (
    .A(_0315_),
    .B(_0317_),
    .Y(_0000_[4])
  );
  NOR _0842_ (
    .A(BC_counter[5]),
    .B(_0317_),
    .Y(_0318_)
  );
  NOT _0843_ (
    .A(_0318_),
    .Y(_0319_)
  );
  NAND _0844_ (
    .A(reset),
    .B(_0319_),
    .Y(_0320_)
  );
  NAND _0845_ (
    .A(BC_counter[5]),
    .B(_0317_),
    .Y(_0321_)
  );
  NOT _0846_ (
    .A(_0321_),
    .Y(_0322_)
  );
  NOR _0847_ (
    .A(_0320_),
    .B(_0322_),
    .Y(_0000_[5])
  );
  NOR _0848_ (
    .A(_0008_),
    .B(_0321_),
    .Y(_0323_)
  );
  NAND _0849_ (
    .A(BC_counter[6]),
    .B(_0322_),
    .Y(_0324_)
  );
  NAND _0850_ (
    .A(_0008_),
    .B(_0321_),
    .Y(_0325_)
  );
  NAND _0851_ (
    .A(reset),
    .B(_0325_),
    .Y(_0326_)
  );
  NOR _0852_ (
    .A(_0323_),
    .B(_0326_),
    .Y(_0000_[6])
  );
  NOR _0853_ (
    .A(_0009_),
    .B(_0324_),
    .Y(_0327_)
  );
  NAND _0854_ (
    .A(_0009_),
    .B(_0324_),
    .Y(_0328_)
  );
  NAND _0855_ (
    .A(reset),
    .B(_0328_),
    .Y(_0329_)
  );
  NOR _0856_ (
    .A(_0327_),
    .B(_0329_),
    .Y(_0000_[7])
  );
  NOR _0857_ (
    .A(BC_counter[8]),
    .B(_0327_),
    .Y(_0330_)
  );
  NOT _0858_ (
    .A(_0330_),
    .Y(_0331_)
  );
  NAND _0859_ (
    .A(reset),
    .B(_0331_),
    .Y(_0332_)
  );
  NAND _0860_ (
    .A(BC_counter[7]),
    .B(BC_counter[8]),
    .Y(_0333_)
  );
  NOR _0861_ (
    .A(_0324_),
    .B(_0333_),
    .Y(_0334_)
  );
  NOR _0862_ (
    .A(_0332_),
    .B(_0334_),
    .Y(_0000_[8])
  );
  NOR _0863_ (
    .A(BC_counter[9]),
    .B(_0334_),
    .Y(_0335_)
  );
  NOR _0864_ (
    .A(_0010_),
    .B(_0333_),
    .Y(_0336_)
  );
  NOT _0865_ (
    .A(_0336_),
    .Y(_0337_)
  );
  NAND _0866_ (
    .A(_0323_),
    .B(_0336_),
    .Y(_0338_)
  );
  NAND _0867_ (
    .A(reset),
    .B(_0338_),
    .Y(_0339_)
  );
  NAND _0868_ (
    .A(BC_counter[9]),
    .B(_0334_),
    .Y(_0340_)
  );
  NOT _0869_ (
    .A(_0340_),
    .Y(_0341_)
  );
  NOR _0870_ (
    .A(_0335_),
    .B(_0339_),
    .Y(_0000_[9])
  );
  NAND _0871_ (
    .A(_0011_),
    .B(_0338_),
    .Y(_0342_)
  );
  NAND _0872_ (
    .A(reset),
    .B(_0342_),
    .Y(_0343_)
  );
  NAND _0873_ (
    .A(BC_counter[10]),
    .B(_0341_),
    .Y(_0344_)
  );
  NOT _0874_ (
    .A(_0344_),
    .Y(_0345_)
  );
  NOR _0875_ (
    .A(_0343_),
    .B(_0345_),
    .Y(_0000_[10])
  );
  NAND _0876_ (
    .A(_0012_),
    .B(_0344_),
    .Y(_0346_)
  );
  NAND _0877_ (
    .A(BC_counter[10]),
    .B(BC_counter[11]),
    .Y(_0347_)
  );
  NOR _0878_ (
    .A(_0338_),
    .B(_0347_),
    .Y(_0348_)
  );
  NAND _0879_ (
    .A(reset),
    .B(_0346_),
    .Y(_0349_)
  );
  NOR _0880_ (
    .A(_0012_),
    .B(_0344_),
    .Y(_0350_)
  );
  NOR _0881_ (
    .A(_0348_),
    .B(_0349_),
    .Y(_0000_[11])
  );
  NOR _0882_ (
    .A(BC_counter[12]),
    .B(_0348_),
    .Y(_0351_)
  );
  NOT _0883_ (
    .A(_0351_),
    .Y(_0352_)
  );
  NAND _0884_ (
    .A(reset),
    .B(_0352_),
    .Y(_0353_)
  );
  NAND _0885_ (
    .A(BC_counter[12]),
    .B(_0348_),
    .Y(_0354_)
  );
  NOT _0886_ (
    .A(_0354_),
    .Y(_0355_)
  );
  NAND _0887_ (
    .A(BC_counter[12]),
    .B(_0350_),
    .Y(_0356_)
  );
  NOR _0888_ (
    .A(_0353_),
    .B(_0355_),
    .Y(_0000_[12])
  );
  NAND _0889_ (
    .A(_0013_),
    .B(_0354_),
    .Y(_0357_)
  );
  NAND _0890_ (
    .A(reset),
    .B(_0357_),
    .Y(_0358_)
  );
  NOR _0891_ (
    .A(_0013_),
    .B(_0354_),
    .Y(_0359_)
  );
  NOR _0892_ (
    .A(_0358_),
    .B(_0359_),
    .Y(_0000_[13])
  );
  NOR _0893_ (
    .A(BC_counter[14]),
    .B(_0359_),
    .Y(_0360_)
  );
  NOT _0894_ (
    .A(_0360_),
    .Y(_0361_)
  );
  NAND _0895_ (
    .A(reset),
    .B(_0361_),
    .Y(_0362_)
  );
  NAND _0896_ (
    .A(BC_counter[14]),
    .B(_0359_),
    .Y(_0363_)
  );
  NAND _0897_ (
    .A(BC_counter[13]),
    .B(BC_counter[14]),
    .Y(_0364_)
  );
  NOR _0898_ (
    .A(_0356_),
    .B(_0364_),
    .Y(_0365_)
  );
  NOR _0899_ (
    .A(_0362_),
    .B(_0365_),
    .Y(_0000_[14])
  );
  NAND _0900_ (
    .A(_0014_),
    .B(_0363_),
    .Y(_0366_)
  );
  NAND _0901_ (
    .A(reset),
    .B(_0366_),
    .Y(_0367_)
  );
  NOR _0902_ (
    .A(_0014_),
    .B(_0363_),
    .Y(_0368_)
  );
  NAND _0903_ (
    .A(BC_counter[15]),
    .B(_0365_),
    .Y(_0369_)
  );
  NOR _0904_ (
    .A(_0367_),
    .B(_0368_),
    .Y(_0000_[15])
  );
  NOR _0905_ (
    .A(_0014_),
    .B(_0364_),
    .Y(_0370_)
  );
  NAND _0906_ (
    .A(_0015_),
    .B(_0369_),
    .Y(_0371_)
  );
  NAND _0907_ (
    .A(reset),
    .B(_0371_),
    .Y(_0372_)
  );
  NOR _0908_ (
    .A(_0015_),
    .B(_0369_),
    .Y(_0373_)
  );
  NOR _0909_ (
    .A(_0372_),
    .B(_0373_),
    .Y(_0000_[16])
  );
  NAND _0910_ (
    .A(BC_counter[12]),
    .B(BC_counter[17]),
    .Y(_0374_)
  );
  NOR _0911_ (
    .A(_0015_),
    .B(_0347_),
    .Y(_0375_)
  );
  NAND _0912_ (
    .A(_0370_),
    .B(_0375_),
    .Y(_0376_)
  );
  NOR _0913_ (
    .A(_0374_),
    .B(_0376_),
    .Y(_0377_)
  );
  NOT _0914_ (
    .A(_0377_),
    .Y(_0378_)
  );
  NAND _0915_ (
    .A(_0341_),
    .B(_0377_),
    .Y(_0379_)
  );
  NOT _0916_ (
    .A(_0379_),
    .Y(_0380_)
  );
  NOR _0917_ (
    .A(BC_counter[17]),
    .B(_0373_),
    .Y(_0381_)
  );
  NOT _0918_ (
    .A(_0381_),
    .Y(_0382_)
  );
  NAND _0919_ (
    .A(reset),
    .B(_0382_),
    .Y(_0383_)
  );
  NOR _0920_ (
    .A(_0380_),
    .B(_0383_),
    .Y(_0000_[17])
  );
  NOR _0921_ (
    .A(_0016_),
    .B(_0379_),
    .Y(_0384_)
  );
  NAND _0922_ (
    .A(_0016_),
    .B(_0379_),
    .Y(_0385_)
  );
  NAND _0923_ (
    .A(reset),
    .B(_0385_),
    .Y(_0386_)
  );
  NOR _0924_ (
    .A(_0384_),
    .B(_0386_),
    .Y(_0000_[18])
  );
  NOR _0925_ (
    .A(BC_counter[19]),
    .B(_0384_),
    .Y(_0387_)
  );
  NOT _0926_ (
    .A(_0387_),
    .Y(_0388_)
  );
  NAND _0927_ (
    .A(reset),
    .B(_0388_),
    .Y(_0389_)
  );
  NAND _0928_ (
    .A(BC_counter[18]),
    .B(BC_counter[19]),
    .Y(_0390_)
  );
  NOR _0929_ (
    .A(_0379_),
    .B(_0390_),
    .Y(_0391_)
  );
  NOR _0930_ (
    .A(_0389_),
    .B(_0391_),
    .Y(_0000_[19])
  );
  NOR _0931_ (
    .A(BC_counter[20]),
    .B(_0391_),
    .Y(_0392_)
  );
  NOT _0932_ (
    .A(_0392_),
    .Y(_0393_)
  );
  NAND _0933_ (
    .A(reset),
    .B(_0393_),
    .Y(_0394_)
  );
  NAND _0934_ (
    .A(BC_counter[20]),
    .B(_0391_),
    .Y(_0395_)
  );
  NOT _0935_ (
    .A(_0395_),
    .Y(_0396_)
  );
  NOR _0936_ (
    .A(_0394_),
    .B(_0396_),
    .Y(_0000_[20])
  );
  NAND _0937_ (
    .A(_0018_),
    .B(_0395_),
    .Y(_0397_)
  );
  NAND _0938_ (
    .A(BC_counter[20]),
    .B(BC_counter[21]),
    .Y(_0398_)
  );
  NOR _0939_ (
    .A(_0017_),
    .B(_0390_),
    .Y(_0399_)
  );
  NOR _0940_ (
    .A(_0390_),
    .B(_0398_),
    .Y(_0400_)
  );
  NAND _0941_ (
    .A(BC_counter[21]),
    .B(_0399_),
    .Y(_0401_)
  );
  NOR _0942_ (
    .A(_0379_),
    .B(_0401_),
    .Y(_0402_)
  );
  NAND _0943_ (
    .A(reset),
    .B(_0397_),
    .Y(_0403_)
  );
  NOR _0944_ (
    .A(_0402_),
    .B(_0403_),
    .Y(_0000_[21])
  );
  NOR _0945_ (
    .A(_0337_),
    .B(_0401_),
    .Y(_0404_)
  );
  NAND _0946_ (
    .A(_0336_),
    .B(_0400_),
    .Y(_0405_)
  );
  NOR _0947_ (
    .A(_0378_),
    .B(_0405_),
    .Y(_0406_)
  );
  NAND _0948_ (
    .A(_0377_),
    .B(_0404_),
    .Y(_0407_)
  );
  NOR _0949_ (
    .A(_0324_),
    .B(_0407_),
    .Y(_0408_)
  );
  NAND _0950_ (
    .A(_0323_),
    .B(_0406_),
    .Y(_0409_)
  );
  NOR _0951_ (
    .A(BC_counter[22]),
    .B(_0408_),
    .Y(_0410_)
  );
  NOT _0952_ (
    .A(_0410_),
    .Y(_0411_)
  );
  NAND _0953_ (
    .A(reset),
    .B(_0411_),
    .Y(_0412_)
  );
  NOR _0954_ (
    .A(_0019_),
    .B(_0409_),
    .Y(_0413_)
  );
  NAND _0955_ (
    .A(BC_counter[22]),
    .B(_0408_),
    .Y(_0414_)
  );
  NOR _0956_ (
    .A(_0412_),
    .B(_0413_),
    .Y(_0000_[22])
  );
  NAND _0957_ (
    .A(_0020_),
    .B(_0414_),
    .Y(_0415_)
  );
  NAND _0958_ (
    .A(reset),
    .B(_0415_),
    .Y(_0416_)
  );
  NOR _0959_ (
    .A(_0020_),
    .B(_0414_),
    .Y(_0417_)
  );
  NAND _0960_ (
    .A(BC_counter[23]),
    .B(_0413_),
    .Y(_0418_)
  );
  NOR _0961_ (
    .A(_0416_),
    .B(_0417_),
    .Y(_0000_[23])
  );
  NAND _0962_ (
    .A(_0021_),
    .B(_0418_),
    .Y(_0419_)
  );
  NAND _0963_ (
    .A(reset),
    .B(_0419_),
    .Y(_0420_)
  );
  NOR _0964_ (
    .A(_0021_),
    .B(_0418_),
    .Y(_0421_)
  );
  NOR _0965_ (
    .A(_0420_),
    .B(_0421_),
    .Y(_0000_[24])
  );
  NOR _0966_ (
    .A(BC_counter[25]),
    .B(_0421_),
    .Y(_0422_)
  );
  NOT _0967_ (
    .A(_0422_),
    .Y(_0423_)
  );
  NAND _0968_ (
    .A(reset),
    .B(_0423_),
    .Y(_0424_)
  );
  NAND _0969_ (
    .A(BC_counter[25]),
    .B(_0421_),
    .Y(_0425_)
  );
  NOT _0970_ (
    .A(_0425_),
    .Y(_0426_)
  );
  NOR _0971_ (
    .A(_0424_),
    .B(_0426_),
    .Y(_0000_[25])
  );
  NAND _0972_ (
    .A(_0022_),
    .B(_0425_),
    .Y(_0427_)
  );
  NAND _0973_ (
    .A(reset),
    .B(_0427_),
    .Y(_0428_)
  );
  NOR _0974_ (
    .A(_0022_),
    .B(_0425_),
    .Y(_0429_)
  );
  NOR _0975_ (
    .A(_0428_),
    .B(_0429_),
    .Y(_0000_[26])
  );
  NOR _0976_ (
    .A(BC_counter[27]),
    .B(_0429_),
    .Y(_0430_)
  );
  NAND _0977_ (
    .A(BC_counter[25]),
    .B(BC_counter[26]),
    .Y(_0431_)
  );
  NOR _0978_ (
    .A(_0023_),
    .B(_0431_),
    .Y(_0432_)
  );
  NAND _0979_ (
    .A(_0421_),
    .B(_0432_),
    .Y(_0433_)
  );
  NAND _0980_ (
    .A(reset),
    .B(_0433_),
    .Y(_0434_)
  );
  NOR _0981_ (
    .A(_0430_),
    .B(_0434_),
    .Y(_0000_[27])
  );
  NAND _0982_ (
    .A(_0024_),
    .B(_0433_),
    .Y(_0435_)
  );
  NAND _0983_ (
    .A(reset),
    .B(_0435_),
    .Y(_0436_)
  );
  NOR _0984_ (
    .A(_0024_),
    .B(_0433_),
    .Y(_0437_)
  );
  NOR _0985_ (
    .A(_0436_),
    .B(_0437_),
    .Y(_0000_[28])
  );
  NOR _0986_ (
    .A(BC_counter[29]),
    .B(_0437_),
    .Y(_0438_)
  );
  NOT _0987_ (
    .A(_0438_),
    .Y(_0439_)
  );
  NAND _0988_ (
    .A(reset),
    .B(_0439_),
    .Y(_0440_)
  );
  NAND _0989_ (
    .A(BC_counter[29]),
    .B(_0437_),
    .Y(_0441_)
  );
  NOT _0990_ (
    .A(_0441_),
    .Y(_0442_)
  );
  NOR _0991_ (
    .A(_0440_),
    .B(_0442_),
    .Y(_0000_[29])
  );
  NAND _0992_ (
    .A(_0025_),
    .B(_0441_),
    .Y(_0443_)
  );
  NAND _0993_ (
    .A(reset),
    .B(_0443_),
    .Y(_0444_)
  );
  NOR _0994_ (
    .A(_0025_),
    .B(_0441_),
    .Y(_0445_)
  );
  NAND _0995_ (
    .A(BC_counter[30]),
    .B(_0442_),
    .Y(_0446_)
  );
  NOR _0996_ (
    .A(_0444_),
    .B(_0445_),
    .Y(_0000_[30])
  );
  NAND _0997_ (
    .A(BC_counter[31]),
    .B(_0446_),
    .Y(_0447_)
  );
  NOR _0998_ (
    .A(_0059_),
    .B(_0447_),
    .Y(_0000_[31])
  );
  NOR _0999_ (
    .A(_0059_),
    .B(_0287_),
    .Y(_0448_)
  );
  NAND _1000_ (
    .A(data_out[0]),
    .B(_0448_),
    .Y(_0449_)
  );
  NOR _1001_ (
    .A(_0286_),
    .B(_0449_),
    .Y(_0450_)
  );
  NOR _1002_ (
    .A(_0002_[1]),
    .B(_0450_),
    .Y(_0451_)
  );
  NOR _1003_ (
    .A(_0066_),
    .B(_0260_),
    .Y(_0452_)
  );
  NOR _1004_ (
    .A(_0282_),
    .B(_0452_),
    .Y(_0453_)
  );
  NOR _1005_ (
    .A(_0451_),
    .B(_0453_),
    .Y(_0004_[0])
  );
  NAND _1006_ (
    .A(data_out[1]),
    .B(_0448_),
    .Y(_0454_)
  );
  NOR _1007_ (
    .A(_0286_),
    .B(_0454_),
    .Y(_0455_)
  );
  NOR _1008_ (
    .A(_0002_[2]),
    .B(_0455_),
    .Y(_0456_)
  );
  NOR _1009_ (
    .A(_0067_),
    .B(_0260_),
    .Y(_0457_)
  );
  NOR _1010_ (
    .A(_0282_),
    .B(_0457_),
    .Y(_0458_)
  );
  NOR _1011_ (
    .A(_0456_),
    .B(_0458_),
    .Y(_0004_[1])
  );
  NOR _1012_ (
    .A(data_out[2]),
    .B(_0286_),
    .Y(_0459_)
  );
  NAND _1013_ (
    .A(_0261_),
    .B(_0448_),
    .Y(_0460_)
  );
  NOR _1014_ (
    .A(_0459_),
    .B(_0460_),
    .Y(_0004_[2])
  );
  NAND _1015_ (
    .A(reset),
    .B(_0261_),
    .Y(_0461_)
  );
  NOR _1016_ (
    .A(data_out[3]),
    .B(_0285_),
    .Y(_0462_)
  );
  NOT _1017_ (
    .A(_0462_),
    .Y(_0463_)
  );
  NAND _1018_ (
    .A(_0063_),
    .B(_0272_),
    .Y(_0464_)
  );
  NAND _1019_ (
    .A(_0463_),
    .B(_0464_),
    .Y(_0465_)
  );
  NOR _1020_ (
    .A(_0461_),
    .B(_0465_),
    .Y(_0004_[3])
  );
  NOR _1021_ (
    .A(data_out[4]),
    .B(_0285_),
    .Y(_0466_)
  );
  NOT _1022_ (
    .A(_0466_),
    .Y(_0467_)
  );
  NAND _1023_ (
    .A(_0064_),
    .B(_0272_),
    .Y(_0468_)
  );
  NAND _1024_ (
    .A(_0467_),
    .B(_0468_),
    .Y(_0469_)
  );
  NOR _1025_ (
    .A(_0461_),
    .B(_0469_),
    .Y(_0004_[4])
  );
  NOR _1026_ (
    .A(data_out[5]),
    .B(_0285_),
    .Y(_0470_)
  );
  NOT _1027_ (
    .A(_0470_),
    .Y(_0471_)
  );
  NAND _1028_ (
    .A(_0065_),
    .B(_0272_),
    .Y(_0472_)
  );
  NAND _1029_ (
    .A(_0471_),
    .B(_0472_),
    .Y(_0473_)
  );
  NOR _1030_ (
    .A(_0461_),
    .B(_0473_),
    .Y(_0004_[5])
  );
  NAND _1031_ (
    .A(data_out[6]),
    .B(_0448_),
    .Y(_0474_)
  );
  NOR _1032_ (
    .A(_0286_),
    .B(_0474_),
    .Y(_0475_)
  );
  NOR _1033_ (
    .A(_0002_[7]),
    .B(_0475_),
    .Y(_0476_)
  );
  NOR _1034_ (
    .A(_0068_),
    .B(_0260_),
    .Y(_0477_)
  );
  NOR _1035_ (
    .A(_0282_),
    .B(_0477_),
    .Y(_0478_)
  );
  NOR _1036_ (
    .A(_0476_),
    .B(_0478_),
    .Y(_0004_[6])
  );
  NOR _1037_ (
    .A(data_out[7]),
    .B(_0285_),
    .Y(_0479_)
  );
  NOT _1038_ (
    .A(_0479_),
    .Y(_0480_)
  );
  NAND _1039_ (
    .A(_0069_),
    .B(_0272_),
    .Y(_0481_)
  );
  NAND _1040_ (
    .A(_0480_),
    .B(_0481_),
    .Y(_0482_)
  );
  NOR _1041_ (
    .A(_0461_),
    .B(_0482_),
    .Y(_0004_[7])
  );
  (* src = "prueba.v:15" *)
  DFF _1042_ (
    .C(clk_32f),
    .D(_0004_[0]),
    .Q(data_out[0])
  );
  (* src = "prueba.v:15" *)
  DFF _1043_ (
    .C(clk_32f),
    .D(_0004_[1]),
    .Q(data_out[1])
  );
  (* src = "prueba.v:15" *)
  DFF _1044_ (
    .C(clk_32f),
    .D(_0004_[2]),
    .Q(data_out[2])
  );
  (* src = "prueba.v:15" *)
  DFF _1045_ (
    .C(clk_32f),
    .D(_0004_[3]),
    .Q(data_out[3])
  );
  (* src = "prueba.v:15" *)
  DFF _1046_ (
    .C(clk_32f),
    .D(_0004_[4]),
    .Q(data_out[4])
  );
  (* src = "prueba.v:15" *)
  DFF _1047_ (
    .C(clk_32f),
    .D(_0004_[5]),
    .Q(data_out[5])
  );
  (* src = "prueba.v:15" *)
  DFF _1048_ (
    .C(clk_32f),
    .D(_0004_[6]),
    .Q(data_out[6])
  );
  (* src = "prueba.v:15" *)
  DFF _1049_ (
    .C(clk_32f),
    .D(_0004_[7]),
    .Q(data_out[7])
  );
  (* src = "prueba.v:15" *)
  DFF _1050_ (
    .C(clk_32f),
    .D(_0000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "prueba.v:15" *)
  DFF _1051_ (
    .C(clk_32f),
    .D(_0000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "prueba.v:15" *)
  DFF _1052_ (
    .C(clk_32f),
    .D(_0000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "prueba.v:15" *)
  DFF _1053_ (
    .C(clk_32f),
    .D(_0000_[3]),
    .Q(BC_counter[3])
  );
  (* src = "prueba.v:15" *)
  DFF _1054_ (
    .C(clk_32f),
    .D(_0000_[4]),
    .Q(BC_counter[4])
  );
  (* src = "prueba.v:15" *)
  DFF _1055_ (
    .C(clk_32f),
    .D(_0000_[5]),
    .Q(BC_counter[5])
  );
  (* src = "prueba.v:15" *)
  DFF _1056_ (
    .C(clk_32f),
    .D(_0000_[6]),
    .Q(BC_counter[6])
  );
  (* src = "prueba.v:15" *)
  DFF _1057_ (
    .C(clk_32f),
    .D(_0000_[7]),
    .Q(BC_counter[7])
  );
  (* src = "prueba.v:15" *)
  DFF _1058_ (
    .C(clk_32f),
    .D(_0000_[8]),
    .Q(BC_counter[8])
  );
  (* src = "prueba.v:15" *)
  DFF _1059_ (
    .C(clk_32f),
    .D(_0000_[9]),
    .Q(BC_counter[9])
  );
  (* src = "prueba.v:15" *)
  DFF _1060_ (
    .C(clk_32f),
    .D(_0000_[10]),
    .Q(BC_counter[10])
  );
  (* src = "prueba.v:15" *)
  DFF _1061_ (
    .C(clk_32f),
    .D(_0000_[11]),
    .Q(BC_counter[11])
  );
  (* src = "prueba.v:15" *)
  DFF _1062_ (
    .C(clk_32f),
    .D(_0000_[12]),
    .Q(BC_counter[12])
  );
  (* src = "prueba.v:15" *)
  DFF _1063_ (
    .C(clk_32f),
    .D(_0000_[13]),
    .Q(BC_counter[13])
  );
  (* src = "prueba.v:15" *)
  DFF _1064_ (
    .C(clk_32f),
    .D(_0000_[14]),
    .Q(BC_counter[14])
  );
  (* src = "prueba.v:15" *)
  DFF _1065_ (
    .C(clk_32f),
    .D(_0000_[15]),
    .Q(BC_counter[15])
  );
  (* src = "prueba.v:15" *)
  DFF _1066_ (
    .C(clk_32f),
    .D(_0000_[16]),
    .Q(BC_counter[16])
  );
  (* src = "prueba.v:15" *)
  DFF _1067_ (
    .C(clk_32f),
    .D(_0000_[17]),
    .Q(BC_counter[17])
  );
  (* src = "prueba.v:15" *)
  DFF _1068_ (
    .C(clk_32f),
    .D(_0000_[18]),
    .Q(BC_counter[18])
  );
  (* src = "prueba.v:15" *)
  DFF _1069_ (
    .C(clk_32f),
    .D(_0000_[19]),
    .Q(BC_counter[19])
  );
  (* src = "prueba.v:15" *)
  DFF _1070_ (
    .C(clk_32f),
    .D(_0000_[20]),
    .Q(BC_counter[20])
  );
  (* src = "prueba.v:15" *)
  DFF _1071_ (
    .C(clk_32f),
    .D(_0000_[21]),
    .Q(BC_counter[21])
  );
  (* src = "prueba.v:15" *)
  DFF _1072_ (
    .C(clk_32f),
    .D(_0000_[22]),
    .Q(BC_counter[22])
  );
  (* src = "prueba.v:15" *)
  DFF _1073_ (
    .C(clk_32f),
    .D(_0000_[23]),
    .Q(BC_counter[23])
  );
  (* src = "prueba.v:15" *)
  DFF _1074_ (
    .C(clk_32f),
    .D(_0000_[24]),
    .Q(BC_counter[24])
  );
  (* src = "prueba.v:15" *)
  DFF _1075_ (
    .C(clk_32f),
    .D(_0000_[25]),
    .Q(BC_counter[25])
  );
  (* src = "prueba.v:15" *)
  DFF _1076_ (
    .C(clk_32f),
    .D(_0000_[26]),
    .Q(BC_counter[26])
  );
  (* src = "prueba.v:15" *)
  DFF _1077_ (
    .C(clk_32f),
    .D(_0000_[27]),
    .Q(BC_counter[27])
  );
  (* src = "prueba.v:15" *)
  DFF _1078_ (
    .C(clk_32f),
    .D(_0000_[28]),
    .Q(BC_counter[28])
  );
  (* src = "prueba.v:15" *)
  DFF _1079_ (
    .C(clk_32f),
    .D(_0000_[29]),
    .Q(BC_counter[29])
  );
  (* src = "prueba.v:15" *)
  DFF _1080_ (
    .C(clk_32f),
    .D(_0000_[30]),
    .Q(BC_counter[30])
  );
  (* src = "prueba.v:15" *)
  DFF _1081_ (
    .C(clk_32f),
    .D(_0000_[31]),
    .Q(BC_counter[31])
  );
  (* src = "prueba.v:15" *)
  DFF _1082_ (
    .C(clk_32f),
    .D(_0002_[0]),
    .Q(buffer[0])
  );
  (* src = "prueba.v:15" *)
  DFF _1083_ (
    .C(clk_32f),
    .D(_0002_[1]),
    .Q(buffer[1])
  );
  (* src = "prueba.v:15" *)
  DFF _1084_ (
    .C(clk_32f),
    .D(_0002_[2]),
    .Q(buffer[2])
  );
  (* src = "prueba.v:15" *)
  DFF _1085_ (
    .C(clk_32f),
    .D(_0002_[3]),
    .Q(buffer[3])
  );
  (* src = "prueba.v:15" *)
  DFF _1086_ (
    .C(clk_32f),
    .D(_0002_[4]),
    .Q(buffer[4])
  );
  (* src = "prueba.v:15" *)
  DFF _1087_ (
    .C(clk_32f),
    .D(_0002_[5]),
    .Q(buffer[5])
  );
  (* src = "prueba.v:15" *)
  DFF _1088_ (
    .C(clk_32f),
    .D(_0002_[6]),
    .Q(buffer[6])
  );
  (* src = "prueba.v:15" *)
  DFF _1089_ (
    .C(clk_32f),
    .D(_0002_[7]),
    .Q(buffer[7])
  );
  (* src = "prueba.v:15" *)
  DFF _1090_ (
    .C(clk_32f),
    .D(_0001_),
    .Q(active)
  );
  (* src = "prueba.v:15" *)
  DFF _1091_ (
    .C(clk_32f),
    .D(_0005_),
    .Q(valid_out)
  );
  (* src = "prueba.v:15" *)
  DFF _1092_ (
    .C(clk_32f),
    .D(_0003_[0]),
    .Q(counter[0])
  );
  (* src = "prueba.v:15" *)
  DFF _1093_ (
    .C(clk_32f),
    .D(_0003_[1]),
    .Q(counter[1])
  );
  (* src = "prueba.v:15" *)
  DFF _1094_ (
    .C(clk_32f),
    .D(_0003_[2]),
    .Q(counter[2])
  );
  (* src = "prueba.v:15" *)
  DFF _1095_ (
    .C(clk_32f),
    .D(_0003_[3]),
    .Q(counter[3])
  );
  (* src = "prueba.v:15" *)
  DFF _1096_ (
    .C(clk_32f),
    .D(_0003_[4]),
    .Q(counter[4])
  );
  (* src = "prueba.v:15" *)
  DFF _1097_ (
    .C(clk_32f),
    .D(_0003_[5]),
    .Q(counter[5])
  );
  (* src = "prueba.v:15" *)
  DFF _1098_ (
    .C(clk_32f),
    .D(_0003_[6]),
    .Q(counter[6])
  );
  (* src = "prueba.v:15" *)
  DFF _1099_ (
    .C(clk_32f),
    .D(_0003_[7]),
    .Q(counter[7])
  );
  (* src = "prueba.v:15" *)
  DFF _1100_ (
    .C(clk_32f),
    .D(_0003_[8]),
    .Q(counter[8])
  );
  (* src = "prueba.v:15" *)
  DFF _1101_ (
    .C(clk_32f),
    .D(_0003_[9]),
    .Q(counter[9])
  );
  (* src = "prueba.v:15" *)
  DFF _1102_ (
    .C(clk_32f),
    .D(_0003_[10]),
    .Q(counter[10])
  );
  (* src = "prueba.v:15" *)
  DFF _1103_ (
    .C(clk_32f),
    .D(_0003_[11]),
    .Q(counter[11])
  );
  (* src = "prueba.v:15" *)
  DFF _1104_ (
    .C(clk_32f),
    .D(_0003_[12]),
    .Q(counter[12])
  );
  (* src = "prueba.v:15" *)
  DFF _1105_ (
    .C(clk_32f),
    .D(_0003_[13]),
    .Q(counter[13])
  );
  (* src = "prueba.v:15" *)
  DFF _1106_ (
    .C(clk_32f),
    .D(_0003_[14]),
    .Q(counter[14])
  );
  (* src = "prueba.v:15" *)
  DFF _1107_ (
    .C(clk_32f),
    .D(_0003_[15]),
    .Q(counter[15])
  );
  (* src = "prueba.v:15" *)
  DFF _1108_ (
    .C(clk_32f),
    .D(_0003_[16]),
    .Q(counter[16])
  );
  (* src = "prueba.v:15" *)
  DFF _1109_ (
    .C(clk_32f),
    .D(_0003_[17]),
    .Q(counter[17])
  );
  (* src = "prueba.v:15" *)
  DFF _1110_ (
    .C(clk_32f),
    .D(_0003_[18]),
    .Q(counter[18])
  );
  (* src = "prueba.v:15" *)
  DFF _1111_ (
    .C(clk_32f),
    .D(_0003_[19]),
    .Q(counter[19])
  );
  (* src = "prueba.v:15" *)
  DFF _1112_ (
    .C(clk_32f),
    .D(_0003_[20]),
    .Q(counter[20])
  );
  (* src = "prueba.v:15" *)
  DFF _1113_ (
    .C(clk_32f),
    .D(_0003_[21]),
    .Q(counter[21])
  );
  (* src = "prueba.v:15" *)
  DFF _1114_ (
    .C(clk_32f),
    .D(_0003_[22]),
    .Q(counter[22])
  );
  (* src = "prueba.v:15" *)
  DFF _1115_ (
    .C(clk_32f),
    .D(_0003_[23]),
    .Q(counter[23])
  );
  (* src = "prueba.v:15" *)
  DFF _1116_ (
    .C(clk_32f),
    .D(_0003_[24]),
    .Q(counter[24])
  );
  (* src = "prueba.v:15" *)
  DFF _1117_ (
    .C(clk_32f),
    .D(_0003_[25]),
    .Q(counter[25])
  );
  (* src = "prueba.v:15" *)
  DFF _1118_ (
    .C(clk_32f),
    .D(_0003_[26]),
    .Q(counter[26])
  );
  (* src = "prueba.v:15" *)
  DFF _1119_ (
    .C(clk_32f),
    .D(_0003_[27]),
    .Q(counter[27])
  );
  (* src = "prueba.v:15" *)
  DFF _1120_ (
    .C(clk_32f),
    .D(_0003_[28]),
    .Q(counter[28])
  );
  (* src = "prueba.v:15" *)
  DFF _1121_ (
    .C(clk_32f),
    .D(_0003_[29]),
    .Q(counter[29])
  );
  (* src = "prueba.v:15" *)
  DFF _1122_ (
    .C(clk_32f),
    .D(_0003_[30]),
    .Q(counter[30])
  );
  (* src = "prueba.v:15" *)
  DFF _1123_ (
    .C(clk_32f),
    .D(_0003_[31]),
    .Q(counter[31])
  );
endmodule
