/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "demux_striping_sintetizado.v:1" *)
module demux_striping_sintetizado(clk_2f, data_input, valid_in, reset, lane_0, lane_1, valid_out0, valid_out1);
  (* src = "demux_striping_sintetizado.v:13" *)
  wire [31:0] _000_;
  (* src = "demux_striping_sintetizado.v:13" *)
  wire [31:0] _001_;
  (* src = "demux_striping_sintetizado.v:13" *)
  wire _002_;
  (* src = "demux_striping_sintetizado.v:13" *)
  wire _003_;
  (* src = "demux_striping_sintetizado.v:13" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  (* src = "demux_striping_sintetizado.v:2" *)
  input clk_2f;
  (* src = "demux_striping_sintetizado.v:3" *)
  input [31:0] data_input;
  (* src = "demux_striping_sintetizado.v:6" *)
  output [31:0] lane_0;
  (* src = "demux_striping_sintetizado.v:7" *)
  output [31:0] lane_1;
  (* src = "demux_striping_sintetizado.v:5" *)
  input reset;
  (* src = "demux_striping_sintetizado.v:11" *)
  wire sel;
  (* src = "demux_striping_sintetizado.v:4" *)
  input valid_in;
  (* src = "demux_striping_sintetizado.v:8" *)
  output valid_out0;
  (* src = "demux_striping_sintetizado.v:9" *)
  output valid_out1;
  NOT _143_ (
    .A(valid_in),
    .Y(_005_)
  );
  NOT _144_ (
    .A(sel),
    .Y(_006_)
  );
  NOT _145_ (
    .A(reset),
    .Y(_007_)
  );
  NOR _146_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  NOT _147_ (
    .A(_008_),
    .Y(_002_)
  );
  NOR _148_ (
    .A(_005_),
    .B(_002_),
    .Y(_009_)
  );
  NAND _149_ (
    .A(valid_in),
    .B(_008_),
    .Y(_010_)
  );
  NAND _150_ (
    .A(data_input[4]),
    .B(_009_),
    .Y(_011_)
  );
  NAND _151_ (
    .A(lane_1[4]),
    .B(_010_),
    .Y(_012_)
  );
  NAND _152_ (
    .A(_011_),
    .B(_012_),
    .Y(_001_[4])
  );
  NAND _153_ (
    .A(data_input[5]),
    .B(_009_),
    .Y(_013_)
  );
  NAND _154_ (
    .A(lane_1[5]),
    .B(_010_),
    .Y(_014_)
  );
  NAND _155_ (
    .A(_013_),
    .B(_014_),
    .Y(_001_[5])
  );
  NAND _156_ (
    .A(data_input[6]),
    .B(_009_),
    .Y(_015_)
  );
  NAND _157_ (
    .A(lane_1[6]),
    .B(_010_),
    .Y(_016_)
  );
  NAND _158_ (
    .A(_015_),
    .B(_016_),
    .Y(_001_[6])
  );
  NAND _159_ (
    .A(data_input[7]),
    .B(_009_),
    .Y(_017_)
  );
  NAND _160_ (
    .A(lane_1[7]),
    .B(_010_),
    .Y(_018_)
  );
  NAND _161_ (
    .A(_017_),
    .B(_018_),
    .Y(_001_[7])
  );
  NAND _162_ (
    .A(data_input[8]),
    .B(_009_),
    .Y(_019_)
  );
  NAND _163_ (
    .A(lane_1[8]),
    .B(_010_),
    .Y(_020_)
  );
  NAND _164_ (
    .A(_019_),
    .B(_020_),
    .Y(_001_[8])
  );
  NAND _165_ (
    .A(data_input[9]),
    .B(_009_),
    .Y(_021_)
  );
  NAND _166_ (
    .A(lane_1[9]),
    .B(_010_),
    .Y(_022_)
  );
  NAND _167_ (
    .A(_021_),
    .B(_022_),
    .Y(_001_[9])
  );
  NAND _168_ (
    .A(data_input[10]),
    .B(_009_),
    .Y(_023_)
  );
  NAND _169_ (
    .A(lane_1[10]),
    .B(_010_),
    .Y(_024_)
  );
  NAND _170_ (
    .A(_023_),
    .B(_024_),
    .Y(_001_[10])
  );
  NAND _171_ (
    .A(data_input[11]),
    .B(_009_),
    .Y(_025_)
  );
  NAND _172_ (
    .A(lane_1[11]),
    .B(_010_),
    .Y(_026_)
  );
  NAND _173_ (
    .A(_025_),
    .B(_026_),
    .Y(_001_[11])
  );
  NAND _174_ (
    .A(data_input[12]),
    .B(_009_),
    .Y(_027_)
  );
  NAND _175_ (
    .A(lane_1[12]),
    .B(_010_),
    .Y(_028_)
  );
  NAND _176_ (
    .A(_027_),
    .B(_028_),
    .Y(_001_[12])
  );
  NAND _177_ (
    .A(data_input[13]),
    .B(_009_),
    .Y(_029_)
  );
  NAND _178_ (
    .A(lane_1[13]),
    .B(_010_),
    .Y(_030_)
  );
  NAND _179_ (
    .A(_029_),
    .B(_030_),
    .Y(_001_[13])
  );
  NAND _180_ (
    .A(data_input[14]),
    .B(_009_),
    .Y(_031_)
  );
  NAND _181_ (
    .A(lane_1[14]),
    .B(_010_),
    .Y(_032_)
  );
  NAND _182_ (
    .A(_031_),
    .B(_032_),
    .Y(_001_[14])
  );
  NAND _183_ (
    .A(data_input[15]),
    .B(_009_),
    .Y(_033_)
  );
  NAND _184_ (
    .A(lane_1[15]),
    .B(_010_),
    .Y(_034_)
  );
  NAND _185_ (
    .A(_033_),
    .B(_034_),
    .Y(_001_[15])
  );
  NAND _186_ (
    .A(data_input[16]),
    .B(_009_),
    .Y(_035_)
  );
  NAND _187_ (
    .A(lane_1[16]),
    .B(_010_),
    .Y(_036_)
  );
  NAND _188_ (
    .A(_035_),
    .B(_036_),
    .Y(_001_[16])
  );
  NAND _189_ (
    .A(data_input[17]),
    .B(_009_),
    .Y(_037_)
  );
  NAND _190_ (
    .A(lane_1[17]),
    .B(_010_),
    .Y(_038_)
  );
  NAND _191_ (
    .A(_037_),
    .B(_038_),
    .Y(_001_[17])
  );
  NAND _192_ (
    .A(data_input[18]),
    .B(_009_),
    .Y(_039_)
  );
  NAND _193_ (
    .A(lane_1[18]),
    .B(_010_),
    .Y(_040_)
  );
  NAND _194_ (
    .A(_039_),
    .B(_040_),
    .Y(_001_[18])
  );
  NAND _195_ (
    .A(data_input[19]),
    .B(_009_),
    .Y(_041_)
  );
  NAND _196_ (
    .A(lane_1[19]),
    .B(_010_),
    .Y(_042_)
  );
  NAND _197_ (
    .A(_041_),
    .B(_042_),
    .Y(_001_[19])
  );
  NAND _198_ (
    .A(data_input[20]),
    .B(_009_),
    .Y(_043_)
  );
  NAND _199_ (
    .A(lane_1[20]),
    .B(_010_),
    .Y(_044_)
  );
  NAND _200_ (
    .A(_043_),
    .B(_044_),
    .Y(_001_[20])
  );
  NAND _201_ (
    .A(data_input[21]),
    .B(_009_),
    .Y(_045_)
  );
  NAND _202_ (
    .A(lane_1[21]),
    .B(_010_),
    .Y(_046_)
  );
  NAND _203_ (
    .A(_045_),
    .B(_046_),
    .Y(_001_[21])
  );
  NAND _204_ (
    .A(data_input[22]),
    .B(_009_),
    .Y(_047_)
  );
  NAND _205_ (
    .A(lane_1[22]),
    .B(_010_),
    .Y(_048_)
  );
  NAND _206_ (
    .A(_047_),
    .B(_048_),
    .Y(_001_[22])
  );
  NAND _207_ (
    .A(data_input[23]),
    .B(_009_),
    .Y(_049_)
  );
  NAND _208_ (
    .A(lane_1[23]),
    .B(_010_),
    .Y(_050_)
  );
  NAND _209_ (
    .A(_049_),
    .B(_050_),
    .Y(_001_[23])
  );
  NAND _210_ (
    .A(data_input[24]),
    .B(_009_),
    .Y(_051_)
  );
  NAND _211_ (
    .A(lane_1[24]),
    .B(_010_),
    .Y(_052_)
  );
  NAND _212_ (
    .A(_051_),
    .B(_052_),
    .Y(_001_[24])
  );
  NAND _213_ (
    .A(data_input[25]),
    .B(_009_),
    .Y(_053_)
  );
  NAND _214_ (
    .A(lane_1[25]),
    .B(_010_),
    .Y(_054_)
  );
  NAND _215_ (
    .A(_053_),
    .B(_054_),
    .Y(_001_[25])
  );
  NAND _216_ (
    .A(data_input[26]),
    .B(_009_),
    .Y(_055_)
  );
  NAND _217_ (
    .A(lane_1[26]),
    .B(_010_),
    .Y(_056_)
  );
  NAND _218_ (
    .A(_055_),
    .B(_056_),
    .Y(_001_[26])
  );
  NAND _219_ (
    .A(data_input[27]),
    .B(_009_),
    .Y(_057_)
  );
  NAND _220_ (
    .A(lane_1[27]),
    .B(_010_),
    .Y(_058_)
  );
  NAND _221_ (
    .A(_057_),
    .B(_058_),
    .Y(_001_[27])
  );
  NAND _222_ (
    .A(data_input[28]),
    .B(_009_),
    .Y(_059_)
  );
  NAND _223_ (
    .A(lane_1[28]),
    .B(_010_),
    .Y(_060_)
  );
  NAND _224_ (
    .A(_059_),
    .B(_060_),
    .Y(_001_[28])
  );
  NAND _225_ (
    .A(data_input[29]),
    .B(_009_),
    .Y(_061_)
  );
  NAND _226_ (
    .A(lane_1[29]),
    .B(_010_),
    .Y(_062_)
  );
  NAND _227_ (
    .A(_061_),
    .B(_062_),
    .Y(_001_[29])
  );
  NAND _228_ (
    .A(data_input[30]),
    .B(_009_),
    .Y(_063_)
  );
  NAND _229_ (
    .A(lane_1[30]),
    .B(_010_),
    .Y(_064_)
  );
  NAND _230_ (
    .A(_063_),
    .B(_064_),
    .Y(_001_[30])
  );
  NAND _231_ (
    .A(data_input[31]),
    .B(_009_),
    .Y(_065_)
  );
  NAND _232_ (
    .A(lane_1[31]),
    .B(_010_),
    .Y(_066_)
  );
  NAND _233_ (
    .A(_065_),
    .B(_066_),
    .Y(_001_[31])
  );
  NAND _234_ (
    .A(valid_out1),
    .B(_002_),
    .Y(_067_)
  );
  NAND _235_ (
    .A(_010_),
    .B(_067_),
    .Y(_004_)
  );
  NOR _236_ (
    .A(_005_),
    .B(_008_),
    .Y(_068_)
  );
  NAND _237_ (
    .A(valid_in),
    .B(_002_),
    .Y(_069_)
  );
  NAND _238_ (
    .A(data_input[0]),
    .B(_068_),
    .Y(_070_)
  );
  NAND _239_ (
    .A(lane_0[0]),
    .B(_069_),
    .Y(_071_)
  );
  NAND _240_ (
    .A(_070_),
    .B(_071_),
    .Y(_000_[0])
  );
  NAND _241_ (
    .A(data_input[1]),
    .B(_068_),
    .Y(_072_)
  );
  NAND _242_ (
    .A(lane_0[1]),
    .B(_069_),
    .Y(_073_)
  );
  NAND _243_ (
    .A(_072_),
    .B(_073_),
    .Y(_000_[1])
  );
  NAND _244_ (
    .A(data_input[2]),
    .B(_068_),
    .Y(_074_)
  );
  NAND _245_ (
    .A(lane_0[2]),
    .B(_069_),
    .Y(_075_)
  );
  NAND _246_ (
    .A(_074_),
    .B(_075_),
    .Y(_000_[2])
  );
  NAND _247_ (
    .A(data_input[3]),
    .B(_068_),
    .Y(_076_)
  );
  NAND _248_ (
    .A(lane_0[3]),
    .B(_069_),
    .Y(_077_)
  );
  NAND _249_ (
    .A(_076_),
    .B(_077_),
    .Y(_000_[3])
  );
  NAND _250_ (
    .A(data_input[4]),
    .B(_068_),
    .Y(_078_)
  );
  NAND _251_ (
    .A(lane_0[4]),
    .B(_069_),
    .Y(_079_)
  );
  NAND _252_ (
    .A(_078_),
    .B(_079_),
    .Y(_000_[4])
  );
  NAND _253_ (
    .A(data_input[5]),
    .B(_068_),
    .Y(_080_)
  );
  NAND _254_ (
    .A(lane_0[5]),
    .B(_069_),
    .Y(_081_)
  );
  NAND _255_ (
    .A(_080_),
    .B(_081_),
    .Y(_000_[5])
  );
  NAND _256_ (
    .A(data_input[6]),
    .B(_068_),
    .Y(_082_)
  );
  NAND _257_ (
    .A(lane_0[6]),
    .B(_069_),
    .Y(_083_)
  );
  NAND _258_ (
    .A(_082_),
    .B(_083_),
    .Y(_000_[6])
  );
  NAND _259_ (
    .A(data_input[7]),
    .B(_068_),
    .Y(_084_)
  );
  NAND _260_ (
    .A(lane_0[7]),
    .B(_069_),
    .Y(_085_)
  );
  NAND _261_ (
    .A(_084_),
    .B(_085_),
    .Y(_000_[7])
  );
  NAND _262_ (
    .A(data_input[8]),
    .B(_068_),
    .Y(_086_)
  );
  NAND _263_ (
    .A(lane_0[8]),
    .B(_069_),
    .Y(_087_)
  );
  NAND _264_ (
    .A(_086_),
    .B(_087_),
    .Y(_000_[8])
  );
  NAND _265_ (
    .A(data_input[9]),
    .B(_068_),
    .Y(_088_)
  );
  NAND _266_ (
    .A(lane_0[9]),
    .B(_069_),
    .Y(_089_)
  );
  NAND _267_ (
    .A(_088_),
    .B(_089_),
    .Y(_000_[9])
  );
  NAND _268_ (
    .A(data_input[10]),
    .B(_068_),
    .Y(_090_)
  );
  NAND _269_ (
    .A(lane_0[10]),
    .B(_069_),
    .Y(_091_)
  );
  NAND _270_ (
    .A(_090_),
    .B(_091_),
    .Y(_000_[10])
  );
  NAND _271_ (
    .A(data_input[11]),
    .B(_068_),
    .Y(_092_)
  );
  NAND _272_ (
    .A(lane_0[11]),
    .B(_069_),
    .Y(_093_)
  );
  NAND _273_ (
    .A(_092_),
    .B(_093_),
    .Y(_000_[11])
  );
  NAND _274_ (
    .A(data_input[12]),
    .B(_068_),
    .Y(_094_)
  );
  NAND _275_ (
    .A(lane_0[12]),
    .B(_069_),
    .Y(_095_)
  );
  NAND _276_ (
    .A(_094_),
    .B(_095_),
    .Y(_000_[12])
  );
  NAND _277_ (
    .A(data_input[13]),
    .B(_068_),
    .Y(_096_)
  );
  NAND _278_ (
    .A(lane_0[13]),
    .B(_069_),
    .Y(_097_)
  );
  NAND _279_ (
    .A(_096_),
    .B(_097_),
    .Y(_000_[13])
  );
  NAND _280_ (
    .A(data_input[14]),
    .B(_068_),
    .Y(_098_)
  );
  NAND _281_ (
    .A(lane_0[14]),
    .B(_069_),
    .Y(_099_)
  );
  NAND _282_ (
    .A(_098_),
    .B(_099_),
    .Y(_000_[14])
  );
  NAND _283_ (
    .A(data_input[15]),
    .B(_068_),
    .Y(_100_)
  );
  NAND _284_ (
    .A(lane_0[15]),
    .B(_069_),
    .Y(_101_)
  );
  NAND _285_ (
    .A(_100_),
    .B(_101_),
    .Y(_000_[15])
  );
  NAND _286_ (
    .A(data_input[16]),
    .B(_068_),
    .Y(_102_)
  );
  NAND _287_ (
    .A(lane_0[16]),
    .B(_069_),
    .Y(_103_)
  );
  NAND _288_ (
    .A(_102_),
    .B(_103_),
    .Y(_000_[16])
  );
  NAND _289_ (
    .A(data_input[17]),
    .B(_068_),
    .Y(_104_)
  );
  NAND _290_ (
    .A(lane_0[17]),
    .B(_069_),
    .Y(_105_)
  );
  NAND _291_ (
    .A(_104_),
    .B(_105_),
    .Y(_000_[17])
  );
  NAND _292_ (
    .A(data_input[18]),
    .B(_068_),
    .Y(_106_)
  );
  NAND _293_ (
    .A(lane_0[18]),
    .B(_069_),
    .Y(_107_)
  );
  NAND _294_ (
    .A(_106_),
    .B(_107_),
    .Y(_000_[18])
  );
  NAND _295_ (
    .A(data_input[19]),
    .B(_068_),
    .Y(_108_)
  );
  NAND _296_ (
    .A(lane_0[19]),
    .B(_069_),
    .Y(_109_)
  );
  NAND _297_ (
    .A(_108_),
    .B(_109_),
    .Y(_000_[19])
  );
  NAND _298_ (
    .A(data_input[20]),
    .B(_068_),
    .Y(_110_)
  );
  NAND _299_ (
    .A(lane_0[20]),
    .B(_069_),
    .Y(_111_)
  );
  NAND _300_ (
    .A(_110_),
    .B(_111_),
    .Y(_000_[20])
  );
  NAND _301_ (
    .A(data_input[21]),
    .B(_068_),
    .Y(_112_)
  );
  NAND _302_ (
    .A(lane_0[21]),
    .B(_069_),
    .Y(_113_)
  );
  NAND _303_ (
    .A(_112_),
    .B(_113_),
    .Y(_000_[21])
  );
  NAND _304_ (
    .A(data_input[22]),
    .B(_068_),
    .Y(_114_)
  );
  NAND _305_ (
    .A(lane_0[22]),
    .B(_069_),
    .Y(_115_)
  );
  NAND _306_ (
    .A(_114_),
    .B(_115_),
    .Y(_000_[22])
  );
  NAND _307_ (
    .A(data_input[23]),
    .B(_068_),
    .Y(_116_)
  );
  NAND _308_ (
    .A(lane_0[23]),
    .B(_069_),
    .Y(_117_)
  );
  NAND _309_ (
    .A(_116_),
    .B(_117_),
    .Y(_000_[23])
  );
  NAND _310_ (
    .A(data_input[24]),
    .B(_068_),
    .Y(_118_)
  );
  NAND _311_ (
    .A(lane_0[24]),
    .B(_069_),
    .Y(_119_)
  );
  NAND _312_ (
    .A(_118_),
    .B(_119_),
    .Y(_000_[24])
  );
  NAND _313_ (
    .A(data_input[25]),
    .B(_068_),
    .Y(_120_)
  );
  NAND _314_ (
    .A(lane_0[25]),
    .B(_069_),
    .Y(_121_)
  );
  NAND _315_ (
    .A(_120_),
    .B(_121_),
    .Y(_000_[25])
  );
  NAND _316_ (
    .A(data_input[26]),
    .B(_068_),
    .Y(_122_)
  );
  NAND _317_ (
    .A(lane_0[26]),
    .B(_069_),
    .Y(_123_)
  );
  NAND _318_ (
    .A(_122_),
    .B(_123_),
    .Y(_000_[26])
  );
  NAND _319_ (
    .A(data_input[27]),
    .B(_068_),
    .Y(_124_)
  );
  NAND _320_ (
    .A(lane_0[27]),
    .B(_069_),
    .Y(_125_)
  );
  NAND _321_ (
    .A(_124_),
    .B(_125_),
    .Y(_000_[27])
  );
  NAND _322_ (
    .A(data_input[28]),
    .B(_068_),
    .Y(_126_)
  );
  NAND _323_ (
    .A(lane_0[28]),
    .B(_069_),
    .Y(_127_)
  );
  NAND _324_ (
    .A(_126_),
    .B(_127_),
    .Y(_000_[28])
  );
  NAND _325_ (
    .A(data_input[29]),
    .B(_068_),
    .Y(_128_)
  );
  NAND _326_ (
    .A(lane_0[29]),
    .B(_069_),
    .Y(_129_)
  );
  NAND _327_ (
    .A(_128_),
    .B(_129_),
    .Y(_000_[29])
  );
  NAND _328_ (
    .A(data_input[30]),
    .B(_068_),
    .Y(_130_)
  );
  NAND _329_ (
    .A(lane_0[30]),
    .B(_069_),
    .Y(_131_)
  );
  NAND _330_ (
    .A(_130_),
    .B(_131_),
    .Y(_000_[30])
  );
  NAND _331_ (
    .A(data_input[31]),
    .B(_068_),
    .Y(_132_)
  );
  NAND _332_ (
    .A(lane_0[31]),
    .B(_069_),
    .Y(_133_)
  );
  NAND _333_ (
    .A(_132_),
    .B(_133_),
    .Y(_000_[31])
  );
  NAND _334_ (
    .A(valid_out0),
    .B(_008_),
    .Y(_134_)
  );
  NAND _335_ (
    .A(_069_),
    .B(_134_),
    .Y(_003_)
  );
  NAND _336_ (
    .A(data_input[0]),
    .B(_009_),
    .Y(_135_)
  );
  NAND _337_ (
    .A(lane_1[0]),
    .B(_010_),
    .Y(_136_)
  );
  NAND _338_ (
    .A(_135_),
    .B(_136_),
    .Y(_001_[0])
  );
  NAND _339_ (
    .A(data_input[1]),
    .B(_009_),
    .Y(_137_)
  );
  NAND _340_ (
    .A(lane_1[1]),
    .B(_010_),
    .Y(_138_)
  );
  NAND _341_ (
    .A(_137_),
    .B(_138_),
    .Y(_001_[1])
  );
  NAND _342_ (
    .A(data_input[2]),
    .B(_009_),
    .Y(_139_)
  );
  NAND _343_ (
    .A(lane_1[2]),
    .B(_010_),
    .Y(_140_)
  );
  NAND _344_ (
    .A(_139_),
    .B(_140_),
    .Y(_001_[2])
  );
  NAND _345_ (
    .A(data_input[3]),
    .B(_009_),
    .Y(_141_)
  );
  NAND _346_ (
    .A(lane_1[3]),
    .B(_010_),
    .Y(_142_)
  );
  NAND _347_ (
    .A(_141_),
    .B(_142_),
    .Y(_001_[3])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _348_ (
    .C(clk_2f),
    .D(_003_),
    .Q(valid_out0)
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _349_ (
    .C(clk_2f),
    .D(_004_),
    .Q(valid_out1)
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _350_ (
    .C(clk_2f),
    .D(_002_),
    .Q(sel)
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _351_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(lane_0[0])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _352_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(lane_0[1])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _353_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(lane_0[2])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _354_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(lane_0[3])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _355_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(lane_0[4])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _356_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(lane_0[5])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _357_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(lane_0[6])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _358_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(lane_0[7])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _359_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(lane_0[8])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _360_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(lane_0[9])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _361_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(lane_0[10])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _362_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(lane_0[11])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _363_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(lane_0[12])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _364_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(lane_0[13])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _365_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(lane_0[14])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _366_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(lane_0[15])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _367_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(lane_0[16])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _368_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(lane_0[17])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _369_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(lane_0[18])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _370_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(lane_0[19])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _371_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(lane_0[20])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _372_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(lane_0[21])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _373_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(lane_0[22])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _374_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(lane_0[23])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _375_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(lane_0[24])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _376_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(lane_0[25])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _377_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(lane_0[26])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _378_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(lane_0[27])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _379_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(lane_0[28])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _380_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(lane_0[29])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _381_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(lane_0[30])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _382_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(lane_0[31])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _383_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(lane_1[0])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _384_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(lane_1[1])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _385_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(lane_1[2])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _386_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(lane_1[3])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _387_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(lane_1[4])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _388_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(lane_1[5])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _389_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(lane_1[6])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _390_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(lane_1[7])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _391_ (
    .C(clk_2f),
    .D(_001_[8]),
    .Q(lane_1[8])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _392_ (
    .C(clk_2f),
    .D(_001_[9]),
    .Q(lane_1[9])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _393_ (
    .C(clk_2f),
    .D(_001_[10]),
    .Q(lane_1[10])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _394_ (
    .C(clk_2f),
    .D(_001_[11]),
    .Q(lane_1[11])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _395_ (
    .C(clk_2f),
    .D(_001_[12]),
    .Q(lane_1[12])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _396_ (
    .C(clk_2f),
    .D(_001_[13]),
    .Q(lane_1[13])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _397_ (
    .C(clk_2f),
    .D(_001_[14]),
    .Q(lane_1[14])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _398_ (
    .C(clk_2f),
    .D(_001_[15]),
    .Q(lane_1[15])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _399_ (
    .C(clk_2f),
    .D(_001_[16]),
    .Q(lane_1[16])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _400_ (
    .C(clk_2f),
    .D(_001_[17]),
    .Q(lane_1[17])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _401_ (
    .C(clk_2f),
    .D(_001_[18]),
    .Q(lane_1[18])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _402_ (
    .C(clk_2f),
    .D(_001_[19]),
    .Q(lane_1[19])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _403_ (
    .C(clk_2f),
    .D(_001_[20]),
    .Q(lane_1[20])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _404_ (
    .C(clk_2f),
    .D(_001_[21]),
    .Q(lane_1[21])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _405_ (
    .C(clk_2f),
    .D(_001_[22]),
    .Q(lane_1[22])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _406_ (
    .C(clk_2f),
    .D(_001_[23]),
    .Q(lane_1[23])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _407_ (
    .C(clk_2f),
    .D(_001_[24]),
    .Q(lane_1[24])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _408_ (
    .C(clk_2f),
    .D(_001_[25]),
    .Q(lane_1[25])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _409_ (
    .C(clk_2f),
    .D(_001_[26]),
    .Q(lane_1[26])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _410_ (
    .C(clk_2f),
    .D(_001_[27]),
    .Q(lane_1[27])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _411_ (
    .C(clk_2f),
    .D(_001_[28]),
    .Q(lane_1[28])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _412_ (
    .C(clk_2f),
    .D(_001_[29]),
    .Q(lane_1[29])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _413_ (
    .C(clk_2f),
    .D(_001_[30]),
    .Q(lane_1[30])
  );
  (* src = "demux_striping_sintetizado.v:13" *)
  DFF _414_ (
    .C(clk_2f),
    .D(_001_[31]),
    .Q(lane_1[31])
  );
endmodule
