/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:1" *)
module demux_32_8_sintetizado(clk_4f, data_in, valid, reset, data_out, valid_out);
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  wire [7:0] _000_;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  wire [1:0] _001_;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:1" *)
  input clk_4f;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:2" *)
  input [31:0] data_in;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:5" *)
  output [7:0] data_out;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:4" *)
  input reset;
  (* init = 2'h0 *)
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:8" *)
  wire [1:0] selector;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:3" *)
  input valid;
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:6" *)
  output valid_out;
  NOT _098_ (
    .A(selector[0]),
    .Y(_060_)
  );
  NOT _099_ (
    .A(selector[1]),
    .Y(_061_)
  );
  NOT _100_ (
    .A(data_in[0]),
    .Y(_062_)
  );
  NOT _101_ (
    .A(data_in[2]),
    .Y(_063_)
  );
  NOT _102_ (
    .A(data_in[3]),
    .Y(_064_)
  );
  NOT _103_ (
    .A(data_in[4]),
    .Y(_065_)
  );
  NOT _104_ (
    .A(data_in[5]),
    .Y(_066_)
  );
  NOT _105_ (
    .A(data_in[7]),
    .Y(_067_)
  );
  NOT _106_ (
    .A(data_in[9]),
    .Y(_068_)
  );
  NAND _107_ (
    .A(valid),
    .B(reset),
    .Y(_069_)
  );
  NOT _108_ (
    .A(_069_),
    .Y(_002_)
  );
  NOR _109_ (
    .A(selector[0]),
    .B(_069_),
    .Y(_001_[0])
  );
  NAND _110_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_070_)
  );
  NOT _111_ (
    .A(_070_),
    .Y(_071_)
  );
  NAND _112_ (
    .A(_060_),
    .B(_061_),
    .Y(_072_)
  );
  NAND _113_ (
    .A(_002_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _114_ (
    .A(_071_),
    .B(_073_),
    .Y(_001_[1])
  );
  NOR _115_ (
    .A(_069_),
    .B(_072_),
    .Y(_074_)
  );
  NAND _116_ (
    .A(data_in[24]),
    .B(_074_),
    .Y(_075_)
  );
  NOR _117_ (
    .A(selector[0]),
    .B(_061_),
    .Y(_076_)
  );
  NAND _118_ (
    .A(data_in[8]),
    .B(_076_),
    .Y(_077_)
  );
  NOR _119_ (
    .A(_062_),
    .B(_070_),
    .Y(_078_)
  );
  NAND _120_ (
    .A(selector[0]),
    .B(_061_),
    .Y(_079_)
  );
  NOR _121_ (
    .A(selector[0]),
    .B(data_out[0]),
    .Y(_080_)
  );
  NOR _122_ (
    .A(selector[1]),
    .B(_080_),
    .Y(_081_)
  );
  NOR _123_ (
    .A(_078_),
    .B(_081_),
    .Y(_082_)
  );
  NAND _124_ (
    .A(_077_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _125_ (
    .A(data_in[16]),
    .B(_079_),
    .Y(_084_)
  );
  NOR _126_ (
    .A(_073_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _127_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _128_ (
    .A(_075_),
    .B(_086_),
    .Y(_000_[0])
  );
  NOR _129_ (
    .A(data_in[1]),
    .B(_070_),
    .Y(_087_)
  );
  NOR _130_ (
    .A(_069_),
    .B(_087_),
    .Y(_088_)
  );
  NOT _131_ (
    .A(_088_),
    .Y(_089_)
  );
  NAND _132_ (
    .A(_068_),
    .B(_076_),
    .Y(_090_)
  );
  NOR _133_ (
    .A(data_in[25]),
    .B(_072_),
    .Y(_091_)
  );
  NOR _134_ (
    .A(data_in[17]),
    .B(_079_),
    .Y(_092_)
  );
  NOR _135_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _136_ (
    .A(_090_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _137_ (
    .A(_089_),
    .B(_094_),
    .Y(_000_[1])
  );
  NAND _138_ (
    .A(data_in[26]),
    .B(_074_),
    .Y(_095_)
  );
  NAND _139_ (
    .A(data_in[10]),
    .B(_076_),
    .Y(_096_)
  );
  NOR _140_ (
    .A(_063_),
    .B(_070_),
    .Y(_097_)
  );
  NOR _141_ (
    .A(selector[0]),
    .B(data_out[2]),
    .Y(_003_)
  );
  NOR _142_ (
    .A(selector[1]),
    .B(_003_),
    .Y(_004_)
  );
  NOR _143_ (
    .A(_097_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _144_ (
    .A(_096_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _145_ (
    .A(selector[1]),
    .B(data_in[18]),
    .Y(_007_)
  );
  NOR _146_ (
    .A(_073_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _147_ (
    .A(_006_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _148_ (
    .A(_095_),
    .B(_009_),
    .Y(_000_[2])
  );
  NAND _149_ (
    .A(data_in[27]),
    .B(_074_),
    .Y(_010_)
  );
  NAND _150_ (
    .A(data_in[11]),
    .B(_076_),
    .Y(_011_)
  );
  NOR _151_ (
    .A(_064_),
    .B(_070_),
    .Y(_012_)
  );
  NOR _152_ (
    .A(selector[0]),
    .B(data_out[3]),
    .Y(_013_)
  );
  NOR _153_ (
    .A(selector[1]),
    .B(_013_),
    .Y(_014_)
  );
  NOR _154_ (
    .A(_012_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _155_ (
    .A(_011_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _156_ (
    .A(selector[1]),
    .B(data_in[19]),
    .Y(_017_)
  );
  NOR _157_ (
    .A(_073_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _158_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _159_ (
    .A(_010_),
    .B(_019_),
    .Y(_000_[3])
  );
  NAND _160_ (
    .A(data_in[28]),
    .B(_074_),
    .Y(_020_)
  );
  NAND _161_ (
    .A(data_in[12]),
    .B(_076_),
    .Y(_021_)
  );
  NOR _162_ (
    .A(selector[0]),
    .B(data_out[4]),
    .Y(_022_)
  );
  NOR _163_ (
    .A(selector[1]),
    .B(_022_),
    .Y(_023_)
  );
  NOR _164_ (
    .A(_065_),
    .B(_070_),
    .Y(_024_)
  );
  NOR _165_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _166_ (
    .A(_021_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _167_ (
    .A(selector[1]),
    .B(data_in[20]),
    .Y(_027_)
  );
  NOR _168_ (
    .A(_073_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _169_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _170_ (
    .A(_020_),
    .B(_029_),
    .Y(_000_[4])
  );
  NAND _171_ (
    .A(data_in[29]),
    .B(_074_),
    .Y(_030_)
  );
  NAND _172_ (
    .A(data_in[13]),
    .B(_076_),
    .Y(_031_)
  );
  NOR _173_ (
    .A(selector[0]),
    .B(data_out[5]),
    .Y(_032_)
  );
  NOR _174_ (
    .A(selector[1]),
    .B(_032_),
    .Y(_033_)
  );
  NOR _175_ (
    .A(_066_),
    .B(_070_),
    .Y(_034_)
  );
  NOR _176_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _177_ (
    .A(_031_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _178_ (
    .A(selector[1]),
    .B(data_in[21]),
    .Y(_037_)
  );
  NOR _179_ (
    .A(_073_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _180_ (
    .A(_036_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _181_ (
    .A(_030_),
    .B(_039_),
    .Y(_000_[5])
  );
  NAND _182_ (
    .A(data_in[14]),
    .B(_076_),
    .Y(_040_)
  );
  NOT _183_ (
    .A(_040_),
    .Y(_041_)
  );
  NAND _184_ (
    .A(data_in[6]),
    .B(_071_),
    .Y(_042_)
  );
  NAND _185_ (
    .A(selector[1]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _186_ (
    .A(_041_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _187_ (
    .A(data_in[30]),
    .B(_002_),
    .Y(_045_)
  );
  NAND _188_ (
    .A(_073_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _189_ (
    .A(data_in[22]),
    .B(_079_),
    .Y(_047_)
  );
  NOT _190_ (
    .A(_047_),
    .Y(_048_)
  );
  NAND _191_ (
    .A(_046_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _192_ (
    .A(_044_),
    .B(_049_),
    .Y(_000_[6])
  );
  NAND _193_ (
    .A(data_in[31]),
    .B(_074_),
    .Y(_050_)
  );
  NOR _194_ (
    .A(selector[0]),
    .B(data_out[7]),
    .Y(_051_)
  );
  NOR _195_ (
    .A(selector[1]),
    .B(_051_),
    .Y(_052_)
  );
  NOR _196_ (
    .A(_067_),
    .B(_070_),
    .Y(_053_)
  );
  NAND _197_ (
    .A(data_in[15]),
    .B(_076_),
    .Y(_054_)
  );
  NOR _198_ (
    .A(_052_),
    .B(_053_),
    .Y(_055_)
  );
  NAND _199_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _200_ (
    .A(selector[1]),
    .B(data_in[23]),
    .Y(_057_)
  );
  NOR _201_ (
    .A(_073_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _202_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _203_ (
    .A(_050_),
    .B(_059_),
    .Y(_000_[7])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _204_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_out)
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _205_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _206_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _207_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _208_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _209_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _210_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _211_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _212_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _213_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(selector[0])
  );
  (* src = "../demux_32_8_sintetizado/demux_32_8_sintetizado.v:10" *)
  DFF _214_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(selector[1])
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:1" *)
module demux_striping_sintetizado(clk_2f, data_input, valid_in, reset, lane_0, lane_1, valid_out0, valid_out1);
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  wire [31:0] _000_;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  wire [31:0] _001_;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  wire _002_;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  wire _003_;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:2" *)
  input clk_2f;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:3" *)
  input [31:0] data_input;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:6" *)
  output [31:0] lane_0;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:7" *)
  output [31:0] lane_1;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:5" *)
  input reset;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:11" *)
  wire sel;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:4" *)
  input valid_in;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:8" *)
  output valid_out0;
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:9" *)
  output valid_out1;
  NOT _239_ (
    .A(valid_in),
    .Y(_005_)
  );
  NOT _240_ (
    .A(sel),
    .Y(_006_)
  );
  NOT _241_ (
    .A(reset),
    .Y(_007_)
  );
  NOT _242_ (
    .A(data_input[0]),
    .Y(_008_)
  );
  NOT _243_ (
    .A(data_input[1]),
    .Y(_009_)
  );
  NOT _244_ (
    .A(data_input[2]),
    .Y(_010_)
  );
  NOT _245_ (
    .A(data_input[3]),
    .Y(_011_)
  );
  NOT _246_ (
    .A(data_input[4]),
    .Y(_012_)
  );
  NOT _247_ (
    .A(data_input[5]),
    .Y(_013_)
  );
  NOT _248_ (
    .A(data_input[6]),
    .Y(_014_)
  );
  NOT _249_ (
    .A(data_input[7]),
    .Y(_015_)
  );
  NOT _250_ (
    .A(data_input[8]),
    .Y(_016_)
  );
  NOT _251_ (
    .A(data_input[9]),
    .Y(_017_)
  );
  NOT _252_ (
    .A(data_input[10]),
    .Y(_018_)
  );
  NOT _253_ (
    .A(data_input[11]),
    .Y(_019_)
  );
  NOT _254_ (
    .A(data_input[12]),
    .Y(_020_)
  );
  NOT _255_ (
    .A(data_input[13]),
    .Y(_021_)
  );
  NOT _256_ (
    .A(data_input[14]),
    .Y(_022_)
  );
  NOT _257_ (
    .A(data_input[15]),
    .Y(_023_)
  );
  NOT _258_ (
    .A(data_input[16]),
    .Y(_024_)
  );
  NOT _259_ (
    .A(data_input[17]),
    .Y(_025_)
  );
  NOT _260_ (
    .A(data_input[18]),
    .Y(_026_)
  );
  NOT _261_ (
    .A(data_input[19]),
    .Y(_027_)
  );
  NOT _262_ (
    .A(data_input[20]),
    .Y(_028_)
  );
  NOT _263_ (
    .A(data_input[21]),
    .Y(_029_)
  );
  NOT _264_ (
    .A(data_input[22]),
    .Y(_030_)
  );
  NOT _265_ (
    .A(data_input[23]),
    .Y(_031_)
  );
  NOT _266_ (
    .A(data_input[24]),
    .Y(_032_)
  );
  NOT _267_ (
    .A(data_input[25]),
    .Y(_033_)
  );
  NOT _268_ (
    .A(data_input[26]),
    .Y(_034_)
  );
  NOT _269_ (
    .A(data_input[27]),
    .Y(_035_)
  );
  NOT _270_ (
    .A(data_input[28]),
    .Y(_036_)
  );
  NOT _271_ (
    .A(data_input[29]),
    .Y(_037_)
  );
  NOT _272_ (
    .A(data_input[30]),
    .Y(_038_)
  );
  NOT _273_ (
    .A(data_input[31]),
    .Y(_039_)
  );
  NOR _274_ (
    .A(_005_),
    .B(sel),
    .Y(_040_)
  );
  NAND _275_ (
    .A(sel),
    .B(valid_out0),
    .Y(_041_)
  );
  NOT _276_ (
    .A(_041_),
    .Y(_042_)
  );
  NOR _277_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _278_ (
    .A(_007_),
    .B(_043_),
    .Y(_003_)
  );
  NOR _279_ (
    .A(lane_0[0]),
    .B(_040_),
    .Y(_044_)
  );
  NAND _280_ (
    .A(_008_),
    .B(_040_),
    .Y(_045_)
  );
  NAND _281_ (
    .A(reset),
    .B(_045_),
    .Y(_046_)
  );
  NOR _282_ (
    .A(_044_),
    .B(_046_),
    .Y(_000_[0])
  );
  NOR _283_ (
    .A(lane_0[1]),
    .B(_040_),
    .Y(_047_)
  );
  NAND _284_ (
    .A(_009_),
    .B(_040_),
    .Y(_048_)
  );
  NAND _285_ (
    .A(reset),
    .B(_048_),
    .Y(_049_)
  );
  NOR _286_ (
    .A(_047_),
    .B(_049_),
    .Y(_000_[1])
  );
  NOR _287_ (
    .A(lane_0[2]),
    .B(_040_),
    .Y(_050_)
  );
  NAND _288_ (
    .A(_010_),
    .B(_040_),
    .Y(_051_)
  );
  NAND _289_ (
    .A(reset),
    .B(_051_),
    .Y(_052_)
  );
  NOR _290_ (
    .A(_050_),
    .B(_052_),
    .Y(_000_[2])
  );
  NOR _291_ (
    .A(lane_0[3]),
    .B(_040_),
    .Y(_053_)
  );
  NAND _292_ (
    .A(_011_),
    .B(_040_),
    .Y(_054_)
  );
  NAND _293_ (
    .A(reset),
    .B(_054_),
    .Y(_055_)
  );
  NOR _294_ (
    .A(_053_),
    .B(_055_),
    .Y(_000_[3])
  );
  NOR _295_ (
    .A(lane_0[4]),
    .B(_040_),
    .Y(_056_)
  );
  NAND _296_ (
    .A(_012_),
    .B(_040_),
    .Y(_057_)
  );
  NAND _297_ (
    .A(reset),
    .B(_057_),
    .Y(_058_)
  );
  NOR _298_ (
    .A(_056_),
    .B(_058_),
    .Y(_000_[4])
  );
  NOR _299_ (
    .A(lane_0[5]),
    .B(_040_),
    .Y(_059_)
  );
  NAND _300_ (
    .A(_013_),
    .B(_040_),
    .Y(_060_)
  );
  NAND _301_ (
    .A(reset),
    .B(_060_),
    .Y(_061_)
  );
  NOR _302_ (
    .A(_059_),
    .B(_061_),
    .Y(_000_[5])
  );
  NOR _303_ (
    .A(lane_0[6]),
    .B(_040_),
    .Y(_062_)
  );
  NAND _304_ (
    .A(_014_),
    .B(_040_),
    .Y(_063_)
  );
  NAND _305_ (
    .A(reset),
    .B(_063_),
    .Y(_064_)
  );
  NOR _306_ (
    .A(_062_),
    .B(_064_),
    .Y(_000_[6])
  );
  NOR _307_ (
    .A(lane_0[7]),
    .B(_040_),
    .Y(_065_)
  );
  NAND _308_ (
    .A(_015_),
    .B(_040_),
    .Y(_066_)
  );
  NAND _309_ (
    .A(reset),
    .B(_066_),
    .Y(_067_)
  );
  NOR _310_ (
    .A(_065_),
    .B(_067_),
    .Y(_000_[7])
  );
  NOR _311_ (
    .A(lane_0[8]),
    .B(_040_),
    .Y(_068_)
  );
  NAND _312_ (
    .A(_016_),
    .B(_040_),
    .Y(_069_)
  );
  NAND _313_ (
    .A(reset),
    .B(_069_),
    .Y(_070_)
  );
  NOR _314_ (
    .A(_068_),
    .B(_070_),
    .Y(_000_[8])
  );
  NOR _315_ (
    .A(lane_0[9]),
    .B(_040_),
    .Y(_071_)
  );
  NAND _316_ (
    .A(_017_),
    .B(_040_),
    .Y(_072_)
  );
  NAND _317_ (
    .A(reset),
    .B(_072_),
    .Y(_073_)
  );
  NOR _318_ (
    .A(_071_),
    .B(_073_),
    .Y(_000_[9])
  );
  NOR _319_ (
    .A(lane_0[10]),
    .B(_040_),
    .Y(_074_)
  );
  NAND _320_ (
    .A(_018_),
    .B(_040_),
    .Y(_075_)
  );
  NAND _321_ (
    .A(reset),
    .B(_075_),
    .Y(_076_)
  );
  NOR _322_ (
    .A(_074_),
    .B(_076_),
    .Y(_000_[10])
  );
  NOR _323_ (
    .A(lane_0[11]),
    .B(_040_),
    .Y(_077_)
  );
  NAND _324_ (
    .A(_019_),
    .B(_040_),
    .Y(_078_)
  );
  NAND _325_ (
    .A(reset),
    .B(_078_),
    .Y(_079_)
  );
  NOR _326_ (
    .A(_077_),
    .B(_079_),
    .Y(_000_[11])
  );
  NOR _327_ (
    .A(lane_0[12]),
    .B(_040_),
    .Y(_080_)
  );
  NAND _328_ (
    .A(_020_),
    .B(_040_),
    .Y(_081_)
  );
  NAND _329_ (
    .A(reset),
    .B(_081_),
    .Y(_082_)
  );
  NOR _330_ (
    .A(_080_),
    .B(_082_),
    .Y(_000_[12])
  );
  NOR _331_ (
    .A(lane_0[13]),
    .B(_040_),
    .Y(_083_)
  );
  NAND _332_ (
    .A(_021_),
    .B(_040_),
    .Y(_084_)
  );
  NAND _333_ (
    .A(reset),
    .B(_084_),
    .Y(_085_)
  );
  NOR _334_ (
    .A(_083_),
    .B(_085_),
    .Y(_000_[13])
  );
  NOR _335_ (
    .A(lane_0[14]),
    .B(_040_),
    .Y(_086_)
  );
  NAND _336_ (
    .A(_022_),
    .B(_040_),
    .Y(_087_)
  );
  NAND _337_ (
    .A(reset),
    .B(_087_),
    .Y(_088_)
  );
  NOR _338_ (
    .A(_086_),
    .B(_088_),
    .Y(_000_[14])
  );
  NOR _339_ (
    .A(lane_0[15]),
    .B(_040_),
    .Y(_089_)
  );
  NAND _340_ (
    .A(_023_),
    .B(_040_),
    .Y(_090_)
  );
  NAND _341_ (
    .A(reset),
    .B(_090_),
    .Y(_091_)
  );
  NOR _342_ (
    .A(_089_),
    .B(_091_),
    .Y(_000_[15])
  );
  NOR _343_ (
    .A(lane_0[16]),
    .B(_040_),
    .Y(_092_)
  );
  NAND _344_ (
    .A(_024_),
    .B(_040_),
    .Y(_093_)
  );
  NAND _345_ (
    .A(reset),
    .B(_093_),
    .Y(_094_)
  );
  NOR _346_ (
    .A(_092_),
    .B(_094_),
    .Y(_000_[16])
  );
  NOR _347_ (
    .A(lane_0[17]),
    .B(_040_),
    .Y(_095_)
  );
  NAND _348_ (
    .A(_025_),
    .B(_040_),
    .Y(_096_)
  );
  NAND _349_ (
    .A(reset),
    .B(_096_),
    .Y(_097_)
  );
  NOR _350_ (
    .A(_095_),
    .B(_097_),
    .Y(_000_[17])
  );
  NOR _351_ (
    .A(lane_0[18]),
    .B(_040_),
    .Y(_098_)
  );
  NAND _352_ (
    .A(_026_),
    .B(_040_),
    .Y(_099_)
  );
  NAND _353_ (
    .A(reset),
    .B(_099_),
    .Y(_100_)
  );
  NOR _354_ (
    .A(_098_),
    .B(_100_),
    .Y(_000_[18])
  );
  NOR _355_ (
    .A(lane_0[19]),
    .B(_040_),
    .Y(_101_)
  );
  NAND _356_ (
    .A(_027_),
    .B(_040_),
    .Y(_102_)
  );
  NAND _357_ (
    .A(reset),
    .B(_102_),
    .Y(_103_)
  );
  NOR _358_ (
    .A(_101_),
    .B(_103_),
    .Y(_000_[19])
  );
  NOR _359_ (
    .A(lane_0[20]),
    .B(_040_),
    .Y(_104_)
  );
  NAND _360_ (
    .A(_028_),
    .B(_040_),
    .Y(_105_)
  );
  NAND _361_ (
    .A(reset),
    .B(_105_),
    .Y(_106_)
  );
  NOR _362_ (
    .A(_104_),
    .B(_106_),
    .Y(_000_[20])
  );
  NOR _363_ (
    .A(lane_0[21]),
    .B(_040_),
    .Y(_107_)
  );
  NAND _364_ (
    .A(_029_),
    .B(_040_),
    .Y(_108_)
  );
  NAND _365_ (
    .A(reset),
    .B(_108_),
    .Y(_109_)
  );
  NOR _366_ (
    .A(_107_),
    .B(_109_),
    .Y(_000_[21])
  );
  NOR _367_ (
    .A(lane_0[22]),
    .B(_040_),
    .Y(_110_)
  );
  NAND _368_ (
    .A(_030_),
    .B(_040_),
    .Y(_111_)
  );
  NAND _369_ (
    .A(reset),
    .B(_111_),
    .Y(_112_)
  );
  NOR _370_ (
    .A(_110_),
    .B(_112_),
    .Y(_000_[22])
  );
  NOR _371_ (
    .A(lane_0[23]),
    .B(_040_),
    .Y(_113_)
  );
  NAND _372_ (
    .A(_031_),
    .B(_040_),
    .Y(_114_)
  );
  NAND _373_ (
    .A(reset),
    .B(_114_),
    .Y(_115_)
  );
  NOR _374_ (
    .A(_113_),
    .B(_115_),
    .Y(_000_[23])
  );
  NOR _375_ (
    .A(lane_0[24]),
    .B(_040_),
    .Y(_116_)
  );
  NAND _376_ (
    .A(_032_),
    .B(_040_),
    .Y(_117_)
  );
  NAND _377_ (
    .A(reset),
    .B(_117_),
    .Y(_118_)
  );
  NOR _378_ (
    .A(_116_),
    .B(_118_),
    .Y(_000_[24])
  );
  NOR _379_ (
    .A(lane_0[25]),
    .B(_040_),
    .Y(_119_)
  );
  NAND _380_ (
    .A(_033_),
    .B(_040_),
    .Y(_120_)
  );
  NAND _381_ (
    .A(reset),
    .B(_120_),
    .Y(_121_)
  );
  NOR _382_ (
    .A(_119_),
    .B(_121_),
    .Y(_000_[25])
  );
  NOR _383_ (
    .A(lane_0[26]),
    .B(_040_),
    .Y(_122_)
  );
  NAND _384_ (
    .A(_034_),
    .B(_040_),
    .Y(_123_)
  );
  NAND _385_ (
    .A(reset),
    .B(_123_),
    .Y(_124_)
  );
  NOR _386_ (
    .A(_122_),
    .B(_124_),
    .Y(_000_[26])
  );
  NOR _387_ (
    .A(lane_0[27]),
    .B(_040_),
    .Y(_125_)
  );
  NAND _388_ (
    .A(_035_),
    .B(_040_),
    .Y(_126_)
  );
  NAND _389_ (
    .A(reset),
    .B(_126_),
    .Y(_127_)
  );
  NOR _390_ (
    .A(_125_),
    .B(_127_),
    .Y(_000_[27])
  );
  NOR _391_ (
    .A(lane_0[28]),
    .B(_040_),
    .Y(_128_)
  );
  NAND _392_ (
    .A(_036_),
    .B(_040_),
    .Y(_129_)
  );
  NAND _393_ (
    .A(reset),
    .B(_129_),
    .Y(_130_)
  );
  NOR _394_ (
    .A(_128_),
    .B(_130_),
    .Y(_000_[28])
  );
  NOR _395_ (
    .A(lane_0[29]),
    .B(_040_),
    .Y(_131_)
  );
  NAND _396_ (
    .A(_037_),
    .B(_040_),
    .Y(_132_)
  );
  NAND _397_ (
    .A(reset),
    .B(_132_),
    .Y(_133_)
  );
  NOR _398_ (
    .A(_131_),
    .B(_133_),
    .Y(_000_[29])
  );
  NOR _399_ (
    .A(lane_0[30]),
    .B(_040_),
    .Y(_134_)
  );
  NAND _400_ (
    .A(_038_),
    .B(_040_),
    .Y(_135_)
  );
  NAND _401_ (
    .A(reset),
    .B(_135_),
    .Y(_136_)
  );
  NOR _402_ (
    .A(_134_),
    .B(_136_),
    .Y(_000_[30])
  );
  NOR _403_ (
    .A(lane_0[31]),
    .B(_040_),
    .Y(_137_)
  );
  NAND _404_ (
    .A(_039_),
    .B(_040_),
    .Y(_138_)
  );
  NAND _405_ (
    .A(reset),
    .B(_138_),
    .Y(_139_)
  );
  NOR _406_ (
    .A(_137_),
    .B(_139_),
    .Y(_000_[31])
  );
  NOR _407_ (
    .A(sel),
    .B(_007_),
    .Y(_002_)
  );
  NOR _408_ (
    .A(_005_),
    .B(_006_),
    .Y(_140_)
  );
  NAND _409_ (
    .A(reset),
    .B(_140_),
    .Y(_141_)
  );
  NAND _410_ (
    .A(valid_out1),
    .B(_002_),
    .Y(_142_)
  );
  NAND _411_ (
    .A(_141_),
    .B(_142_),
    .Y(_004_)
  );
  NAND _412_ (
    .A(_008_),
    .B(_140_),
    .Y(_143_)
  );
  NAND _413_ (
    .A(reset),
    .B(_143_),
    .Y(_144_)
  );
  NOR _414_ (
    .A(lane_1[0]),
    .B(_140_),
    .Y(_145_)
  );
  NOR _415_ (
    .A(_144_),
    .B(_145_),
    .Y(_001_[0])
  );
  NAND _416_ (
    .A(_009_),
    .B(_140_),
    .Y(_146_)
  );
  NAND _417_ (
    .A(reset),
    .B(_146_),
    .Y(_147_)
  );
  NOR _418_ (
    .A(lane_1[1]),
    .B(_140_),
    .Y(_148_)
  );
  NOR _419_ (
    .A(_147_),
    .B(_148_),
    .Y(_001_[1])
  );
  NAND _420_ (
    .A(_010_),
    .B(_140_),
    .Y(_149_)
  );
  NAND _421_ (
    .A(reset),
    .B(_149_),
    .Y(_150_)
  );
  NOR _422_ (
    .A(lane_1[2]),
    .B(_140_),
    .Y(_151_)
  );
  NOR _423_ (
    .A(_150_),
    .B(_151_),
    .Y(_001_[2])
  );
  NAND _424_ (
    .A(_011_),
    .B(_140_),
    .Y(_152_)
  );
  NAND _425_ (
    .A(reset),
    .B(_152_),
    .Y(_153_)
  );
  NOR _426_ (
    .A(lane_1[3]),
    .B(_140_),
    .Y(_154_)
  );
  NOR _427_ (
    .A(_153_),
    .B(_154_),
    .Y(_001_[3])
  );
  NAND _428_ (
    .A(_012_),
    .B(_140_),
    .Y(_155_)
  );
  NAND _429_ (
    .A(reset),
    .B(_155_),
    .Y(_156_)
  );
  NOR _430_ (
    .A(lane_1[4]),
    .B(_140_),
    .Y(_157_)
  );
  NOR _431_ (
    .A(_156_),
    .B(_157_),
    .Y(_001_[4])
  );
  NAND _432_ (
    .A(_013_),
    .B(_140_),
    .Y(_158_)
  );
  NAND _433_ (
    .A(reset),
    .B(_158_),
    .Y(_159_)
  );
  NOR _434_ (
    .A(lane_1[5]),
    .B(_140_),
    .Y(_160_)
  );
  NOR _435_ (
    .A(_159_),
    .B(_160_),
    .Y(_001_[5])
  );
  NAND _436_ (
    .A(_014_),
    .B(_140_),
    .Y(_161_)
  );
  NAND _437_ (
    .A(reset),
    .B(_161_),
    .Y(_162_)
  );
  NOR _438_ (
    .A(lane_1[6]),
    .B(_140_),
    .Y(_163_)
  );
  NOR _439_ (
    .A(_162_),
    .B(_163_),
    .Y(_001_[6])
  );
  NAND _440_ (
    .A(_015_),
    .B(_140_),
    .Y(_164_)
  );
  NAND _441_ (
    .A(reset),
    .B(_164_),
    .Y(_165_)
  );
  NOR _442_ (
    .A(lane_1[7]),
    .B(_140_),
    .Y(_166_)
  );
  NOR _443_ (
    .A(_165_),
    .B(_166_),
    .Y(_001_[7])
  );
  NAND _444_ (
    .A(_016_),
    .B(_140_),
    .Y(_167_)
  );
  NAND _445_ (
    .A(reset),
    .B(_167_),
    .Y(_168_)
  );
  NOR _446_ (
    .A(lane_1[8]),
    .B(_140_),
    .Y(_169_)
  );
  NOR _447_ (
    .A(_168_),
    .B(_169_),
    .Y(_001_[8])
  );
  NAND _448_ (
    .A(_017_),
    .B(_140_),
    .Y(_170_)
  );
  NAND _449_ (
    .A(reset),
    .B(_170_),
    .Y(_171_)
  );
  NOR _450_ (
    .A(lane_1[9]),
    .B(_140_),
    .Y(_172_)
  );
  NOR _451_ (
    .A(_171_),
    .B(_172_),
    .Y(_001_[9])
  );
  NAND _452_ (
    .A(_018_),
    .B(_140_),
    .Y(_173_)
  );
  NAND _453_ (
    .A(reset),
    .B(_173_),
    .Y(_174_)
  );
  NOR _454_ (
    .A(lane_1[10]),
    .B(_140_),
    .Y(_175_)
  );
  NOR _455_ (
    .A(_174_),
    .B(_175_),
    .Y(_001_[10])
  );
  NAND _456_ (
    .A(_019_),
    .B(_140_),
    .Y(_176_)
  );
  NAND _457_ (
    .A(reset),
    .B(_176_),
    .Y(_177_)
  );
  NOR _458_ (
    .A(lane_1[11]),
    .B(_140_),
    .Y(_178_)
  );
  NOR _459_ (
    .A(_177_),
    .B(_178_),
    .Y(_001_[11])
  );
  NAND _460_ (
    .A(_020_),
    .B(_140_),
    .Y(_179_)
  );
  NAND _461_ (
    .A(reset),
    .B(_179_),
    .Y(_180_)
  );
  NOR _462_ (
    .A(lane_1[12]),
    .B(_140_),
    .Y(_181_)
  );
  NOR _463_ (
    .A(_180_),
    .B(_181_),
    .Y(_001_[12])
  );
  NAND _464_ (
    .A(_021_),
    .B(_140_),
    .Y(_182_)
  );
  NAND _465_ (
    .A(reset),
    .B(_182_),
    .Y(_183_)
  );
  NOR _466_ (
    .A(lane_1[13]),
    .B(_140_),
    .Y(_184_)
  );
  NOR _467_ (
    .A(_183_),
    .B(_184_),
    .Y(_001_[13])
  );
  NAND _468_ (
    .A(_022_),
    .B(_140_),
    .Y(_185_)
  );
  NAND _469_ (
    .A(reset),
    .B(_185_),
    .Y(_186_)
  );
  NOR _470_ (
    .A(lane_1[14]),
    .B(_140_),
    .Y(_187_)
  );
  NOR _471_ (
    .A(_186_),
    .B(_187_),
    .Y(_001_[14])
  );
  NAND _472_ (
    .A(_023_),
    .B(_140_),
    .Y(_188_)
  );
  NAND _473_ (
    .A(reset),
    .B(_188_),
    .Y(_189_)
  );
  NOR _474_ (
    .A(lane_1[15]),
    .B(_140_),
    .Y(_190_)
  );
  NOR _475_ (
    .A(_189_),
    .B(_190_),
    .Y(_001_[15])
  );
  NAND _476_ (
    .A(_024_),
    .B(_140_),
    .Y(_191_)
  );
  NAND _477_ (
    .A(reset),
    .B(_191_),
    .Y(_192_)
  );
  NOR _478_ (
    .A(lane_1[16]),
    .B(_140_),
    .Y(_193_)
  );
  NOR _479_ (
    .A(_192_),
    .B(_193_),
    .Y(_001_[16])
  );
  NAND _480_ (
    .A(_025_),
    .B(_140_),
    .Y(_194_)
  );
  NAND _481_ (
    .A(reset),
    .B(_194_),
    .Y(_195_)
  );
  NOR _482_ (
    .A(lane_1[17]),
    .B(_140_),
    .Y(_196_)
  );
  NOR _483_ (
    .A(_195_),
    .B(_196_),
    .Y(_001_[17])
  );
  NAND _484_ (
    .A(_026_),
    .B(_140_),
    .Y(_197_)
  );
  NAND _485_ (
    .A(reset),
    .B(_197_),
    .Y(_198_)
  );
  NOR _486_ (
    .A(lane_1[18]),
    .B(_140_),
    .Y(_199_)
  );
  NOR _487_ (
    .A(_198_),
    .B(_199_),
    .Y(_001_[18])
  );
  NAND _488_ (
    .A(_027_),
    .B(_140_),
    .Y(_200_)
  );
  NAND _489_ (
    .A(reset),
    .B(_200_),
    .Y(_201_)
  );
  NOR _490_ (
    .A(lane_1[19]),
    .B(_140_),
    .Y(_202_)
  );
  NOR _491_ (
    .A(_201_),
    .B(_202_),
    .Y(_001_[19])
  );
  NAND _492_ (
    .A(_028_),
    .B(_140_),
    .Y(_203_)
  );
  NAND _493_ (
    .A(reset),
    .B(_203_),
    .Y(_204_)
  );
  NOR _494_ (
    .A(lane_1[20]),
    .B(_140_),
    .Y(_205_)
  );
  NOR _495_ (
    .A(_204_),
    .B(_205_),
    .Y(_001_[20])
  );
  NAND _496_ (
    .A(_029_),
    .B(_140_),
    .Y(_206_)
  );
  NAND _497_ (
    .A(reset),
    .B(_206_),
    .Y(_207_)
  );
  NOR _498_ (
    .A(lane_1[21]),
    .B(_140_),
    .Y(_208_)
  );
  NOR _499_ (
    .A(_207_),
    .B(_208_),
    .Y(_001_[21])
  );
  NAND _500_ (
    .A(_030_),
    .B(_140_),
    .Y(_209_)
  );
  NAND _501_ (
    .A(reset),
    .B(_209_),
    .Y(_210_)
  );
  NOR _502_ (
    .A(lane_1[22]),
    .B(_140_),
    .Y(_211_)
  );
  NOR _503_ (
    .A(_210_),
    .B(_211_),
    .Y(_001_[22])
  );
  NAND _504_ (
    .A(_031_),
    .B(_140_),
    .Y(_212_)
  );
  NAND _505_ (
    .A(reset),
    .B(_212_),
    .Y(_213_)
  );
  NOR _506_ (
    .A(lane_1[23]),
    .B(_140_),
    .Y(_214_)
  );
  NOR _507_ (
    .A(_213_),
    .B(_214_),
    .Y(_001_[23])
  );
  NAND _508_ (
    .A(_032_),
    .B(_140_),
    .Y(_215_)
  );
  NAND _509_ (
    .A(reset),
    .B(_215_),
    .Y(_216_)
  );
  NOR _510_ (
    .A(lane_1[24]),
    .B(_140_),
    .Y(_217_)
  );
  NOR _511_ (
    .A(_216_),
    .B(_217_),
    .Y(_001_[24])
  );
  NAND _512_ (
    .A(_033_),
    .B(_140_),
    .Y(_218_)
  );
  NAND _513_ (
    .A(reset),
    .B(_218_),
    .Y(_219_)
  );
  NOR _514_ (
    .A(lane_1[25]),
    .B(_140_),
    .Y(_220_)
  );
  NOR _515_ (
    .A(_219_),
    .B(_220_),
    .Y(_001_[25])
  );
  NAND _516_ (
    .A(_034_),
    .B(_140_),
    .Y(_221_)
  );
  NAND _517_ (
    .A(reset),
    .B(_221_),
    .Y(_222_)
  );
  NOR _518_ (
    .A(lane_1[26]),
    .B(_140_),
    .Y(_223_)
  );
  NOR _519_ (
    .A(_222_),
    .B(_223_),
    .Y(_001_[26])
  );
  NAND _520_ (
    .A(_035_),
    .B(_140_),
    .Y(_224_)
  );
  NAND _521_ (
    .A(reset),
    .B(_224_),
    .Y(_225_)
  );
  NOR _522_ (
    .A(lane_1[27]),
    .B(_140_),
    .Y(_226_)
  );
  NOR _523_ (
    .A(_225_),
    .B(_226_),
    .Y(_001_[27])
  );
  NAND _524_ (
    .A(_036_),
    .B(_140_),
    .Y(_227_)
  );
  NAND _525_ (
    .A(reset),
    .B(_227_),
    .Y(_228_)
  );
  NOR _526_ (
    .A(lane_1[28]),
    .B(_140_),
    .Y(_229_)
  );
  NOR _527_ (
    .A(_228_),
    .B(_229_),
    .Y(_001_[28])
  );
  NAND _528_ (
    .A(_037_),
    .B(_140_),
    .Y(_230_)
  );
  NAND _529_ (
    .A(reset),
    .B(_230_),
    .Y(_231_)
  );
  NOR _530_ (
    .A(lane_1[29]),
    .B(_140_),
    .Y(_232_)
  );
  NOR _531_ (
    .A(_231_),
    .B(_232_),
    .Y(_001_[29])
  );
  NAND _532_ (
    .A(_038_),
    .B(_140_),
    .Y(_233_)
  );
  NAND _533_ (
    .A(reset),
    .B(_233_),
    .Y(_234_)
  );
  NOR _534_ (
    .A(lane_1[30]),
    .B(_140_),
    .Y(_235_)
  );
  NOR _535_ (
    .A(_234_),
    .B(_235_),
    .Y(_001_[30])
  );
  NAND _536_ (
    .A(_039_),
    .B(_140_),
    .Y(_236_)
  );
  NAND _537_ (
    .A(reset),
    .B(_236_),
    .Y(_237_)
  );
  NOR _538_ (
    .A(lane_1[31]),
    .B(_140_),
    .Y(_238_)
  );
  NOR _539_ (
    .A(_237_),
    .B(_238_),
    .Y(_001_[31])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _540_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(lane_1[0])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _541_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(lane_1[1])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _542_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(lane_1[2])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _543_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(lane_1[3])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _544_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(lane_1[4])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _545_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(lane_1[5])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _546_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(lane_1[6])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _547_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(lane_1[7])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _548_ (
    .C(clk_2f),
    .D(_001_[8]),
    .Q(lane_1[8])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _549_ (
    .C(clk_2f),
    .D(_001_[9]),
    .Q(lane_1[9])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _550_ (
    .C(clk_2f),
    .D(_001_[10]),
    .Q(lane_1[10])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _551_ (
    .C(clk_2f),
    .D(_001_[11]),
    .Q(lane_1[11])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _552_ (
    .C(clk_2f),
    .D(_001_[12]),
    .Q(lane_1[12])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _553_ (
    .C(clk_2f),
    .D(_001_[13]),
    .Q(lane_1[13])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _554_ (
    .C(clk_2f),
    .D(_001_[14]),
    .Q(lane_1[14])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _555_ (
    .C(clk_2f),
    .D(_001_[15]),
    .Q(lane_1[15])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _556_ (
    .C(clk_2f),
    .D(_001_[16]),
    .Q(lane_1[16])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _557_ (
    .C(clk_2f),
    .D(_001_[17]),
    .Q(lane_1[17])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _558_ (
    .C(clk_2f),
    .D(_001_[18]),
    .Q(lane_1[18])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _559_ (
    .C(clk_2f),
    .D(_001_[19]),
    .Q(lane_1[19])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _560_ (
    .C(clk_2f),
    .D(_001_[20]),
    .Q(lane_1[20])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _561_ (
    .C(clk_2f),
    .D(_001_[21]),
    .Q(lane_1[21])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _562_ (
    .C(clk_2f),
    .D(_001_[22]),
    .Q(lane_1[22])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _563_ (
    .C(clk_2f),
    .D(_001_[23]),
    .Q(lane_1[23])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _564_ (
    .C(clk_2f),
    .D(_001_[24]),
    .Q(lane_1[24])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _565_ (
    .C(clk_2f),
    .D(_001_[25]),
    .Q(lane_1[25])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _566_ (
    .C(clk_2f),
    .D(_001_[26]),
    .Q(lane_1[26])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _567_ (
    .C(clk_2f),
    .D(_001_[27]),
    .Q(lane_1[27])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _568_ (
    .C(clk_2f),
    .D(_001_[28]),
    .Q(lane_1[28])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _569_ (
    .C(clk_2f),
    .D(_001_[29]),
    .Q(lane_1[29])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _570_ (
    .C(clk_2f),
    .D(_001_[30]),
    .Q(lane_1[30])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _571_ (
    .C(clk_2f),
    .D(_001_[31]),
    .Q(lane_1[31])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _572_ (
    .C(clk_2f),
    .D(_004_),
    .Q(valid_out1)
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _573_ (
    .C(clk_2f),
    .D(_002_),
    .Q(sel)
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _574_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(lane_0[0])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _575_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(lane_0[1])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _576_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(lane_0[2])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _577_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(lane_0[3])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _578_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(lane_0[4])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _579_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(lane_0[5])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _580_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(lane_0[6])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _581_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(lane_0[7])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _582_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(lane_0[8])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _583_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(lane_0[9])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _584_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(lane_0[10])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _585_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(lane_0[11])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _586_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(lane_0[12])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _587_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(lane_0[13])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _588_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(lane_0[14])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _589_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(lane_0[15])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _590_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(lane_0[16])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _591_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(lane_0[17])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _592_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(lane_0[18])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _593_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(lane_0[19])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _594_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(lane_0[20])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _595_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(lane_0[21])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _596_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(lane_0[22])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _597_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(lane_0[23])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _598_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(lane_0[24])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _599_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(lane_0[25])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _600_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(lane_0[26])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _601_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(lane_0[27])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _602_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(lane_0[28])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _603_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(lane_0[29])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _604_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(lane_0[30])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _605_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(lane_0[31])
  );
  (* src = "../demux_striping_sintetizado/demux_striping_sintetizado.v:13" *)
  DFF _606_ (
    .C(clk_2f),
    .D(_003_),
    .Q(valid_out0)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:1" *)
module paralelo_serial_sintetizado(clk_4f, clk_32f, data_in, valid_in, reset, data_out);
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  wire _000_;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  wire [2:0] _001_;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  wire [2:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:2" *)
  input clk_32f;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:1" *)
  input clk_4f;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:3" *)
  input [7:0] data_in;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:6" *)
  output data_out;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:5" *)
  input reset;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:8" *)
  wire [2:0] selector;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:9" *)
  wire [2:0] selector_2;
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:4" *)
  input valid_in;
  NOT _051_ (
    .A(selector_2[0]),
    .Y(_003_)
  );
  NOT _052_ (
    .A(selector_2[1]),
    .Y(_004_)
  );
  NOT _053_ (
    .A(selector_2[2]),
    .Y(_005_)
  );
  NOT _054_ (
    .A(valid_in),
    .Y(_006_)
  );
  NOT _055_ (
    .A(data_in[7]),
    .Y(_007_)
  );
  NAND _056_ (
    .A(_006_),
    .B(reset),
    .Y(_008_)
  );
  NAND _057_ (
    .A(selector[2]),
    .B(selector[1]),
    .Y(_009_)
  );
  NOT _058_ (
    .A(_009_),
    .Y(_010_)
  );
  NOR _059_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _060_ (
    .A(selector[2]),
    .B(selector[1]),
    .Y(_012_)
  );
  NAND _061_ (
    .A(selector[0]),
    .B(_012_),
    .Y(_013_)
  );
  NAND _062_ (
    .A(_011_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _063_ (
    .A(selector_2[0]),
    .B(_004_),
    .Y(_015_)
  );
  NAND _064_ (
    .A(data_in[5]),
    .B(_015_),
    .Y(_016_)
  );
  NOR _065_ (
    .A(_003_),
    .B(selector_2[1]),
    .Y(_017_)
  );
  NAND _066_ (
    .A(data_in[6]),
    .B(_017_),
    .Y(_018_)
  );
  NOR _067_ (
    .A(_003_),
    .B(_004_),
    .Y(_019_)
  );
  NAND _068_ (
    .A(selector_2[0]),
    .B(selector_2[1]),
    .Y(_020_)
  );
  NAND _069_ (
    .A(data_in[4]),
    .B(_019_),
    .Y(_021_)
  );
  NOR _070_ (
    .A(selector_2[0]),
    .B(selector_2[1]),
    .Y(_022_)
  );
  NOT _071_ (
    .A(_022_),
    .Y(_023_)
  );
  NOR _072_ (
    .A(_007_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _073_ (
    .A(_018_),
    .B(_021_),
    .Y(_025_)
  );
  NOR _074_ (
    .A(selector_2[2]),
    .B(_024_),
    .Y(_026_)
  );
  NAND _075_ (
    .A(_016_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _076_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _077_ (
    .A(data_in[3]),
    .B(_022_),
    .Y(_029_)
  );
  NAND _078_ (
    .A(selector_2[2]),
    .B(_029_),
    .Y(_030_)
  );
  NAND _079_ (
    .A(data_in[1]),
    .B(_015_),
    .Y(_031_)
  );
  NAND _080_ (
    .A(data_in[2]),
    .B(_017_),
    .Y(_032_)
  );
  NAND _081_ (
    .A(data_in[0]),
    .B(_019_),
    .Y(_033_)
  );
  NAND _082_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _083_ (
    .A(_030_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _084_ (
    .A(_031_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _085_ (
    .A(valid_in),
    .B(reset),
    .Y(_037_)
  );
  NOR _086_ (
    .A(_028_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _087_ (
    .A(_036_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _088_ (
    .A(_014_),
    .B(_039_),
    .Y(_000_)
  );
  NOR _089_ (
    .A(selector[0]),
    .B(_008_),
    .Y(_001_[0])
  );
  NAND _090_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_040_)
  );
  NOT _091_ (
    .A(_040_),
    .Y(_041_)
  );
  NOR _092_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_042_)
  );
  NOR _093_ (
    .A(_008_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _094_ (
    .A(_040_),
    .B(_043_),
    .Y(_044_)
  );
  NOT _095_ (
    .A(_044_),
    .Y(_001_[1])
  );
  NOR _096_ (
    .A(selector[2]),
    .B(_041_),
    .Y(_045_)
  );
  NOR _097_ (
    .A(_011_),
    .B(_001_[0]),
    .Y(_046_)
  );
  NOR _098_ (
    .A(_045_),
    .B(_046_),
    .Y(_001_[2])
  );
  NOR _099_ (
    .A(selector_2[0]),
    .B(_037_),
    .Y(_002_[0])
  );
  NAND _100_ (
    .A(_020_),
    .B(_023_),
    .Y(_047_)
  );
  NOR _101_ (
    .A(_037_),
    .B(_047_),
    .Y(_002_[1])
  );
  NAND _102_ (
    .A(selector_2[2]),
    .B(_019_),
    .Y(_048_)
  );
  NAND _103_ (
    .A(_005_),
    .B(_020_),
    .Y(_049_)
  );
  NAND _104_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _105_ (
    .A(_037_),
    .B(_050_),
    .Y(_002_[2])
  );
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  DFF _106_ (
    .C(clk_32f),
    .D(_000_),
    .Q(data_out)
  );
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  DFF _107_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(selector[0])
  );
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  DFF _108_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(selector[1])
  );
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  DFF _109_ (
    .C(clk_32f),
    .D(_001_[2]),
    .Q(selector[2])
  );
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  DFF _110_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(selector_2[0])
  );
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  DFF _111_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(selector_2[1])
  );
  (* src = "../paralelo_serial_sintetizado/paralelo_serial_sintetizado.v:11" *)
  DFF _112_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(selector_2[2])
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "phy_TX_sintetizado.v:7" *)
module phy_TX_sintetizado(data_input, valid, active, reset, clk_2f, clk_f, clk_4f, clk_32f, data_out_ps0_sintetizado, data_out_ps1_sintetizado);
  (* src = "phy_TX_sintetizado.v:9" *)
  input active;
  (* src = "phy_TX_sintetizado.v:11" *)
  input clk_2f;
  (* src = "phy_TX_sintetizado.v:14" *)
  input clk_32f;
  (* src = "phy_TX_sintetizado.v:13" *)
  input clk_4f;
  (* src = "phy_TX_sintetizado.v:12" *)
  input clk_f;
  (* src = "phy_TX_sintetizado.v:7" *)
  input [31:0] data_input;
  (* src = "phy_TX_sintetizado.v:15" *)
  output data_out_ps0_sintetizado;
  (* src = "phy_TX_sintetizado.v:16" *)
  output data_out_ps1_sintetizado;
  (* src = "phy_TX_sintetizado.v:20" *)
  wire [7:0] demux0_paraleloserial;
  (* src = "phy_TX_sintetizado.v:20" *)
  wire [7:0] demux1_paraleloserial;
  (* src = "phy_TX_sintetizado.v:19" *)
  wire [31:0] demux_0;
  (* src = "phy_TX_sintetizado.v:19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] demux_1_probador;
  (* src = "phy_TX_sintetizado.v:19" *)
  wire [31:0] lane_0;
  (* src = "phy_TX_sintetizado.v:19" *)
  wire [31:0] lane_1;
  (* src = "phy_TX_sintetizado.v:10" *)
  input reset;
  (* src = "phy_TX_sintetizado.v:8" *)
  input valid;
  (* src = "phy_TX_sintetizado.v:22" *)
  wire valid_demux_striping_sintetizado_0;
  (* src = "phy_TX_sintetizado.v:22" *)
  wire valid_demux_striping_sintetizado_1;
  (* src = "phy_TX_sintetizado.v:21" *)
  wire valid_out;
  (* src = "phy_TX_sintetizado.v:22" *)
  wire valid_out0;
  (* src = "phy_TX_sintetizado.v:22" *)
  wire valid_out1;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_TX_sintetizado.v:46" *)
  demux_32_8_sintetizado demux_lane_0 (
    .clk_4f(clk_4f),
    .data_in(lane_0),
    .data_out(demux0_paraleloserial),
    .reset(reset),
    .valid(valid_demux_striping_sintetizado_0),
    .valid_out(valid_out0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_TX_sintetizado.v:64" *)
  demux_32_8_sintetizado demux_lane_1 (
    .clk_4f(clk_4f),
    .data_in(lane_1),
    .data_out(demux1_paraleloserial),
    .reset(reset),
    .valid(valid_demux_striping_sintetizado_1),
    .valid_out(valid_out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_TX_sintetizado.v:55" *)
  paralelo_serial_sintetizado paralelo_serial_sintetizado0 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(demux0_paraleloserial),
    .data_out(data_out_ps0_sintetizado),
    .reset(reset),
    .valid_in(valid_out0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_TX_sintetizado.v:73" *)
  paralelo_serial_sintetizado paralelo_serial_sintetizado1 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(demux1_paraleloserial),
    .data_out(data_out_ps1_sintetizado),
    .reset(reset),
    .valid_in(valid_out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_TX_sintetizado.v:24" *)
  recirculador_sintetizado recirculador_sintetizado_inicial (
    .active(active),
    .clk_2f(clk_2f),
    .data_input(data_input),
    .demux_0(demux_0),
    .demux_1_probador(demux_1_probador),
    .reset(reset),
    .valid(valid),
    .valid_out(valid_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_TX_sintetizado.v:35" *)
  demux_striping_sintetizado u_demux_striping_sintetizado (
    .clk_2f(clk_2f),
    .data_input(demux_0),
    .lane_0(lane_0),
    .lane_1(lane_1),
    .reset(reset),
    .valid_in(valid_out),
    .valid_out0(valid_demux_striping_sintetizado_0),
    .valid_out1(valid_demux_striping_sintetizado_1)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "../recirculador_sintetizado/recirculador_sintetizado.v:1" *)
module recirculador_sintetizado(clk_2f, data_input, valid, active, reset, demux_0, demux_1_probador, valid_out);
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  wire [31:0] _000_;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  wire [31:0] _001_;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:4" *)
  input active;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:1" *)
  input clk_2f;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:2" *)
  input [31:0] data_input;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:6" *)
  output [31:0] demux_0;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:7" *)
  output [31:0] demux_1_probador;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:5" *)
  input reset;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:3" *)
  input valid;
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:8" *)
  output valid_out;
  NOT _200_ (
    .A(valid),
    .Y(_003_)
  );
  NOT _201_ (
    .A(active),
    .Y(_004_)
  );
  NOR _202_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _203_ (
    .A(valid),
    .B(active),
    .Y(_006_)
  );
  NOR _204_ (
    .A(demux_0[0]),
    .B(_005_),
    .Y(_007_)
  );
  NOR _205_ (
    .A(data_input[0]),
    .B(_006_),
    .Y(_008_)
  );
  NOT _206_ (
    .A(_008_),
    .Y(_009_)
  );
  NAND _207_ (
    .A(reset),
    .B(_009_),
    .Y(_010_)
  );
  NOR _208_ (
    .A(_007_),
    .B(_010_),
    .Y(_000_[0])
  );
  NOR _209_ (
    .A(demux_0[1]),
    .B(_005_),
    .Y(_011_)
  );
  NOR _210_ (
    .A(data_input[1]),
    .B(_006_),
    .Y(_012_)
  );
  NOT _211_ (
    .A(_012_),
    .Y(_013_)
  );
  NAND _212_ (
    .A(reset),
    .B(_013_),
    .Y(_014_)
  );
  NOR _213_ (
    .A(_011_),
    .B(_014_),
    .Y(_000_[1])
  );
  NOR _214_ (
    .A(demux_0[2]),
    .B(_005_),
    .Y(_015_)
  );
  NOR _215_ (
    .A(data_input[2]),
    .B(_006_),
    .Y(_016_)
  );
  NOT _216_ (
    .A(_016_),
    .Y(_017_)
  );
  NAND _217_ (
    .A(reset),
    .B(_017_),
    .Y(_018_)
  );
  NOR _218_ (
    .A(_015_),
    .B(_018_),
    .Y(_000_[2])
  );
  NOR _219_ (
    .A(demux_0[3]),
    .B(_005_),
    .Y(_019_)
  );
  NOR _220_ (
    .A(data_input[3]),
    .B(_006_),
    .Y(_020_)
  );
  NOT _221_ (
    .A(_020_),
    .Y(_021_)
  );
  NAND _222_ (
    .A(reset),
    .B(_021_),
    .Y(_022_)
  );
  NOR _223_ (
    .A(_019_),
    .B(_022_),
    .Y(_000_[3])
  );
  NOR _224_ (
    .A(demux_0[4]),
    .B(_005_),
    .Y(_023_)
  );
  NOR _225_ (
    .A(data_input[4]),
    .B(_006_),
    .Y(_024_)
  );
  NOT _226_ (
    .A(_024_),
    .Y(_025_)
  );
  NAND _227_ (
    .A(reset),
    .B(_025_),
    .Y(_026_)
  );
  NOR _228_ (
    .A(_023_),
    .B(_026_),
    .Y(_000_[4])
  );
  NOR _229_ (
    .A(demux_0[5]),
    .B(_005_),
    .Y(_027_)
  );
  NOR _230_ (
    .A(data_input[5]),
    .B(_006_),
    .Y(_028_)
  );
  NOT _231_ (
    .A(_028_),
    .Y(_029_)
  );
  NAND _232_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NOR _233_ (
    .A(_027_),
    .B(_030_),
    .Y(_000_[5])
  );
  NOR _234_ (
    .A(demux_0[6]),
    .B(_005_),
    .Y(_031_)
  );
  NOR _235_ (
    .A(data_input[6]),
    .B(_006_),
    .Y(_032_)
  );
  NOT _236_ (
    .A(_032_),
    .Y(_033_)
  );
  NAND _237_ (
    .A(reset),
    .B(_033_),
    .Y(_034_)
  );
  NOR _238_ (
    .A(_031_),
    .B(_034_),
    .Y(_000_[6])
  );
  NOR _239_ (
    .A(demux_0[7]),
    .B(_005_),
    .Y(_035_)
  );
  NOR _240_ (
    .A(data_input[7]),
    .B(_006_),
    .Y(_036_)
  );
  NOT _241_ (
    .A(_036_),
    .Y(_037_)
  );
  NAND _242_ (
    .A(reset),
    .B(_037_),
    .Y(_038_)
  );
  NOR _243_ (
    .A(_035_),
    .B(_038_),
    .Y(_000_[7])
  );
  NOR _244_ (
    .A(demux_0[8]),
    .B(_005_),
    .Y(_039_)
  );
  NOR _245_ (
    .A(data_input[8]),
    .B(_006_),
    .Y(_040_)
  );
  NOT _246_ (
    .A(_040_),
    .Y(_041_)
  );
  NAND _247_ (
    .A(reset),
    .B(_041_),
    .Y(_042_)
  );
  NOR _248_ (
    .A(_039_),
    .B(_042_),
    .Y(_000_[8])
  );
  NOR _249_ (
    .A(demux_0[9]),
    .B(_005_),
    .Y(_043_)
  );
  NOR _250_ (
    .A(data_input[9]),
    .B(_006_),
    .Y(_044_)
  );
  NOT _251_ (
    .A(_044_),
    .Y(_045_)
  );
  NAND _252_ (
    .A(reset),
    .B(_045_),
    .Y(_046_)
  );
  NOR _253_ (
    .A(_043_),
    .B(_046_),
    .Y(_000_[9])
  );
  NOR _254_ (
    .A(demux_0[10]),
    .B(_005_),
    .Y(_047_)
  );
  NOR _255_ (
    .A(data_input[10]),
    .B(_006_),
    .Y(_048_)
  );
  NOT _256_ (
    .A(_048_),
    .Y(_049_)
  );
  NAND _257_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _258_ (
    .A(_047_),
    .B(_050_),
    .Y(_000_[10])
  );
  NOR _259_ (
    .A(demux_0[11]),
    .B(_005_),
    .Y(_051_)
  );
  NOR _260_ (
    .A(data_input[11]),
    .B(_006_),
    .Y(_052_)
  );
  NOT _261_ (
    .A(_052_),
    .Y(_053_)
  );
  NAND _262_ (
    .A(reset),
    .B(_053_),
    .Y(_054_)
  );
  NOR _263_ (
    .A(_051_),
    .B(_054_),
    .Y(_000_[11])
  );
  NOR _264_ (
    .A(demux_0[12]),
    .B(_005_),
    .Y(_055_)
  );
  NOR _265_ (
    .A(data_input[12]),
    .B(_006_),
    .Y(_056_)
  );
  NOT _266_ (
    .A(_056_),
    .Y(_057_)
  );
  NAND _267_ (
    .A(reset),
    .B(_057_),
    .Y(_058_)
  );
  NOR _268_ (
    .A(_055_),
    .B(_058_),
    .Y(_000_[12])
  );
  NOR _269_ (
    .A(demux_0[13]),
    .B(_005_),
    .Y(_059_)
  );
  NOR _270_ (
    .A(data_input[13]),
    .B(_006_),
    .Y(_060_)
  );
  NOT _271_ (
    .A(_060_),
    .Y(_061_)
  );
  NAND _272_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NOR _273_ (
    .A(_059_),
    .B(_062_),
    .Y(_000_[13])
  );
  NOR _274_ (
    .A(demux_0[14]),
    .B(_005_),
    .Y(_063_)
  );
  NOR _275_ (
    .A(data_input[14]),
    .B(_006_),
    .Y(_064_)
  );
  NOT _276_ (
    .A(_064_),
    .Y(_065_)
  );
  NAND _277_ (
    .A(reset),
    .B(_065_),
    .Y(_066_)
  );
  NOR _278_ (
    .A(_063_),
    .B(_066_),
    .Y(_000_[14])
  );
  NOR _279_ (
    .A(demux_0[15]),
    .B(_005_),
    .Y(_067_)
  );
  NOR _280_ (
    .A(data_input[15]),
    .B(_006_),
    .Y(_068_)
  );
  NOT _281_ (
    .A(_068_),
    .Y(_069_)
  );
  NAND _282_ (
    .A(reset),
    .B(_069_),
    .Y(_070_)
  );
  NOR _283_ (
    .A(_067_),
    .B(_070_),
    .Y(_000_[15])
  );
  NOR _284_ (
    .A(demux_0[16]),
    .B(_005_),
    .Y(_071_)
  );
  NOR _285_ (
    .A(data_input[16]),
    .B(_006_),
    .Y(_072_)
  );
  NOT _286_ (
    .A(_072_),
    .Y(_073_)
  );
  NAND _287_ (
    .A(reset),
    .B(_073_),
    .Y(_074_)
  );
  NOR _288_ (
    .A(_071_),
    .B(_074_),
    .Y(_000_[16])
  );
  NOR _289_ (
    .A(demux_0[17]),
    .B(_005_),
    .Y(_075_)
  );
  NOR _290_ (
    .A(data_input[17]),
    .B(_006_),
    .Y(_076_)
  );
  NOT _291_ (
    .A(_076_),
    .Y(_077_)
  );
  NAND _292_ (
    .A(reset),
    .B(_077_),
    .Y(_078_)
  );
  NOR _293_ (
    .A(_075_),
    .B(_078_),
    .Y(_000_[17])
  );
  NOR _294_ (
    .A(demux_0[18]),
    .B(_005_),
    .Y(_079_)
  );
  NOR _295_ (
    .A(data_input[18]),
    .B(_006_),
    .Y(_080_)
  );
  NOT _296_ (
    .A(_080_),
    .Y(_081_)
  );
  NAND _297_ (
    .A(reset),
    .B(_081_),
    .Y(_082_)
  );
  NOR _298_ (
    .A(_079_),
    .B(_082_),
    .Y(_000_[18])
  );
  NOR _299_ (
    .A(demux_0[19]),
    .B(_005_),
    .Y(_083_)
  );
  NOR _300_ (
    .A(data_input[19]),
    .B(_006_),
    .Y(_084_)
  );
  NOT _301_ (
    .A(_084_),
    .Y(_085_)
  );
  NAND _302_ (
    .A(reset),
    .B(_085_),
    .Y(_086_)
  );
  NOR _303_ (
    .A(_083_),
    .B(_086_),
    .Y(_000_[19])
  );
  NOR _304_ (
    .A(demux_0[20]),
    .B(_005_),
    .Y(_087_)
  );
  NOR _305_ (
    .A(data_input[20]),
    .B(_006_),
    .Y(_088_)
  );
  NOT _306_ (
    .A(_088_),
    .Y(_089_)
  );
  NAND _307_ (
    .A(reset),
    .B(_089_),
    .Y(_090_)
  );
  NOR _308_ (
    .A(_087_),
    .B(_090_),
    .Y(_000_[20])
  );
  NOR _309_ (
    .A(demux_0[21]),
    .B(_005_),
    .Y(_091_)
  );
  NOR _310_ (
    .A(data_input[21]),
    .B(_006_),
    .Y(_092_)
  );
  NOT _311_ (
    .A(_092_),
    .Y(_093_)
  );
  NAND _312_ (
    .A(reset),
    .B(_093_),
    .Y(_094_)
  );
  NOR _313_ (
    .A(_091_),
    .B(_094_),
    .Y(_000_[21])
  );
  NOR _314_ (
    .A(demux_0[22]),
    .B(_005_),
    .Y(_095_)
  );
  NOR _315_ (
    .A(data_input[22]),
    .B(_006_),
    .Y(_096_)
  );
  NOT _316_ (
    .A(_096_),
    .Y(_097_)
  );
  NAND _317_ (
    .A(reset),
    .B(_097_),
    .Y(_098_)
  );
  NOR _318_ (
    .A(_095_),
    .B(_098_),
    .Y(_000_[22])
  );
  NOR _319_ (
    .A(demux_0[23]),
    .B(_005_),
    .Y(_099_)
  );
  NOR _320_ (
    .A(data_input[23]),
    .B(_006_),
    .Y(_100_)
  );
  NOT _321_ (
    .A(_100_),
    .Y(_101_)
  );
  NAND _322_ (
    .A(reset),
    .B(_101_),
    .Y(_102_)
  );
  NOR _323_ (
    .A(_099_),
    .B(_102_),
    .Y(_000_[23])
  );
  NOR _324_ (
    .A(demux_0[24]),
    .B(_005_),
    .Y(_103_)
  );
  NOR _325_ (
    .A(data_input[24]),
    .B(_006_),
    .Y(_104_)
  );
  NOT _326_ (
    .A(_104_),
    .Y(_105_)
  );
  NAND _327_ (
    .A(reset),
    .B(_105_),
    .Y(_106_)
  );
  NOR _328_ (
    .A(_103_),
    .B(_106_),
    .Y(_000_[24])
  );
  NOR _329_ (
    .A(demux_0[25]),
    .B(_005_),
    .Y(_107_)
  );
  NOR _330_ (
    .A(data_input[25]),
    .B(_006_),
    .Y(_108_)
  );
  NOT _331_ (
    .A(_108_),
    .Y(_109_)
  );
  NAND _332_ (
    .A(reset),
    .B(_109_),
    .Y(_110_)
  );
  NOR _333_ (
    .A(_107_),
    .B(_110_),
    .Y(_000_[25])
  );
  NOR _334_ (
    .A(demux_0[26]),
    .B(_005_),
    .Y(_111_)
  );
  NOR _335_ (
    .A(data_input[26]),
    .B(_006_),
    .Y(_112_)
  );
  NOT _336_ (
    .A(_112_),
    .Y(_113_)
  );
  NAND _337_ (
    .A(reset),
    .B(_113_),
    .Y(_114_)
  );
  NOR _338_ (
    .A(_111_),
    .B(_114_),
    .Y(_000_[26])
  );
  NOR _339_ (
    .A(demux_0[27]),
    .B(_005_),
    .Y(_115_)
  );
  NOR _340_ (
    .A(data_input[27]),
    .B(_006_),
    .Y(_116_)
  );
  NOT _341_ (
    .A(_116_),
    .Y(_117_)
  );
  NAND _342_ (
    .A(reset),
    .B(_117_),
    .Y(_118_)
  );
  NOR _343_ (
    .A(_115_),
    .B(_118_),
    .Y(_000_[27])
  );
  NOR _344_ (
    .A(demux_0[28]),
    .B(_005_),
    .Y(_119_)
  );
  NOR _345_ (
    .A(data_input[28]),
    .B(_006_),
    .Y(_120_)
  );
  NOT _346_ (
    .A(_120_),
    .Y(_121_)
  );
  NAND _347_ (
    .A(reset),
    .B(_121_),
    .Y(_122_)
  );
  NOR _348_ (
    .A(_119_),
    .B(_122_),
    .Y(_000_[28])
  );
  NOR _349_ (
    .A(demux_0[29]),
    .B(_005_),
    .Y(_123_)
  );
  NOR _350_ (
    .A(data_input[29]),
    .B(_006_),
    .Y(_124_)
  );
  NOT _351_ (
    .A(_124_),
    .Y(_125_)
  );
  NAND _352_ (
    .A(reset),
    .B(_125_),
    .Y(_126_)
  );
  NOR _353_ (
    .A(_123_),
    .B(_126_),
    .Y(_000_[29])
  );
  NOR _354_ (
    .A(demux_0[30]),
    .B(_005_),
    .Y(_127_)
  );
  NOR _355_ (
    .A(data_input[30]),
    .B(_006_),
    .Y(_128_)
  );
  NOT _356_ (
    .A(_128_),
    .Y(_129_)
  );
  NAND _357_ (
    .A(reset),
    .B(_129_),
    .Y(_130_)
  );
  NOR _358_ (
    .A(_127_),
    .B(_130_),
    .Y(_000_[30])
  );
  NOR _359_ (
    .A(demux_0[31]),
    .B(_005_),
    .Y(_131_)
  );
  NOR _360_ (
    .A(data_input[31]),
    .B(_006_),
    .Y(_132_)
  );
  NOT _361_ (
    .A(_132_),
    .Y(_133_)
  );
  NAND _362_ (
    .A(reset),
    .B(_133_),
    .Y(_134_)
  );
  NOR _363_ (
    .A(_131_),
    .B(_134_),
    .Y(_000_[31])
  );
  NAND _364_ (
    .A(reset),
    .B(_005_),
    .Y(_135_)
  );
  NOT _365_ (
    .A(_135_),
    .Y(_002_)
  );
  NAND _366_ (
    .A(demux_1_probador[0]),
    .B(_002_),
    .Y(_136_)
  );
  NAND _367_ (
    .A(data_input[0]),
    .B(_135_),
    .Y(_137_)
  );
  NAND _368_ (
    .A(_136_),
    .B(_137_),
    .Y(_001_[0])
  );
  NAND _369_ (
    .A(demux_1_probador[1]),
    .B(_002_),
    .Y(_138_)
  );
  NAND _370_ (
    .A(data_input[1]),
    .B(_135_),
    .Y(_139_)
  );
  NAND _371_ (
    .A(_138_),
    .B(_139_),
    .Y(_001_[1])
  );
  NAND _372_ (
    .A(demux_1_probador[2]),
    .B(_002_),
    .Y(_140_)
  );
  NAND _373_ (
    .A(data_input[2]),
    .B(_135_),
    .Y(_141_)
  );
  NAND _374_ (
    .A(_140_),
    .B(_141_),
    .Y(_001_[2])
  );
  NAND _375_ (
    .A(demux_1_probador[3]),
    .B(_002_),
    .Y(_142_)
  );
  NAND _376_ (
    .A(data_input[3]),
    .B(_135_),
    .Y(_143_)
  );
  NAND _377_ (
    .A(_142_),
    .B(_143_),
    .Y(_001_[3])
  );
  NAND _378_ (
    .A(demux_1_probador[4]),
    .B(_002_),
    .Y(_144_)
  );
  NAND _379_ (
    .A(data_input[4]),
    .B(_135_),
    .Y(_145_)
  );
  NAND _380_ (
    .A(_144_),
    .B(_145_),
    .Y(_001_[4])
  );
  NAND _381_ (
    .A(demux_1_probador[5]),
    .B(_002_),
    .Y(_146_)
  );
  NAND _382_ (
    .A(data_input[5]),
    .B(_135_),
    .Y(_147_)
  );
  NAND _383_ (
    .A(_146_),
    .B(_147_),
    .Y(_001_[5])
  );
  NAND _384_ (
    .A(demux_1_probador[6]),
    .B(_002_),
    .Y(_148_)
  );
  NAND _385_ (
    .A(data_input[6]),
    .B(_135_),
    .Y(_149_)
  );
  NAND _386_ (
    .A(_148_),
    .B(_149_),
    .Y(_001_[6])
  );
  NAND _387_ (
    .A(demux_1_probador[7]),
    .B(_002_),
    .Y(_150_)
  );
  NAND _388_ (
    .A(data_input[7]),
    .B(_135_),
    .Y(_151_)
  );
  NAND _389_ (
    .A(_150_),
    .B(_151_),
    .Y(_001_[7])
  );
  NAND _390_ (
    .A(demux_1_probador[8]),
    .B(_002_),
    .Y(_152_)
  );
  NAND _391_ (
    .A(data_input[8]),
    .B(_135_),
    .Y(_153_)
  );
  NAND _392_ (
    .A(_152_),
    .B(_153_),
    .Y(_001_[8])
  );
  NAND _393_ (
    .A(demux_1_probador[9]),
    .B(_002_),
    .Y(_154_)
  );
  NAND _394_ (
    .A(data_input[9]),
    .B(_135_),
    .Y(_155_)
  );
  NAND _395_ (
    .A(_154_),
    .B(_155_),
    .Y(_001_[9])
  );
  NAND _396_ (
    .A(demux_1_probador[10]),
    .B(_002_),
    .Y(_156_)
  );
  NAND _397_ (
    .A(data_input[10]),
    .B(_135_),
    .Y(_157_)
  );
  NAND _398_ (
    .A(_156_),
    .B(_157_),
    .Y(_001_[10])
  );
  NAND _399_ (
    .A(demux_1_probador[11]),
    .B(_002_),
    .Y(_158_)
  );
  NAND _400_ (
    .A(data_input[11]),
    .B(_135_),
    .Y(_159_)
  );
  NAND _401_ (
    .A(_158_),
    .B(_159_),
    .Y(_001_[11])
  );
  NAND _402_ (
    .A(demux_1_probador[12]),
    .B(_002_),
    .Y(_160_)
  );
  NAND _403_ (
    .A(data_input[12]),
    .B(_135_),
    .Y(_161_)
  );
  NAND _404_ (
    .A(_160_),
    .B(_161_),
    .Y(_001_[12])
  );
  NAND _405_ (
    .A(demux_1_probador[13]),
    .B(_002_),
    .Y(_162_)
  );
  NAND _406_ (
    .A(data_input[13]),
    .B(_135_),
    .Y(_163_)
  );
  NAND _407_ (
    .A(_162_),
    .B(_163_),
    .Y(_001_[13])
  );
  NAND _408_ (
    .A(demux_1_probador[14]),
    .B(_002_),
    .Y(_164_)
  );
  NAND _409_ (
    .A(data_input[14]),
    .B(_135_),
    .Y(_165_)
  );
  NAND _410_ (
    .A(_164_),
    .B(_165_),
    .Y(_001_[14])
  );
  NAND _411_ (
    .A(demux_1_probador[15]),
    .B(_002_),
    .Y(_166_)
  );
  NAND _412_ (
    .A(data_input[15]),
    .B(_135_),
    .Y(_167_)
  );
  NAND _413_ (
    .A(_166_),
    .B(_167_),
    .Y(_001_[15])
  );
  NAND _414_ (
    .A(demux_1_probador[16]),
    .B(_002_),
    .Y(_168_)
  );
  NAND _415_ (
    .A(data_input[16]),
    .B(_135_),
    .Y(_169_)
  );
  NAND _416_ (
    .A(_168_),
    .B(_169_),
    .Y(_001_[16])
  );
  NAND _417_ (
    .A(demux_1_probador[17]),
    .B(_002_),
    .Y(_170_)
  );
  NAND _418_ (
    .A(data_input[17]),
    .B(_135_),
    .Y(_171_)
  );
  NAND _419_ (
    .A(_170_),
    .B(_171_),
    .Y(_001_[17])
  );
  NAND _420_ (
    .A(demux_1_probador[18]),
    .B(_002_),
    .Y(_172_)
  );
  NAND _421_ (
    .A(data_input[18]),
    .B(_135_),
    .Y(_173_)
  );
  NAND _422_ (
    .A(_172_),
    .B(_173_),
    .Y(_001_[18])
  );
  NAND _423_ (
    .A(demux_1_probador[19]),
    .B(_002_),
    .Y(_174_)
  );
  NAND _424_ (
    .A(data_input[19]),
    .B(_135_),
    .Y(_175_)
  );
  NAND _425_ (
    .A(_174_),
    .B(_175_),
    .Y(_001_[19])
  );
  NAND _426_ (
    .A(demux_1_probador[20]),
    .B(_002_),
    .Y(_176_)
  );
  NAND _427_ (
    .A(data_input[20]),
    .B(_135_),
    .Y(_177_)
  );
  NAND _428_ (
    .A(_176_),
    .B(_177_),
    .Y(_001_[20])
  );
  NAND _429_ (
    .A(demux_1_probador[21]),
    .B(_002_),
    .Y(_178_)
  );
  NAND _430_ (
    .A(data_input[21]),
    .B(_135_),
    .Y(_179_)
  );
  NAND _431_ (
    .A(_178_),
    .B(_179_),
    .Y(_001_[21])
  );
  NAND _432_ (
    .A(demux_1_probador[22]),
    .B(_002_),
    .Y(_180_)
  );
  NAND _433_ (
    .A(data_input[22]),
    .B(_135_),
    .Y(_181_)
  );
  NAND _434_ (
    .A(_180_),
    .B(_181_),
    .Y(_001_[22])
  );
  NAND _435_ (
    .A(demux_1_probador[23]),
    .B(_002_),
    .Y(_182_)
  );
  NAND _436_ (
    .A(data_input[23]),
    .B(_135_),
    .Y(_183_)
  );
  NAND _437_ (
    .A(_182_),
    .B(_183_),
    .Y(_001_[23])
  );
  NAND _438_ (
    .A(demux_1_probador[24]),
    .B(_002_),
    .Y(_184_)
  );
  NAND _439_ (
    .A(data_input[24]),
    .B(_135_),
    .Y(_185_)
  );
  NAND _440_ (
    .A(_184_),
    .B(_185_),
    .Y(_001_[24])
  );
  NAND _441_ (
    .A(demux_1_probador[25]),
    .B(_002_),
    .Y(_186_)
  );
  NAND _442_ (
    .A(data_input[25]),
    .B(_135_),
    .Y(_187_)
  );
  NAND _443_ (
    .A(_186_),
    .B(_187_),
    .Y(_001_[25])
  );
  NAND _444_ (
    .A(demux_1_probador[26]),
    .B(_002_),
    .Y(_188_)
  );
  NAND _445_ (
    .A(data_input[26]),
    .B(_135_),
    .Y(_189_)
  );
  NAND _446_ (
    .A(_188_),
    .B(_189_),
    .Y(_001_[26])
  );
  NAND _447_ (
    .A(demux_1_probador[27]),
    .B(_002_),
    .Y(_190_)
  );
  NAND _448_ (
    .A(data_input[27]),
    .B(_135_),
    .Y(_191_)
  );
  NAND _449_ (
    .A(_190_),
    .B(_191_),
    .Y(_001_[27])
  );
  NAND _450_ (
    .A(demux_1_probador[28]),
    .B(_002_),
    .Y(_192_)
  );
  NAND _451_ (
    .A(data_input[28]),
    .B(_135_),
    .Y(_193_)
  );
  NAND _452_ (
    .A(_192_),
    .B(_193_),
    .Y(_001_[28])
  );
  NAND _453_ (
    .A(demux_1_probador[29]),
    .B(_002_),
    .Y(_194_)
  );
  NAND _454_ (
    .A(data_input[29]),
    .B(_135_),
    .Y(_195_)
  );
  NAND _455_ (
    .A(_194_),
    .B(_195_),
    .Y(_001_[29])
  );
  NAND _456_ (
    .A(demux_1_probador[30]),
    .B(_002_),
    .Y(_196_)
  );
  NAND _457_ (
    .A(data_input[30]),
    .B(_135_),
    .Y(_197_)
  );
  NAND _458_ (
    .A(_196_),
    .B(_197_),
    .Y(_001_[30])
  );
  NAND _459_ (
    .A(demux_1_probador[31]),
    .B(_002_),
    .Y(_198_)
  );
  NAND _460_ (
    .A(data_input[31]),
    .B(_135_),
    .Y(_199_)
  );
  NAND _461_ (
    .A(_198_),
    .B(_199_),
    .Y(_001_[31])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _462_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(demux_1_probador[0])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _463_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(demux_1_probador[1])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _464_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(demux_1_probador[2])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _465_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(demux_1_probador[3])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _466_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(demux_1_probador[4])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _467_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(demux_1_probador[5])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _468_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(demux_1_probador[6])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _469_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(demux_1_probador[7])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _470_ (
    .C(clk_2f),
    .D(_001_[8]),
    .Q(demux_1_probador[8])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _471_ (
    .C(clk_2f),
    .D(_001_[9]),
    .Q(demux_1_probador[9])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _472_ (
    .C(clk_2f),
    .D(_001_[10]),
    .Q(demux_1_probador[10])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _473_ (
    .C(clk_2f),
    .D(_001_[11]),
    .Q(demux_1_probador[11])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _474_ (
    .C(clk_2f),
    .D(_001_[12]),
    .Q(demux_1_probador[12])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _475_ (
    .C(clk_2f),
    .D(_001_[13]),
    .Q(demux_1_probador[13])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _476_ (
    .C(clk_2f),
    .D(_001_[14]),
    .Q(demux_1_probador[14])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _477_ (
    .C(clk_2f),
    .D(_001_[15]),
    .Q(demux_1_probador[15])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _478_ (
    .C(clk_2f),
    .D(_001_[16]),
    .Q(demux_1_probador[16])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _479_ (
    .C(clk_2f),
    .D(_001_[17]),
    .Q(demux_1_probador[17])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _480_ (
    .C(clk_2f),
    .D(_001_[18]),
    .Q(demux_1_probador[18])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _481_ (
    .C(clk_2f),
    .D(_001_[19]),
    .Q(demux_1_probador[19])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _482_ (
    .C(clk_2f),
    .D(_001_[20]),
    .Q(demux_1_probador[20])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _483_ (
    .C(clk_2f),
    .D(_001_[21]),
    .Q(demux_1_probador[21])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _484_ (
    .C(clk_2f),
    .D(_001_[22]),
    .Q(demux_1_probador[22])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _485_ (
    .C(clk_2f),
    .D(_001_[23]),
    .Q(demux_1_probador[23])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _486_ (
    .C(clk_2f),
    .D(_001_[24]),
    .Q(demux_1_probador[24])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _487_ (
    .C(clk_2f),
    .D(_001_[25]),
    .Q(demux_1_probador[25])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _488_ (
    .C(clk_2f),
    .D(_001_[26]),
    .Q(demux_1_probador[26])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _489_ (
    .C(clk_2f),
    .D(_001_[27]),
    .Q(demux_1_probador[27])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _490_ (
    .C(clk_2f),
    .D(_001_[28]),
    .Q(demux_1_probador[28])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _491_ (
    .C(clk_2f),
    .D(_001_[29]),
    .Q(demux_1_probador[29])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _492_ (
    .C(clk_2f),
    .D(_001_[30]),
    .Q(demux_1_probador[30])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _493_ (
    .C(clk_2f),
    .D(_001_[31]),
    .Q(demux_1_probador[31])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _494_ (
    .C(clk_2f),
    .D(_002_),
    .Q(valid_out)
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _495_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(demux_0[0])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _496_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(demux_0[1])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _497_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(demux_0[2])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _498_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(demux_0[3])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _499_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(demux_0[4])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _500_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(demux_0[5])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _501_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(demux_0[6])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _502_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(demux_0[7])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _503_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(demux_0[8])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _504_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(demux_0[9])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _505_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(demux_0[10])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _506_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(demux_0[11])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _507_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(demux_0[12])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _508_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(demux_0[13])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _509_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(demux_0[14])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _510_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(demux_0[15])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _511_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(demux_0[16])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _512_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(demux_0[17])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _513_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(demux_0[18])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _514_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(demux_0[19])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _515_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(demux_0[20])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _516_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(demux_0[21])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _517_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(demux_0[22])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _518_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(demux_0[23])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _519_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(demux_0[24])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _520_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(demux_0[25])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _521_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(demux_0[26])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _522_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(demux_0[27])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _523_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(demux_0[28])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _524_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(demux_0[29])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _525_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(demux_0[30])
  );
  (* src = "../recirculador_sintetizado/recirculador_sintetizado.v:10" *)
  DFF _526_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(demux_0[31])
  );
endmodule
