/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sintetizado_paralelo_serial_cmos.v:1" *)
module sintetizado_paralelo_serial_cmos(clk_4f, clk_32f, data_in, valid_in, data2send_estructural, data_out_estructural);
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "sintetizado_paralelo_serial_cmos.v:2" *)
  input clk_32f;
  (* src = "sintetizado_paralelo_serial_cmos.v:1" *)
  input clk_4f;
  (* src = "sintetizado_paralelo_serial_cmos.v:5" *)
  output [7:0] data2send_estructural;
  (* src = "sintetizado_paralelo_serial_cmos.v:3" *)
  input [7:0] data_in;
  (* src = "sintetizado_paralelo_serial_cmos.v:6" *)
  output data_out_estructural;
  (* src = "sintetizado_paralelo_serial_cmos.v:8" *)
  wire [2:0] selector;
  (* src = "sintetizado_paralelo_serial_cmos.v:4" *)
  input valid_in;
  NOT _09_ (
    .A(data_in[2]),
    .Y(_01_)
  );
  NOT _10_ (
    .A(data_in[3]),
    .Y(_02_)
  );
  NOT _11_ (
    .A(data_in[4]),
    .Y(_03_)
  );
  NOT _12_ (
    .A(data_in[5]),
    .Y(_04_)
  );
  NOT _13_ (
    .A(data_in[7]),
    .Y(_05_)
  );
  NAND _14_ (
    .A(data_in[0]),
    .B(valid_in),
    .Y(_06_)
  );
  NOT _15_ (
    .A(_06_),
    .Y(_00_[0])
  );
  NAND _16_ (
    .A(valid_in),
    .B(data_in[1]),
    .Y(_07_)
  );
  NOT _17_ (
    .A(_07_),
    .Y(_00_[1])
  );
  NAND _18_ (
    .A(valid_in),
    .B(_01_),
    .Y(_00_[2])
  );
  NAND _19_ (
    .A(valid_in),
    .B(_02_),
    .Y(_00_[3])
  );
  NAND _20_ (
    .A(valid_in),
    .B(_03_),
    .Y(_00_[4])
  );
  NAND _21_ (
    .A(valid_in),
    .B(_04_),
    .Y(_00_[5])
  );
  NAND _22_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_08_)
  );
  NOT _23_ (
    .A(_08_),
    .Y(_00_[6])
  );
  NAND _24_ (
    .A(valid_in),
    .B(_05_),
    .Y(_00_[7])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:20" *)
  DFF _25_ (
    .C(clk_32f),
    .D(_00_[7]),
    .Q(data_out_estructural)
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _26_ (
    .C(clk_4f),
    .D(_00_[0]),
    .Q(data2send_estructural[0])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _27_ (
    .C(clk_4f),
    .D(_00_[1]),
    .Q(data2send_estructural[1])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _28_ (
    .C(clk_4f),
    .D(_00_[2]),
    .Q(data2send_estructural[2])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _29_ (
    .C(clk_4f),
    .D(_00_[3]),
    .Q(data2send_estructural[3])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _30_ (
    .C(clk_4f),
    .D(_00_[4]),
    .Q(data2send_estructural[4])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _31_ (
    .C(clk_4f),
    .D(_00_[5]),
    .Q(data2send_estructural[5])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _32_ (
    .C(clk_4f),
    .D(_00_[6]),
    .Q(data2send_estructural[6])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  DFF _33_ (
    .C(clk_4f),
    .D(_00_[7]),
    .Q(data2send_estructural[7])
  );
  assign selector = 3'h0;
endmodule
