/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sintetizado_paralelo_serial_cmos.v:1" *)
module sintetizado_paralelo_serial_cmos(clk_4f, clk_32f, data_in, valid_in, reset, data2send_estructural, data_out_estructural);
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  wire [7:0] _00_;
  (* src = "sintetizado_paralelo_serial_cmos.v:22" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "sintetizado_paralelo_serial_cmos.v:2" *)
  input clk_32f;
  (* src = "sintetizado_paralelo_serial_cmos.v:1" *)
  input clk_4f;
  (* src = "sintetizado_paralelo_serial_cmos.v:6" *)
  output [7:0] data2send_estructural;
  (* src = "sintetizado_paralelo_serial_cmos.v:3" *)
  input [7:0] data_in;
  (* src = "sintetizado_paralelo_serial_cmos.v:7" *)
  output data_out_estructural;
  (* src = "sintetizado_paralelo_serial_cmos.v:5" *)
  input reset;
  (* src = "sintetizado_paralelo_serial_cmos.v:9" *)
  wire [2:0] selector;
  (* src = "sintetizado_paralelo_serial_cmos.v:4" *)
  input valid_in;
  NOT _12_ (
    .A(data_out_estructural),
    .Y(_02_)
  );
  NOT _13_ (
    .A(data_in[0]),
    .Y(_03_)
  );
  NOT _14_ (
    .A(data_in[1]),
    .Y(_04_)
  );
  NOT _15_ (
    .A(data_in[6]),
    .Y(_05_)
  );
  NOR _16_ (
    .A(reset),
    .B(_02_),
    .Y(_01_)
  );
  NAND _17_ (
    .A(reset),
    .B(valid_in),
    .Y(_06_)
  );
  NOR _18_ (
    .A(_03_),
    .B(_06_),
    .Y(_00_[0])
  );
  NOR _19_ (
    .A(_04_),
    .B(_06_),
    .Y(_00_[1])
  );
  NOR _20_ (
    .A(data_in[2]),
    .B(_06_),
    .Y(_07_)
  );
  NOT _21_ (
    .A(_07_),
    .Y(_00_[2])
  );
  NOR _22_ (
    .A(data_in[3]),
    .B(_06_),
    .Y(_08_)
  );
  NOT _23_ (
    .A(_08_),
    .Y(_00_[3])
  );
  NOR _24_ (
    .A(data_in[4]),
    .B(_06_),
    .Y(_09_)
  );
  NOT _25_ (
    .A(_09_),
    .Y(_00_[4])
  );
  NOR _26_ (
    .A(data_in[5]),
    .B(_06_),
    .Y(_10_)
  );
  NOT _27_ (
    .A(_10_),
    .Y(_00_[5])
  );
  NOR _28_ (
    .A(_05_),
    .B(_06_),
    .Y(_00_[6])
  );
  NOR _29_ (
    .A(data_in[7]),
    .B(_06_),
    .Y(_11_)
  );
  NOT _30_ (
    .A(_11_),
    .Y(_00_[7])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:22" *)
  DFF _31_ (
    .C(clk_32f),
    .D(_01_),
    .Q(data_out_estructural)
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _32_ (
    .C(clk_4f),
    .D(_00_[0]),
    .Q(data2send_estructural[0])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _33_ (
    .C(clk_4f),
    .D(_00_[1]),
    .Q(data2send_estructural[1])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _34_ (
    .C(clk_4f),
    .D(_00_[2]),
    .Q(data2send_estructural[2])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _35_ (
    .C(clk_4f),
    .D(_00_[3]),
    .Q(data2send_estructural[3])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _36_ (
    .C(clk_4f),
    .D(_00_[4]),
    .Q(data2send_estructural[4])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _37_ (
    .C(clk_4f),
    .D(_00_[5]),
    .Q(data2send_estructural[5])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _38_ (
    .C(clk_4f),
    .D(_00_[6]),
    .Q(data2send_estructural[6])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _39_ (
    .C(clk_4f),
    .D(_00_[7]),
    .Q(data2send_estructural[7])
  );
  assign selector = 3'h7;
endmodule
