/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sintetizado_paralelo_serial_cmos.v:1" *)
module sintetizado_paralelo_serial_cmos(clk_4f, clk_32f, data_in, valid_in, reset, data_out_estructural);
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] _00_;
  (* src = "sintetizado_paralelo_serial_cmos.v:22" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "sintetizado_paralelo_serial_cmos.v:2" *)
  input clk_32f;
  (* src = "sintetizado_paralelo_serial_cmos.v:1" *)
  input clk_4f;
  (* src = "sintetizado_paralelo_serial_cmos.v:10" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] data2send;
  (* src = "sintetizado_paralelo_serial_cmos.v:3" *)
  input [7:0] data_in;
  (* src = "sintetizado_paralelo_serial_cmos.v:7" *)
  output data_out_estructural;
  (* src = "sintetizado_paralelo_serial_cmos.v:5" *)
  input reset;
  (* src = "sintetizado_paralelo_serial_cmos.v:9" *)
  wire [2:0] selector;
  (* src = "sintetizado_paralelo_serial_cmos.v:4" *)
  input valid_in;
  NOT _05_ (
    .A(reset),
    .Y(_03_)
  );
  NAND _06_ (
    .A(data2send[7]),
    .B(reset),
    .Y(_04_)
  );
  NOT _07_ (
    .A(_04_),
    .Y(_01_)
  );
  NOR _08_ (
    .A(_03_),
    .B(data_in[7]),
    .Y(_02_)
  );
  NAND _09_ (
    .A(valid_in),
    .B(_02_),
    .Y(_00_[7])
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:22" *)
  DFF _10_ (
    .C(clk_32f),
    .D(_01_),
    .Q(data_out_estructural)
  );
  (* src = "sintetizado_paralelo_serial_cmos.v:12" *)
  DFF _11_ (
    .C(clk_4f),
    .D(_00_[7]),
    .Q(data2send[7])
  );
  assign selector = 3'h7;
endmodule
