/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sintetizado_serial_paralelo.v:1" *)
module sintetizado_serial_paralelo(reset, clk_4f, clk_32f, data_in, data2send, active, valid_out, data_out);
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire [2:0] _000_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire _001_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire [7:0] _002_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire [7:0] _003_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire _004_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire _005_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire [3:0] _006_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire [7:0] _007_;
  (* src = "sintetizado_serial_paralelo.v:18" *)
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  (* src = "sintetizado_serial_paralelo.v:12" *)
  wire [2:0] BC_counter;
  (* src = "sintetizado_serial_paralelo.v:7" *)
  output active;
  (* src = "sintetizado_serial_paralelo.v:4" *)
  input clk_32f;
  (* src = "sintetizado_serial_paralelo.v:3" *)
  input clk_4f;
  (* src = "sintetizado_serial_paralelo.v:6" *)
  output [7:0] data2send;
  (* src = "sintetizado_serial_paralelo.v:5" *)
  input data_in;
  (* src = "sintetizado_serial_paralelo.v:9" *)
  output [7:0] data_out;
  (* src = "sintetizado_serial_paralelo.v:14" *)
  wire dataout_on;
  (* src = "sintetizado_serial_paralelo.v:16" *)
  wire primero;
  (* src = "sintetizado_serial_paralelo.v:2" *)
  input reset;
  (* src = "sintetizado_serial_paralelo.v:11" *)
  wire [3:0] selector;
  (* src = "sintetizado_serial_paralelo.v:13" *)
  wire [7:0] transicion_dataout;
  (* src = "sintetizado_serial_paralelo.v:8" *)
  output valid_out;
  NOT _277_ (
    .A(data2send[0]),
    .Y(_250_)
  );
  NOT _278_ (
    .A(data2send[6]),
    .Y(_251_)
  );
  NOT _279_ (
    .A(selector[2]),
    .Y(_252_)
  );
  NOT _280_ (
    .A(selector[3]),
    .Y(_253_)
  );
  NOT _281_ (
    .A(selector[0]),
    .Y(_254_)
  );
  NOT _282_ (
    .A(selector[1]),
    .Y(_255_)
  );
  NOT _283_ (
    .A(BC_counter[0]),
    .Y(_256_)
  );
  NOT _284_ (
    .A(primero),
    .Y(_257_)
  );
  NOT _285_ (
    .A(transicion_dataout[6]),
    .Y(_258_)
  );
  NOT _286_ (
    .A(reset),
    .Y(_259_)
  );
  NOT _287_ (
    .A(data_in),
    .Y(_260_)
  );
  NOT _288_ (
    .A(active),
    .Y(_261_)
  );
  NOT _289_ (
    .A(BC_counter[2]),
    .Y(_262_)
  );
  NOT _290_ (
    .A(data_out[0]),
    .Y(_263_)
  );
  NOT _291_ (
    .A(data_out[1]),
    .Y(_264_)
  );
  NOT _292_ (
    .A(data_out[2]),
    .Y(_265_)
  );
  NOT _293_ (
    .A(data_out[3]),
    .Y(_266_)
  );
  NOT _294_ (
    .A(data_out[4]),
    .Y(_267_)
  );
  NOT _295_ (
    .A(data_out[5]),
    .Y(_268_)
  );
  NOT _296_ (
    .A(data_out[6]),
    .Y(_269_)
  );
  NOT _297_ (
    .A(data_out[7]),
    .Y(_270_)
  );
  NOR _298_ (
    .A(_252_),
    .B(selector[3]),
    .Y(_271_)
  );
  NAND _299_ (
    .A(selector[2]),
    .B(_253_),
    .Y(_272_)
  );
  NOR _300_ (
    .A(_255_),
    .B(_272_),
    .Y(_273_)
  );
  NAND _301_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_274_)
  );
  NOT _302_ (
    .A(_274_),
    .Y(_275_)
  );
  NOR _303_ (
    .A(_272_),
    .B(_274_),
    .Y(_276_)
  );
  NAND _304_ (
    .A(_271_),
    .B(_275_),
    .Y(_009_)
  );
  NOR _305_ (
    .A(primero),
    .B(_260_),
    .Y(_010_)
  );
  NAND _306_ (
    .A(_257_),
    .B(data_in),
    .Y(_011_)
  );
  NOR _307_ (
    .A(_009_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _308_ (
    .A(_257_),
    .B(dataout_on),
    .Y(_013_)
  );
  NAND _309_ (
    .A(dataout_on),
    .B(_010_),
    .Y(_014_)
  );
  NOR _310_ (
    .A(_009_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _311_ (
    .A(selector[0]),
    .B(primero),
    .Y(_016_)
  );
  NOR _312_ (
    .A(_257_),
    .B(_009_),
    .Y(_017_)
  );
  NAND _313_ (
    .A(primero),
    .B(_276_),
    .Y(_018_)
  );
  NAND _314_ (
    .A(_273_),
    .B(_016_),
    .Y(_019_)
  );
  NAND _315_ (
    .A(transicion_dataout[1]),
    .B(_019_),
    .Y(_020_)
  );
  NAND _316_ (
    .A(_254_),
    .B(selector[1]),
    .Y(_021_)
  );
  NOR _317_ (
    .A(_272_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _318_ (
    .A(_257_),
    .B(transicion_dataout[1]),
    .Y(_023_)
  );
  NOR _319_ (
    .A(_257_),
    .B(_260_),
    .Y(_024_)
  );
  NAND _320_ (
    .A(primero),
    .B(data_in),
    .Y(_025_)
  );
  NAND _321_ (
    .A(dataout_on),
    .B(_024_),
    .Y(_026_)
  );
  NOT _322_ (
    .A(_026_),
    .Y(_027_)
  );
  NAND _323_ (
    .A(_023_),
    .B(_026_),
    .Y(_028_)
  );
  NAND _324_ (
    .A(_022_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _325_ (
    .A(_020_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _326_ (
    .A(_015_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _327_ (
    .A(_259_),
    .B(_031_),
    .Y(_007_[1])
  );
  NOR _328_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_032_)
  );
  NAND _329_ (
    .A(selector[3]),
    .B(_032_),
    .Y(_033_)
  );
  NOR _330_ (
    .A(selector[2]),
    .B(_033_),
    .Y(_034_)
  );
  NOR _331_ (
    .A(_017_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _332_ (
    .A(transicion_dataout[0]),
    .B(_035_),
    .Y(_036_)
  );
  NOR _333_ (
    .A(_009_),
    .B(_026_),
    .Y(_037_)
  );
  NAND _334_ (
    .A(primero),
    .B(transicion_dataout[0]),
    .Y(_038_)
  );
  NAND _335_ (
    .A(_014_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _336_ (
    .A(_034_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _337_ (
    .A(_036_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _338_ (
    .A(_037_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _339_ (
    .A(_259_),
    .B(_042_),
    .Y(_007_[0])
  );
  NOR _340_ (
    .A(selector[2]),
    .B(selector[3]),
    .Y(_043_)
  );
  NOT _341_ (
    .A(_043_),
    .Y(_044_)
  );
  NOR _342_ (
    .A(selector[1]),
    .B(_044_),
    .Y(_045_)
  );
  NOT _343_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _344_ (
    .A(selector[0]),
    .B(_046_),
    .Y(_047_)
  );
  NAND _345_ (
    .A(_254_),
    .B(_045_),
    .Y(_048_)
  );
  NOR _346_ (
    .A(_009_),
    .B(_025_),
    .Y(_049_)
  );
  NAND _347_ (
    .A(data2send[0]),
    .B(primero),
    .Y(_050_)
  );
  NAND _348_ (
    .A(_011_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _349_ (
    .A(_034_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _350_ (
    .A(_250_),
    .B(_047_),
    .Y(_053_)
  );
  NAND _351_ (
    .A(_035_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _352_ (
    .A(_052_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _353_ (
    .A(_049_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _354_ (
    .A(_259_),
    .B(_056_),
    .Y(_002_[0])
  );
  NAND _355_ (
    .A(data2send[1]),
    .B(_019_),
    .Y(_057_)
  );
  NOR _356_ (
    .A(_047_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _357_ (
    .A(data2send[1]),
    .B(_257_),
    .Y(_059_)
  );
  NAND _358_ (
    .A(_025_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _359_ (
    .A(_022_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _360_ (
    .A(_012_),
    .B(_058_),
    .Y(_062_)
  );
  NAND _361_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _362_ (
    .A(reset),
    .B(_063_),
    .Y(_064_)
  );
  NOT _363_ (
    .A(_064_),
    .Y(_002_[1])
  );
  NAND _364_ (
    .A(selector[0]),
    .B(_255_),
    .Y(_065_)
  );
  NAND _365_ (
    .A(_021_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _366_ (
    .A(_254_),
    .B(primero),
    .Y(_067_)
  );
  NOR _367_ (
    .A(_272_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _368_ (
    .A(_271_),
    .B(_066_),
    .Y(_069_)
  );
  NOR _369_ (
    .A(selector[1]),
    .B(_272_),
    .Y(_070_)
  );
  NAND _370_ (
    .A(_255_),
    .B(_271_),
    .Y(_071_)
  );
  NOR _371_ (
    .A(_272_),
    .B(_065_),
    .Y(_072_)
  );
  NAND _372_ (
    .A(selector[0]),
    .B(_070_),
    .Y(_073_)
  );
  NOR _373_ (
    .A(primero),
    .B(_073_),
    .Y(_074_)
  );
  NOR _374_ (
    .A(_069_),
    .B(_074_),
    .Y(_075_)
  );
  NAND _375_ (
    .A(_066_),
    .B(_068_),
    .Y(_076_)
  );
  NAND _376_ (
    .A(transicion_dataout[2]),
    .B(_076_),
    .Y(_077_)
  );
  NOR _377_ (
    .A(_026_),
    .B(_073_),
    .Y(_078_)
  );
  NAND _378_ (
    .A(primero),
    .B(transicion_dataout[2]),
    .Y(_079_)
  );
  NAND _379_ (
    .A(_014_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _380_ (
    .A(_022_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _381_ (
    .A(_077_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _382_ (
    .A(_078_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _383_ (
    .A(_259_),
    .B(_083_),
    .Y(_007_[2])
  );
  NAND _384_ (
    .A(data2send[2]),
    .B(_048_),
    .Y(_084_)
  );
  NOR _385_ (
    .A(_075_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _386_ (
    .A(primero),
    .B(data2send[2]),
    .Y(_086_)
  );
  NAND _387_ (
    .A(_011_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _388_ (
    .A(_022_),
    .B(_087_),
    .Y(_088_)
  );
  NAND _389_ (
    .A(_024_),
    .B(_072_),
    .Y(_089_)
  );
  NAND _390_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _391_ (
    .A(_085_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _392_ (
    .A(_259_),
    .B(_091_),
    .Y(_002_[2])
  );
  NOR _393_ (
    .A(selector[0]),
    .B(_071_),
    .Y(_092_)
  );
  NAND _394_ (
    .A(_254_),
    .B(_070_),
    .Y(_093_)
  );
  NOR _395_ (
    .A(_026_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _396_ (
    .A(_014_),
    .B(_073_),
    .Y(_095_)
  );
  NOR _397_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _398_ (
    .A(primero),
    .B(_093_),
    .Y(_097_)
  );
  NOR _399_ (
    .A(_071_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _400_ (
    .A(_016_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _401_ (
    .A(transicion_dataout[3]),
    .B(_099_),
    .Y(_100_)
  );
  NAND _402_ (
    .A(_096_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _403_ (
    .A(reset),
    .B(_101_),
    .Y(_102_)
  );
  NOT _404_ (
    .A(_102_),
    .Y(_007_[3])
  );
  NAND _405_ (
    .A(data2send[3]),
    .B(_048_),
    .Y(_103_)
  );
  NOR _406_ (
    .A(_098_),
    .B(_103_),
    .Y(_104_)
  );
  NAND _407_ (
    .A(primero),
    .B(data2send[3]),
    .Y(_105_)
  );
  NAND _408_ (
    .A(_011_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _409_ (
    .A(_072_),
    .B(_106_),
    .Y(_107_)
  );
  NAND _410_ (
    .A(_024_),
    .B(_092_),
    .Y(_108_)
  );
  NAND _411_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _412_ (
    .A(_104_),
    .B(_109_),
    .Y(_110_)
  );
  NOR _413_ (
    .A(_259_),
    .B(_110_),
    .Y(_002_[3])
  );
  NAND _414_ (
    .A(selector[1]),
    .B(_043_),
    .Y(_111_)
  );
  NOR _415_ (
    .A(_254_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _416_ (
    .A(_275_),
    .B(_043_),
    .Y(_113_)
  );
  NAND _417_ (
    .A(_024_),
    .B(_112_),
    .Y(_114_)
  );
  NOR _418_ (
    .A(_011_),
    .B(_093_),
    .Y(_115_)
  );
  NOT _419_ (
    .A(_115_),
    .Y(_116_)
  );
  NAND _420_ (
    .A(_114_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _421_ (
    .A(dataout_on),
    .B(_117_),
    .Y(_118_)
  );
  NAND _422_ (
    .A(_093_),
    .B(_113_),
    .Y(_119_)
  );
  NOR _423_ (
    .A(primero),
    .B(_113_),
    .Y(_120_)
  );
  NOR _424_ (
    .A(_257_),
    .B(_093_),
    .Y(_121_)
  );
  NOR _425_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  NAND _426_ (
    .A(_119_),
    .B(_122_),
    .Y(_123_)
  );
  NAND _427_ (
    .A(transicion_dataout[4]),
    .B(_123_),
    .Y(_124_)
  );
  NAND _428_ (
    .A(_118_),
    .B(_124_),
    .Y(_125_)
  );
  NAND _429_ (
    .A(reset),
    .B(_125_),
    .Y(_126_)
  );
  NOT _430_ (
    .A(_126_),
    .Y(_007_[4])
  );
  NAND _431_ (
    .A(data2send[4]),
    .B(_123_),
    .Y(_127_)
  );
  NOR _432_ (
    .A(_047_),
    .B(_127_),
    .Y(_128_)
  );
  NOR _433_ (
    .A(_117_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _434_ (
    .A(_259_),
    .B(_129_),
    .Y(_002_[4])
  );
  NOR _435_ (
    .A(selector[0]),
    .B(_111_),
    .Y(_130_)
  );
  NAND _436_ (
    .A(_257_),
    .B(transicion_dataout[5]),
    .Y(_131_)
  );
  NAND _437_ (
    .A(_026_),
    .B(_131_),
    .Y(_132_)
  );
  NAND _438_ (
    .A(_130_),
    .B(_132_),
    .Y(_133_)
  );
  NOT _439_ (
    .A(_133_),
    .Y(_134_)
  );
  NAND _440_ (
    .A(transicion_dataout[5]),
    .B(_013_),
    .Y(_135_)
  );
  NAND _441_ (
    .A(_014_),
    .B(_135_),
    .Y(_136_)
  );
  NAND _442_ (
    .A(_112_),
    .B(_136_),
    .Y(_137_)
  );
  NAND _443_ (
    .A(transicion_dataout[5]),
    .B(_111_),
    .Y(_138_)
  );
  NAND _444_ (
    .A(_137_),
    .B(_138_),
    .Y(_139_)
  );
  NOR _445_ (
    .A(_134_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _446_ (
    .A(_259_),
    .B(_140_),
    .Y(_007_[5])
  );
  NAND _447_ (
    .A(_257_),
    .B(data2send[5]),
    .Y(_141_)
  );
  NAND _448_ (
    .A(_025_),
    .B(_141_),
    .Y(_142_)
  );
  NAND _449_ (
    .A(_130_),
    .B(_142_),
    .Y(_143_)
  );
  NAND _450_ (
    .A(_043_),
    .B(_065_),
    .Y(_144_)
  );
  NAND _451_ (
    .A(data2send[5]),
    .B(_144_),
    .Y(_145_)
  );
  NOT _452_ (
    .A(_145_),
    .Y(_146_)
  );
  NAND _453_ (
    .A(primero),
    .B(data2send[5]),
    .Y(_147_)
  );
  NAND _454_ (
    .A(_011_),
    .B(_147_),
    .Y(_148_)
  );
  NAND _455_ (
    .A(_112_),
    .B(_148_),
    .Y(_149_)
  );
  NAND _456_ (
    .A(_143_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _457_ (
    .A(_146_),
    .B(_150_),
    .Y(_151_)
  );
  NOR _458_ (
    .A(_259_),
    .B(_151_),
    .Y(_002_[5])
  );
  NAND _459_ (
    .A(selector[0]),
    .B(_045_),
    .Y(_152_)
  );
  NOR _460_ (
    .A(primero),
    .B(_258_),
    .Y(_153_)
  );
  NOR _461_ (
    .A(_027_),
    .B(_153_),
    .Y(_154_)
  );
  NOR _462_ (
    .A(_152_),
    .B(_154_),
    .Y(_155_)
  );
  NAND _463_ (
    .A(transicion_dataout[6]),
    .B(_013_),
    .Y(_156_)
  );
  NAND _464_ (
    .A(_014_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _465_ (
    .A(_130_),
    .B(_157_),
    .Y(_158_)
  );
  NAND _466_ (
    .A(transicion_dataout[6]),
    .B(_152_),
    .Y(_159_)
  );
  NOR _467_ (
    .A(_130_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _468_ (
    .A(_155_),
    .B(_160_),
    .Y(_161_)
  );
  NAND _469_ (
    .A(_158_),
    .B(_161_),
    .Y(_162_)
  );
  NAND _470_ (
    .A(reset),
    .B(_162_),
    .Y(_163_)
  );
  NOT _471_ (
    .A(_163_),
    .Y(_007_[6])
  );
  NOR _472_ (
    .A(_251_),
    .B(primero),
    .Y(_164_)
  );
  NOR _473_ (
    .A(_024_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _474_ (
    .A(_152_),
    .B(_165_),
    .Y(_166_)
  );
  NAND _475_ (
    .A(data2send[6]),
    .B(primero),
    .Y(_167_)
  );
  NAND _476_ (
    .A(_011_),
    .B(_167_),
    .Y(_168_)
  );
  NAND _477_ (
    .A(_130_),
    .B(_168_),
    .Y(_169_)
  );
  NAND _478_ (
    .A(_274_),
    .B(_043_),
    .Y(_170_)
  );
  NAND _479_ (
    .A(data2send[6]),
    .B(_170_),
    .Y(_171_)
  );
  NAND _480_ (
    .A(_169_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _481_ (
    .A(_166_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _482_ (
    .A(_259_),
    .B(_173_),
    .Y(_002_[6])
  );
  NAND _483_ (
    .A(_016_),
    .B(_045_),
    .Y(_174_)
  );
  NOR _484_ (
    .A(_011_),
    .B(_152_),
    .Y(_175_)
  );
  NOR _485_ (
    .A(_014_),
    .B(_152_),
    .Y(_176_)
  );
  NAND _486_ (
    .A(_257_),
    .B(transicion_dataout[7]),
    .Y(_177_)
  );
  NAND _487_ (
    .A(_026_),
    .B(_177_),
    .Y(_178_)
  );
  NAND _488_ (
    .A(_047_),
    .B(_178_),
    .Y(_179_)
  );
  NAND _489_ (
    .A(transicion_dataout[7]),
    .B(_174_),
    .Y(_180_)
  );
  NAND _490_ (
    .A(_179_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _491_ (
    .A(_176_),
    .B(_181_),
    .Y(_182_)
  );
  NOR _492_ (
    .A(_259_),
    .B(_182_),
    .Y(_007_[7])
  );
  NAND _493_ (
    .A(_257_),
    .B(_034_),
    .Y(_183_)
  );
  NOT _494_ (
    .A(_183_),
    .Y(_184_)
  );
  NOR _495_ (
    .A(_017_),
    .B(_184_),
    .Y(_185_)
  );
  NAND _496_ (
    .A(_018_),
    .B(_183_),
    .Y(_186_)
  );
  NOR _497_ (
    .A(_261_),
    .B(_185_),
    .Y(_187_)
  );
  NOR _498_ (
    .A(dataout_on),
    .B(_187_),
    .Y(_188_)
  );
  NOR _499_ (
    .A(_259_),
    .B(_188_),
    .Y(_004_)
  );
  NAND _500_ (
    .A(data2send[7]),
    .B(_174_),
    .Y(_189_)
  );
  NAND _501_ (
    .A(_024_),
    .B(_047_),
    .Y(_190_)
  );
  NAND _502_ (
    .A(_189_),
    .B(_190_),
    .Y(_191_)
  );
  NOR _503_ (
    .A(_175_),
    .B(_191_),
    .Y(_192_)
  );
  NOR _504_ (
    .A(_259_),
    .B(_192_),
    .Y(_002_[7])
  );
  NAND _505_ (
    .A(data2send[3]),
    .B(data2send[4]),
    .Y(_193_)
  );
  NAND _506_ (
    .A(data2send[5]),
    .B(data2send[7]),
    .Y(_194_)
  );
  NOR _507_ (
    .A(_193_),
    .B(_194_),
    .Y(_195_)
  );
  NOR _508_ (
    .A(data2send[1]),
    .B(data2send[6]),
    .Y(_196_)
  );
  NAND _509_ (
    .A(data2send[2]),
    .B(_196_),
    .Y(_197_)
  );
  NOR _510_ (
    .A(data2send[0]),
    .B(_197_),
    .Y(_198_)
  );
  NAND _511_ (
    .A(_195_),
    .B(_198_),
    .Y(_199_)
  );
  NOT _512_ (
    .A(_199_),
    .Y(_200_)
  );
  NAND _513_ (
    .A(_186_),
    .B(_200_),
    .Y(_201_)
  );
  NOR _514_ (
    .A(_256_),
    .B(_201_),
    .Y(_202_)
  );
  NAND _515_ (
    .A(_256_),
    .B(_201_),
    .Y(_203_)
  );
  NAND _516_ (
    .A(reset),
    .B(_203_),
    .Y(_204_)
  );
  NOR _517_ (
    .A(_202_),
    .B(_204_),
    .Y(_000_[0])
  );
  NAND _518_ (
    .A(BC_counter[1]),
    .B(_202_),
    .Y(_205_)
  );
  NOT _519_ (
    .A(_205_),
    .Y(_206_)
  );
  NOR _520_ (
    .A(BC_counter[1]),
    .B(_202_),
    .Y(_207_)
  );
  NOT _521_ (
    .A(_207_),
    .Y(_208_)
  );
  NAND _522_ (
    .A(reset),
    .B(_208_),
    .Y(_209_)
  );
  NOR _523_ (
    .A(_206_),
    .B(_209_),
    .Y(_000_[1])
  );
  NOR _524_ (
    .A(_262_),
    .B(_205_),
    .Y(_210_)
  );
  NAND _525_ (
    .A(_262_),
    .B(_205_),
    .Y(_211_)
  );
  NAND _526_ (
    .A(reset),
    .B(_211_),
    .Y(_212_)
  );
  NOR _527_ (
    .A(_210_),
    .B(_212_),
    .Y(_000_[2])
  );
  NOR _528_ (
    .A(_262_),
    .B(_185_),
    .Y(_213_)
  );
  NOR _529_ (
    .A(active),
    .B(_213_),
    .Y(_214_)
  );
  NOR _530_ (
    .A(_259_),
    .B(_214_),
    .Y(_001_)
  );
  NOR _531_ (
    .A(primero),
    .B(_034_),
    .Y(_215_)
  );
  NOR _532_ (
    .A(_259_),
    .B(_215_),
    .Y(_005_)
  );
  NAND _533_ (
    .A(reset),
    .B(_183_),
    .Y(_216_)
  );
  NOR _534_ (
    .A(selector[0]),
    .B(_216_),
    .Y(_006_[0])
  );
  NAND _535_ (
    .A(reset),
    .B(_066_),
    .Y(_217_)
  );
  NOT _536_ (
    .A(_217_),
    .Y(_006_[1])
  );
  NOR _537_ (
    .A(_252_),
    .B(_274_),
    .Y(_218_)
  );
  NAND _538_ (
    .A(_252_),
    .B(_274_),
    .Y(_219_)
  );
  NAND _539_ (
    .A(reset),
    .B(_219_),
    .Y(_220_)
  );
  NOR _540_ (
    .A(_218_),
    .B(_220_),
    .Y(_006_[2])
  );
  NOR _541_ (
    .A(_253_),
    .B(_218_),
    .Y(_221_)
  );
  NOR _542_ (
    .A(_276_),
    .B(_221_),
    .Y(_222_)
  );
  NAND _543_ (
    .A(reset),
    .B(_185_),
    .Y(_223_)
  );
  NOR _544_ (
    .A(_222_),
    .B(_223_),
    .Y(_006_[3])
  );
  NOR _545_ (
    .A(transicion_dataout[0]),
    .B(_185_),
    .Y(_224_)
  );
  NAND _546_ (
    .A(_263_),
    .B(_185_),
    .Y(_225_)
  );
  NAND _547_ (
    .A(reset),
    .B(_225_),
    .Y(_226_)
  );
  NOR _548_ (
    .A(_224_),
    .B(_226_),
    .Y(_003_[0])
  );
  NOR _549_ (
    .A(transicion_dataout[1]),
    .B(_185_),
    .Y(_227_)
  );
  NAND _550_ (
    .A(_264_),
    .B(_185_),
    .Y(_228_)
  );
  NAND _551_ (
    .A(reset),
    .B(_228_),
    .Y(_229_)
  );
  NOR _552_ (
    .A(_227_),
    .B(_229_),
    .Y(_003_[1])
  );
  NOR _553_ (
    .A(transicion_dataout[2]),
    .B(_185_),
    .Y(_230_)
  );
  NAND _554_ (
    .A(_265_),
    .B(_185_),
    .Y(_231_)
  );
  NAND _555_ (
    .A(reset),
    .B(_231_),
    .Y(_232_)
  );
  NOR _556_ (
    .A(_230_),
    .B(_232_),
    .Y(_003_[2])
  );
  NOR _557_ (
    .A(transicion_dataout[3]),
    .B(_185_),
    .Y(_233_)
  );
  NAND _558_ (
    .A(_266_),
    .B(_185_),
    .Y(_234_)
  );
  NAND _559_ (
    .A(reset),
    .B(_234_),
    .Y(_235_)
  );
  NOR _560_ (
    .A(_233_),
    .B(_235_),
    .Y(_003_[3])
  );
  NOR _561_ (
    .A(transicion_dataout[4]),
    .B(_185_),
    .Y(_236_)
  );
  NAND _562_ (
    .A(_267_),
    .B(_185_),
    .Y(_237_)
  );
  NAND _563_ (
    .A(reset),
    .B(_237_),
    .Y(_238_)
  );
  NOR _564_ (
    .A(_236_),
    .B(_238_),
    .Y(_003_[4])
  );
  NOR _565_ (
    .A(transicion_dataout[5]),
    .B(_185_),
    .Y(_239_)
  );
  NAND _566_ (
    .A(_268_),
    .B(_185_),
    .Y(_240_)
  );
  NAND _567_ (
    .A(reset),
    .B(_240_),
    .Y(_241_)
  );
  NOR _568_ (
    .A(_239_),
    .B(_241_),
    .Y(_003_[5])
  );
  NOR _569_ (
    .A(_269_),
    .B(_186_),
    .Y(_242_)
  );
  NOR _570_ (
    .A(_258_),
    .B(_185_),
    .Y(_243_)
  );
  NOR _571_ (
    .A(_242_),
    .B(_243_),
    .Y(_244_)
  );
  NOR _572_ (
    .A(_259_),
    .B(_244_),
    .Y(_003_[6])
  );
  NOR _573_ (
    .A(transicion_dataout[7]),
    .B(_185_),
    .Y(_245_)
  );
  NAND _574_ (
    .A(_270_),
    .B(_185_),
    .Y(_246_)
  );
  NAND _575_ (
    .A(reset),
    .B(_246_),
    .Y(_247_)
  );
  NOR _576_ (
    .A(_245_),
    .B(_247_),
    .Y(_003_[7])
  );
  NOR _577_ (
    .A(valid_out),
    .B(_186_),
    .Y(_248_)
  );
  NAND _578_ (
    .A(reset),
    .B(_201_),
    .Y(_249_)
  );
  NOR _579_ (
    .A(_248_),
    .B(_249_),
    .Y(_008_)
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _580_ (
    .C(clk_32f),
    .D(_008_),
    .Q(valid_out)
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _581_ (
    .C(clk_32f),
    .D(_003_[0]),
    .Q(data_out[0])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _582_ (
    .C(clk_32f),
    .D(_003_[1]),
    .Q(data_out[1])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _583_ (
    .C(clk_32f),
    .D(_003_[2]),
    .Q(data_out[2])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _584_ (
    .C(clk_32f),
    .D(_003_[3]),
    .Q(data_out[3])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _585_ (
    .C(clk_32f),
    .D(_003_[4]),
    .Q(data_out[4])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _586_ (
    .C(clk_32f),
    .D(_003_[5]),
    .Q(data_out[5])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _587_ (
    .C(clk_32f),
    .D(_003_[6]),
    .Q(data_out[6])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _588_ (
    .C(clk_32f),
    .D(_003_[7]),
    .Q(data_out[7])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _589_ (
    .C(clk_32f),
    .D(_006_[0]),
    .Q(selector[0])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _590_ (
    .C(clk_32f),
    .D(_006_[1]),
    .Q(selector[1])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _591_ (
    .C(clk_32f),
    .D(_006_[2]),
    .Q(selector[2])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _592_ (
    .C(clk_32f),
    .D(_006_[3]),
    .Q(selector[3])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _593_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(data2send[0])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _594_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(data2send[1])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _595_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(data2send[2])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _596_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(data2send[3])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _597_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(data2send[4])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _598_ (
    .C(clk_32f),
    .D(_002_[5]),
    .Q(data2send[5])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _599_ (
    .C(clk_32f),
    .D(_002_[6]),
    .Q(data2send[6])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _600_ (
    .C(clk_32f),
    .D(_002_[7]),
    .Q(data2send[7])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _601_ (
    .C(clk_32f),
    .D(_001_),
    .Q(active)
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _602_ (
    .C(clk_32f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _603_ (
    .C(clk_32f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _604_ (
    .C(clk_32f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _605_ (
    .C(clk_32f),
    .D(_007_[0]),
    .Q(transicion_dataout[0])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _606_ (
    .C(clk_32f),
    .D(_007_[1]),
    .Q(transicion_dataout[1])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _607_ (
    .C(clk_32f),
    .D(_007_[2]),
    .Q(transicion_dataout[2])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _608_ (
    .C(clk_32f),
    .D(_007_[3]),
    .Q(transicion_dataout[3])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _609_ (
    .C(clk_32f),
    .D(_007_[4]),
    .Q(transicion_dataout[4])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _610_ (
    .C(clk_32f),
    .D(_007_[5]),
    .Q(transicion_dataout[5])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _611_ (
    .C(clk_32f),
    .D(_007_[6]),
    .Q(transicion_dataout[6])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _612_ (
    .C(clk_32f),
    .D(_007_[7]),
    .Q(transicion_dataout[7])
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _613_ (
    .C(clk_32f),
    .D(_004_),
    .Q(dataout_on)
  );
  (* src = "sintetizado_serial_paralelo.v:18" *)
  DFF _614_ (
    .C(clk_32f),
    .D(_005_),
    .Q(primero)
  );
endmodule
